#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
timestamp=$(date -u +%Y%m%dT%H%M%SZ)

if [[ -z "${DEEPSEEK_ADAFLOOR_SMOKE_BASELINE_DIR:-}" ]]; then
    echo "set DEEPSEEK_ADAFLOOR_SMOKE_BASELINE_DIR to a completed n=16 two-step threshold actor probe" >&2
    exit 2
fi

export DEEPSEEK_ADAFLOOR_SMOKE_RUN_NAME="${DEEPSEEK_ADAFLOOR_SMOKE_RUN_NAME:-adafloor_ep16_floor8_threshold_2step_$timestamp}"
export DEEPSEEK_ADAFLOOR_SMOKE_TRAINING_STEPS=2
export DEEPSEEK_ADAFLOOR_SMOKE_TRAIN_BATCH_SIZE=32
export DEEPSEEK_ADAFLOOR_SMOKE_ROLLOUT_N=16
export DEEPSEEK_ADAFLOOR_SMOKE_MAX_PROMPT_LENGTH=1024
export DEEPSEEK_ADAFLOOR_SMOKE_MAX_RESPONSE_LENGTH=64
export DEEPSEEK_ADAFLOOR_SMOKE_TAIL_VALIDATE_LEVEL_TOKENS=4,16,32,64,64
export DEEPSEEK_ADAFLOOR_SMOKE_TASK_QUEUE_ENABLE=1
export DEEPSEEK_ADAFLOOR_SMOKE_RECOMPUTE_METHOD=uniform
export DEEPSEEK_ADAFLOOR_SMOKE_RECOMPUTE_NUM_LAYERS=1
export DEEPSEEK_ADAFLOOR_SMOKE_MOE_ALLTOALL_OVERLAP_COMM=False
export DEEPSEEK_ADAFLOOR_SMOKE_MOE_SHARED_EXPERT_OVERLAP=False
export DEEPSEEK_ADAFLOOR_SMOKE_DEALLOCATE_PIPELINE_OUTPUTS=False

echo "[DeepSeek threshold two-step] real_distcp=1 topology=EP16 floor=8 steps=$DEEPSEEK_ADAFLOOR_SMOKE_TRAINING_STEPS n=$DEEPSEEK_ADAFLOOR_SMOKE_ROLLOUT_N"
echo "[DeepSeek threshold two-step] baseline=$DEEPSEEK_ADAFLOOR_SMOKE_BASELINE_DIR"
exec "$SCRIPT_DIR/run_deepseek_v2_lite_adafloor_smoke.sh" "$@"
