#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$SCRIPT_DIR"

GROUPING="${DP2_EP8_GROUPING:-random}"
case "$GROUPING" in
    random|length_sorted) ;;
    *)
        echo "DP2_EP8_GROUPING must be random or length_sorted" >&2
        exit 2
        ;;
esac

DEFAULT_COMMON_EPOCH0_ROOT=/data/adafloor_shared_state/common_epoch0_probe_gpu09_kv380800_permanent
COMMON_EPOCH0_ROOT="${COMMON_EPOCH0_ROOT:-$DEFAULT_COMMON_EPOCH0_ROOT}"
COMMON_EPOCH0_DIR="${COMMON_EPOCH0_DIR:-$COMMON_EPOCH0_ROOT/epoch_000_mode0_probe}"
COMMON_EPOCH0_CKPT="${COMMON_EPOCH0_CKPT:-$COMMON_EPOCH0_DIR/checkpoints/qwen3moe_for_eagle3/global_step_5}"
RUN_NAME="${DP2_EP8_RUN_NAME:-dp2_ep8_${GROUPING}_adafloor_epoch1}"
OUTPUT_ROOT="${OUTPUT_ROOT:-$SCRIPT_DIR}"
RUN_DIR="$OUTPUT_ROOT/$RUN_NAME"
PLAN_DIR="${PLAN_DIR:-$RUN_DIR/planner}"

if [[ ! -d "$COMMON_EPOCH0_DIR/rollout_data" ]]; then
    echo "missing common epoch0 rollout data: $COMMON_EPOCH0_DIR" >&2
    exit 2
fi
PLANNING_BASELINE_DIR="$COMMON_EPOCH0_DIR"
if [[ ! -f "$COMMON_EPOCH0_DIR/offline_planning_history.json" ]]; then
    PLANNING_BASELINE_DIR="$RUN_DIR/epoch0_history_cache"
    mkdir -p "$PLANNING_BASELINE_DIR"
    ln -sfn "$COMMON_EPOCH0_DIR/rollout_data" \
        "$PLANNING_BASELINE_DIR/rollout_data"
    ln -sfn "$COMMON_EPOCH0_DIR/rollout_length" \
        "$PLANNING_BASELINE_DIR/rollout_length"
    if [[ ! -f "$PLANNING_BASELINE_DIR/offline_planning_history.json" ]]; then
        python3 "$SCRIPT_DIR/tools/build_offline_planning_history.py" \
            --baseline-dir "$PLANNING_BASELINE_DIR" \
            --steps "${PLAN_STEPS:-5}" \
            --responses-per-prompt "${ROLLOUT_N:-16}"
    fi
fi

resume_args=()
if [[ "${DP2_EP8_PLAN_ONLY:-0}" != "1" ]]; then
    if [[ ! -d "$COMMON_EPOCH0_CKPT" ]]; then
        echo "missing COMMON_EPOCH0_CKPT: $COMMON_EPOCH0_CKPT" >&2
        exit 2
    fi
    export VERL_RESET_TRAINER_PROGRESS_AFTER_RESUME="${VERL_RESET_TRAINER_PROGRESS_AFTER_RESUME:-1}"
    resume_args+=(trainer.resume_mode=resume_path)
    resume_args+=(trainer.resume_from_path="$COMMON_EPOCH0_CKPT")
fi

export HIERARCHICAL_DP2_EP8=1
export DP2_EP8_GROUPING="$GROUPING"
export VLLM_DP_SIZE=8
export VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY=natural
export VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_COMM_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_DISPATCH_WARMUP=0
export VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE=0
export VLLM_ASCEND_DP2_EP8_RETAIN_ALL_FLOOR_GROUPS=0
export VLLM_ASCEND_ELASTIC_LOCAL_GROUP_CREATION=1
export VLLM_ASCEND_MODE1_PRESERVE_KV_ON_SAME_FLOOR_NEXT_STEP=0
export VLLM_ASCEND_MODE1_STAGE_WEIGHTS_BEFORE_KV_REBUILD=1
export VLLM_ASCEND_MODE1_BOOTSTRAP_KV_BEFORE_WEIGHT_ONLOAD=1
export VLLM_ASCEND_MODE1_BOOTSTRAP_KV_TOKENS="${VLLM_ASCEND_MODE1_BOOTSTRAP_KV_TOKENS:-131072}"
export VLLM_ASCEND_MODE1_COLD_INIT_KV_TOKENS="${VLLM_ASCEND_MODE1_COLD_INIT_KV_TOKENS:-2048}"
export VLLM_ASCEND_MODE1_USE_COLD_INIT_KV_CAP=1
export VLLM_ASCEND_MODE1_PROFILE_MAX_TOKENS="${VLLM_ASCEND_MODE1_PROFILE_MAX_TOKENS:-2048}"
export VLLM_ASCEND_MODE1_PROFILE_AVOID_MC2_BOUNDARY=1
export VLLM_ASCEND_MODE1_PROFILE_MC2_AVOID_TOKENS=640
export VLLM_ASCEND_MODE1_USE_EXPLICIT_KV_CAP_FOR_INIT=0
export VLLM_ASCEND_MODE1_RELOAD_TRIM_ALLOCATOR=0
export VLLM_ASCEND_MODE1_RELOAD_SYNC_ON_TRIM=0
export VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC=1
export VLLM_ASCEND_MODE1_REFRESH_GROUPS_ON_KV_RESIZE=1
export VLLM_ASCEND_MODE1_FULLWORLD_REFRESH_MC2_WARMUP=1
export VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_MC2_WARMUP=1
export VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_MC2_WARMUP_TOKENS=32
export VLLM_ASCEND_MODE1_PARITY_MC2_WARMUP_ROUTE=global
export VLLM_ASCEND_MODE1_CLEAR_STALE_PARAM_DICTS_AFTER_OLD_KV=1
export VLLM_ROLLOUT_SHRINK_AWARE_SHORT_STEP_CAP_ENABLE=1
export VLLM_ROLLOUT_SHRINK_AWARE_SHORT_STEP_CAP_FLOORS=2,4,8
export VLLM_EPOCH_LENGTH_REGROUP_ENABLE=0
export VLLM_EAGER_BASELINE_NO_RESAMPLE=0
export VERL_PAIRED_REQUEST_SAMPLING_SEEDS=1
export VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG=1
export VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG_LIMIT=40
export VLLM_ASCEND_MODE1_RELEASE_MOE_RUNTIME_BEFORE_TRAINING=1
export VLLM_ASCEND_MODE1_TRAINING_MEMORY_GUARD=1
export VLLM_ASCEND_MODE1_TRAINING_MEMORY_GUARD_STRICT=1
export VLLM_ASCEND_MODE1_OFFLOAD_LOADED_WEIGHTS_AFTER_FULL_RESTORE=1
export VLLM_ASCEND_MODE1_OFFLOAD_CANONICAL_LOADED_WEIGHTS_AFTER_FULL_RESTORE=0
export VLLM_ASCEND_MODE1_TRAINING_MIN_FREE_MIB="${VLLM_ASCEND_MODE1_TRAINING_MIN_FREE_MIB:-28672}"
export REQUIRE_COMPACT_HISTORY=1
export CHECK_LOCAL_INPUTS="${CHECK_LOCAL_INPUTS:-1}"
export MAX_CROSS_STEP_REPAIR_SWAPS="${MAX_CROSS_STEP_REPAIR_SWAPS:-16}"
export REPAIR_CANDIDATE_LIMIT="${REPAIR_CANDIDATE_LIMIT:-16}"

echo "[dp2-ep8] grouping=$GROUPING common_epoch0=$COMMON_EPOCH0_DIR run_dir=$RUN_DIR"
echo "[dp2-ep8] topology=external_dp2_ep8 prompts_per_step=32 prompts_per_worker=16 prompts_per_rank=2 rollout_n=16"
echo "[dp2-ep8] lifecycle=natural floor_caps=${DP2_EP8_FLOOR_KV_CAPS:-2:131072,4:280576,8:377344} strict_kv=true"

OUTPUT_ROOT="$OUTPUT_ROOT" \
OUTPUT_SUBDIR="$RUN_NAME" \
BASELINE_DIRS="$PLANNING_BASELINE_DIR" \
PLAN_DIR="$PLAN_DIR" \
OPT_TRAIN_FILE="$PLAN_DIR/train.parquet" \
OPT_RANK_PLAN="$PLAN_DIR/rank_plan.json" \
OPT_SUMMARY="$PLAN_DIR/plan_summary.json" \
OPT_ORACLE="$PLAN_DIR/length_oracle.json" \
TRAINER_TOTAL_EPOCHS=1 \
PLAN_STEPS="${PLAN_STEPS:-5}" \
TRAIN_BATCH_SIZE=32 \
ROLLOUT_N=16 \
ROLLOUT_MAX_NUM_SEQS=32 \
DP2_EP8_FLOOR_KV_CAPS="${DP2_EP8_FLOOR_KV_CAPS:-2:131072,4:280576,8:377344}" \
"$SCRIPT_DIR/run_mode1_local_length_sorted_e2e_adaptive_floor2.sh" \
    "${resume_args[@]}" "$@"

if [[ "${DP2_EP8_PLAN_ONLY:-0}" == "1" ]]; then
    touch "$RUN_DIR/PLAN_ONLY_COMPLETE"
    echo "[dp2-ep8] plan-only complete grouping=$GROUPING plan=$PLAN_DIR/rank_plan.json"
    exit 0
fi

python3 "$SCRIPT_DIR/tools/summarize_dp2_ep8_run.py" \
    --run-dir "$RUN_DIR" \
    --plan-file "$PLAN_DIR/rank_plan.json" \
    --output "$RUN_DIR/dp2_ep8_summary.json" \
    --expected-steps "${PLAN_STEPS:-5}"

touch "$RUN_DIR/STRICT_RUN_COMPLETE"
echo "[dp2-ep8] complete grouping=$GROUPING summary=$RUN_DIR/dp2_ep8_summary.json"
