#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
timestamp=$(date -u +%Y%m%dT%H%M%SZ)

export DEEPSEEK_ACTOR_PROBE_RUN_NAME="${DEEPSEEK_ACTOR_PROBE_RUN_NAME:-threshold_actor_2step_n16_$timestamp}"
export DEEPSEEK_ACTOR_PROBE_TRAINING_STEPS="${DEEPSEEK_ACTOR_PROBE_TRAINING_STEPS:-2}"
export DEEPSEEK_ACTOR_PROBE_TRAIN_BATCH_SIZE="${DEEPSEEK_ACTOR_PROBE_TRAIN_BATCH_SIZE:-32}"
export DEEPSEEK_ACTOR_PROBE_ROLLOUT_N="${DEEPSEEK_ACTOR_PROBE_ROLLOUT_N:-16}"
export DEEPSEEK_ACTOR_PROBE_MAX_PROMPT_LENGTH="${DEEPSEEK_ACTOR_PROBE_MAX_PROMPT_LENGTH:-1024}"
export DEEPSEEK_ACTOR_PROBE_MAX_RESPONSE_LENGTH="${DEEPSEEK_ACTOR_PROBE_MAX_RESPONSE_LENGTH:-64}"
export DEEPSEEK_ACTOR_PROBE_MAX_NUM_BATCHED_TOKENS="${DEEPSEEK_ACTOR_PROBE_MAX_NUM_BATCHED_TOKENS:-1088}"
export DEEPSEEK_ACTOR_PROBE_ACTOR_TOKEN_CAP="${DEEPSEEK_ACTOR_PROBE_ACTOR_TOKEN_CAP:-1088}"
export DEEPSEEK_ACTOR_PROBE_LOG_PROB_TOKEN_CAP="${DEEPSEEK_ACTOR_PROBE_LOG_PROB_TOKEN_CAP:-1088}"
export DEEPSEEK_ACTOR_PROBE_KV_TOKENS_PER_RANK="${DEEPSEEK_ACTOR_PROBE_KV_TOKENS_PER_RANK:-16384}"
export DEEPSEEK_ACTOR_PROBE_DEALLOCATE_PIPELINE_OUTPUTS="${DEEPSEEK_ACTOR_PROBE_DEALLOCATE_PIPELINE_OUTPUTS:-True}"
export DEEPSEEK_ACTOR_PROBE_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP="${DEEPSEEK_ACTOR_PROBE_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP:-4,16,32,64,64;4,16,32,64,64}"

echo "[DeepSeek threshold actor smoke] mode=0 steps=$DEEPSEEK_ACTOR_PROBE_TRAINING_STEPS n=$DEEPSEEK_ACTOR_PROBE_ROLLOUT_N caps=$DEEPSEEK_ACTOR_PROBE_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP"
exec "$SCRIPT_DIR/run_deepseek_v2_lite_actor_update_probe.sh" "$@"
