#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
timestamp=$(date -u +%Y%m%dT%H%M%SZ)
OUTPUT_ROOT=${DEEPSEEK_THRESHOLD_ADAFLOOR_OUTPUT_ROOT:-/data/adafloor_shared_state/deepseek_v2_lite}
RUN_NAME=${DEEPSEEK_THRESHOLD_ADAFLOOR_RUN_NAME:-threshold_adafloor_two_step_tq1_$timestamp}
RUN_ROOT=$OUTPUT_ROOT/$RUN_NAME
MODE0_NAME=mode0_threshold_history
MODE1_NAME=mode1_ep16_to_ep8
MODE0_ROOT=$RUN_ROOT/$MODE0_NAME
MODE1_ROOT=$RUN_ROOT/$MODE1_NAME
CAPS_BY_STEP='4,16,32,64,64;4,16,32,64,64'

if (( $# != 0 )); then
    echo "DeepSeek threshold AdaFloor smoke does not accept overrides" >&2
    exit 2
fi
if [[ -e "$RUN_ROOT" ]]; then
    echo "refusing to overwrite DeepSeek threshold AdaFloor smoke: $RUN_ROOT" >&2
    exit 2
fi

mkdir -p "$RUN_ROOT"
printf '%s\n' "INCOMPLETE DeepSeek threshold AdaFloor two-step smoke" \
    > "$RUN_ROOT/INCOMPLETE"

echo "[DeepSeek threshold AdaFloor smoke] phase=mode0 output=$MODE0_ROOT"
DEEPSEEK_ACTOR_PROBE_OUTPUT_ROOT="$RUN_ROOT" \
DEEPSEEK_ACTOR_PROBE_RUN_NAME="$MODE0_NAME" \
DEEPSEEK_ACTOR_PROBE_TRAINING_STEPS=2 \
DEEPSEEK_ACTOR_PROBE_TRAIN_BATCH_SIZE=32 \
DEEPSEEK_ACTOR_PROBE_ROLLOUT_N=16 \
DEEPSEEK_ACTOR_PROBE_MAX_PROMPT_LENGTH=1024 \
DEEPSEEK_ACTOR_PROBE_MAX_RESPONSE_LENGTH=64 \
DEEPSEEK_ACTOR_PROBE_MAX_NUM_BATCHED_TOKENS=1088 \
DEEPSEEK_ACTOR_PROBE_ACTOR_TOKEN_CAP=1088 \
DEEPSEEK_ACTOR_PROBE_LOG_PROB_TOKEN_CAP=1088 \
DEEPSEEK_ACTOR_PROBE_KV_TOKENS_PER_RANK=16384 \
DEEPSEEK_ACTOR_PROBE_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP="$CAPS_BY_STEP" \
DEEPSEEK_ACTOR_PROBE_TASK_QUEUE_ENABLE=1 \
DEEPSEEK_ACTOR_PROBE_RECOMPUTE_METHOD=uniform \
DEEPSEEK_ACTOR_PROBE_RECOMPUTE_NUM_LAYERS=1 \
DEEPSEEK_ACTOR_PROBE_MOE_ALLTOALL_OVERLAP_COMM=False \
DEEPSEEK_ACTOR_PROBE_MOE_SHARED_EXPERT_OVERLAP=False \
DEEPSEEK_ACTOR_PROBE_DEALLOCATE_PIPELINE_OUTPUTS=False \
"$SCRIPT_DIR/run_deepseek_v2_lite_threshold_actor_two_step_tq1_smoke.sh"

if [[ ! -f "$MODE0_ROOT/COMPLETE" ]]; then
    echo "DeepSeek threshold mode0 phase did not produce COMPLETE" >&2
    exit 3
fi

echo "[DeepSeek threshold AdaFloor smoke] phase=mode1 output=$MODE1_ROOT"
DEEPSEEK_ADAFLOOR_SMOKE_OUTPUT_ROOT="$RUN_ROOT" \
DEEPSEEK_ADAFLOOR_SMOKE_RUN_NAME="$MODE1_NAME" \
DEEPSEEK_ADAFLOOR_SMOKE_BASELINE_DIR="$MODE0_ROOT/epoch_000_mode0_probe" \
DEEPSEEK_ADAFLOOR_SMOKE_KV_TOKENS=16384 \
DEEPSEEK_ADAFLOOR_SMOKE_TRAINING_STEPS=2 \
DEEPSEEK_ADAFLOOR_SMOKE_TRAIN_BATCH_SIZE=32 \
DEEPSEEK_ADAFLOOR_SMOKE_ROLLOUT_N=16 \
DEEPSEEK_ADAFLOOR_SMOKE_MAX_PROMPT_LENGTH=1024 \
DEEPSEEK_ADAFLOOR_SMOKE_MAX_RESPONSE_LENGTH=64 \
DEEPSEEK_ADAFLOOR_SMOKE_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP="$CAPS_BY_STEP" \
DEEPSEEK_ADAFLOOR_SMOKE_TASK_QUEUE_ENABLE=1 \
DEEPSEEK_ADAFLOOR_SMOKE_RECOMPUTE_METHOD=uniform \
DEEPSEEK_ADAFLOOR_SMOKE_RECOMPUTE_NUM_LAYERS=1 \
DEEPSEEK_ADAFLOOR_SMOKE_MOE_ALLTOALL_OVERLAP_COMM=False \
DEEPSEEK_ADAFLOOR_SMOKE_MOE_SHARED_EXPERT_OVERLAP=False \
DEEPSEEK_ADAFLOOR_SMOKE_DEALLOCATE_PIPELINE_OUTPUTS=False \
"$SCRIPT_DIR/run_deepseek_v2_lite_adafloor_smoke.sh"

if [[ ! -f "$MODE1_ROOT/COMPLETE" ]]; then
    echo "DeepSeek threshold mode1 phase did not produce COMPLETE" >&2
    exit 3
fi

rm -f "$RUN_ROOT/INCOMPLETE"
printf '%s\n' \
    "COMPLETE DeepSeek threshold AdaFloor two-step smoke" \
    "MODE0_ROOT=$MODE0_ROOT" \
    "MODE1_ROOT=$MODE1_ROOT" \
    "TRANSITION=16-to-8" \
    "TRAINING_STEPS=2" \
    "RESPONSES_PER_STEP=512" \
    "KV_POLICY=smoke-only-not-calibrated" \
    "TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP=$CAPS_BY_STEP" \
    > "$RUN_ROOT/COMPLETE"

echo "[DeepSeek threshold AdaFloor smoke] complete root=$RUN_ROOT"
