#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

DP2_EP8_GROUPING=random \
DP2_EP8_RUN_NAME="${DP2_EP8_RUN_NAME:-dp2_ep8_random_adafloor_epoch1}" \
HCCL_IF_BASE_PORT="${DP2_EP8_RANDOM_HCCL_IF_BASE_PORT:-18000}" \
VERL_HCCL_IF_BASE_PORT_START="${DP2_EP8_RANDOM_HCCL_IF_BASE_PORT:-18000}" \
MASTER_PORT="${DP2_EP8_RANDOM_MASTER_PORT:-15000}" \
VERL_MASTER_PORT_START="${DP2_EP8_RANDOM_MASTER_PORT:-15000}" \
"$SCRIPT_DIR/run_dp2_ep8_adafloor_one_epoch.sh" "$@"
