#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Short natural-policy probe for the floor2 expert-weight reload path.  The
# default is intentionally a single floor2 step so correctness bugs are caught
# before spending time on the longer floor2 -> floor4 -> floor16 sequence.
#
# Full 5-step shape, enabled by overriding the step/floor envs:
#   step1 selected_floor=2, short caps by rank bucket: 8*8,16*4,32*2,64*2
#   step2 selected_floor=2, same caps
#   step3 selected_floor=4, short caps by rank bucket: 8*8,16*4,32*4
#   step4 selected_floor=4, same caps, should not trigger a floor/KV switch
#   step5 selected_floor=16, short full-world sanity step
#
# The goal is not training quality.  It is to quickly check whether the floor2
# expert weights are loaded into all active slots before generate.  After the
# single-step smoke test is clean, run the 5-step sequence explicitly.

BASELINE_EPOCH0="${DYNAMIC_INITIAL_BASELINE_DIR:-$SCRIPT_DIR/mode1_dynamic_length_aware_adaptive_floor4_natural_tailguard_full3/epoch_000_mode0_probe}"

if [[ ! -d "$BASELINE_EPOCH0/rollout_data" ]]; then
    echo "missing reusable epoch0 rollout data: $BASELINE_EPOCH0/rollout_data" >&2
    exit 2
fi

export DYNAMIC_RUN_NAME="${DYNAMIC_RUN_NAME:-mode1_dynamic_floor2_to_floor4_kv_probe}"
export DYNAMIC_TOTAL_EPOCHS=2
export DYNAMIC_START_EPOCH=1
export DYNAMIC_SHRINK_POLICY=natural
export DYNAMIC_SKIP_MODE0_PROBE=1
export DYNAMIC_INITIAL_BASELINE_DIR="$BASELINE_EPOCH0"
export DYNAMIC_ENABLE_CKPT_CHAIN=0
export DYNAMIC_PLAN_STEPS="${DYNAMIC_PLAN_STEPS:-1}"
export DYNAMIC_TRAIN_STEPS="${DYNAMIC_TRAIN_STEPS:-1}"
export DYNAMIC_DATASET_FRACTION="${DYNAMIC_DATASET_FRACTION:-0.005}"

export VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY=natural
export VLLM_ASCEND_SHRINK_AWARE_STAGES=8,4,2
export VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE=2
export MIN_ADAPTIVE_FLOOR=2
export DYNAMIC_FORCE_SELECTED_FLOORS="${DYNAMIC_FORCE_SELECTED_FLOORS:-2}"
export MAX_CROSS_STEP_REPAIR_SWAPS=0
export IGNORE_TAIL_TIES_AT_RESPONSE_CAP=1

export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2:-131072}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4:-280576}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8:-315648}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR16="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR16:-380800}"
export FLOOR_KV_CAPS="${FLOOR_KV_CAPS:-2:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2},4:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4},8:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8},16:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR16}}"

export DYNAMIC_ENABLE_THRESHOLD_CONTROL=0
# Tail validate caps are applied to repeated-halving rank buckets [8, 4, 2, 1, 1].
# Keep the synthetic decode tail identical across forced 2,2,4,4,16 steps so
# timing differences reflect floor transitions rather than different lengths.
export DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP="${DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP:-8,16,32,64,64;8,16,32,64,64;8,16,32,64,64;8,16,32,64,64;8,16,32,64,64}"
export DYNAMIC_FULL_MAX_PROMPT_LENGTH="${DYNAMIC_FULL_MAX_PROMPT_LENGTH:-1024}"
export DYNAMIC_FULL_MAX_RESPONSE_LENGTH="${DYNAMIC_FULL_MAX_RESPONSE_LENGTH:-1024}"
export DYNAMIC_FULL_MAX_RESPONSE_LEN="${DYNAMIC_FULL_MAX_RESPONSE_LEN:-1024}"
export DYNAMIC_FULL_MAX_NUM_BATCHED_TOKENS="${DYNAMIC_FULL_MAX_NUM_BATCHED_TOKENS:-2048}"

export DYNAMIC_SHORT_STEP_CAP_ENABLE=0
export DYNAMIC_TAIL_GUARD_MIN_CAP="${DYNAMIC_TAIL_GUARD_MIN_CAP:-1024}"
export DYNAMIC_TAIL_GUARD_ROUND_TO="${DYNAMIC_TAIL_GUARD_ROUND_TO:-64}"

# Natural mode should not retain planned floor communicators.
export VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_COMM_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_DISPATCH_WARMUP=0
export VLLM_ASCEND_MODE1_PARITY_MC2_WARMUP_ROUTE="${VLLM_ASCEND_MODE1_PARITY_MC2_WARMUP_ROUTE:-local}"
export VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY=0
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_FULL_RESTORE=0
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_PRE_REBUILD=0
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_STASH=0
export VLLM_ASCEND_MODE1_PARITY_DEFER_DESTROY_FLOOR_GROUP_SIZES="${VLLM_ASCEND_MODE1_PARITY_DEFER_DESTROY_FLOOR_GROUP_SIZES:-1,2,4,8}"
export VLLM_ASCEND_MODE1_PARITY_PRESERVE_DEVICE_PG_ON_FULL_RESTORE=0
export VLLM_ASCEND_MODE1_PARITY_PRESERVE_GROUP_REFS_ON_FULL_RESTORE=0
export VLLM_ASCEND_MODE1_PARITY_SKIP_CLEANUP_ON_PRESERVED_FULL_RESTORE=0

# Keep only the useful memory/KV timeline logs; avoid the very hot MC2 logs.
export VLLM_ASCEND_MODE1_RELOAD_TRIM_ALLOCATOR=0
export VLLM_ASCEND_MODE1_RELOAD_SYNC_ON_TRIM=0
export VLLM_ASCEND_FULL_REDUNDANCY_EXPERIMENT_LOG="${VLLM_ASCEND_FULL_REDUNDANCY_EXPERIMENT_LOG:-0}"
# DP metadata sync only exchanges a few int32 values.  Keep it on the CPU group
# so new shrink DP groups do not lazily allocate a large NPU HCCL workspace on
# the first real decode after shrink.
export VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC="${VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC:-1}"
# Keep the old stable lifecycle by default: trainer mode releases rollout KV,
# and the next rollout rebuilds it.  Preserving KV across trainer mode can move
# the OOM earlier because actor/rollout weight sync then runs with KV resident.
export VLLM_ASCEND_MODE1_PRESERVE_KV_ON_SAME_FLOOR_NEXT_STEP=0
export VLLM_ASCEND_MODE1_STAGE_WEIGHTS_BEFORE_KV_REBUILD="${VLLM_ASCEND_MODE1_STAGE_WEIGHTS_BEFORE_KV_REBUILD:-1}"
export VLLM_ASCEND_MODE1_SKIP_PRE_WEIGHT_KV_RESUME="${VLLM_ASCEND_MODE1_SKIP_PRE_WEIGHT_KV_RESUME:-1}"
export VLLM_ASCEND_MODE1_BOOTSTRAP_KV_BEFORE_WEIGHT_ONLOAD="${VLLM_ASCEND_MODE1_BOOTSTRAP_KV_BEFORE_WEIGHT_ONLOAD:-1}"
export VLLM_ASCEND_MODE1_BOOTSTRAP_KV_TOKENS="${VLLM_ASCEND_MODE1_BOOTSTRAP_KV_TOKENS:-${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2}}"
export VLLM_ASCEND_MODE1_COLD_INIT_KV_TOKENS="${VLLM_ASCEND_MODE1_COLD_INIT_KV_TOKENS:-2048}"
export VLLM_ASCEND_MODE1_USE_COLD_INIT_KV_CAP="${VLLM_ASCEND_MODE1_USE_COLD_INIT_KV_CAP:-1}"
# The short probe profiles the real mode1 rollout lifecycle separately.  The
# extra synthetic 512-token MC2 boundary profile can allocate a large HCCL
# dispatch workspace before mode1 cleanup/warmup runs, so keep it disabled here.
export VLLM_ASCEND_MODE1_PROFILE_EXTRA_MC2_DUMMY="${VLLM_ASCEND_MODE1_PROFILE_EXTRA_MC2_DUMMY:-0}"
export VLLM_ASCEND_MODE1_PROFILE_MC2_DUMMY_TOKENS="${VLLM_ASCEND_MODE1_PROFILE_MC2_DUMMY_TOKENS:-128}"
export VLLM_ASCEND_MODE1_PROFILE_MAX_TOKENS="${VLLM_ASCEND_MODE1_PROFILE_MAX_TOKENS:-2048}"
export VLLM_ASCEND_MODE1_PROFILE_AVOID_MC2_BOUNDARY="${VLLM_ASCEND_MODE1_PROFILE_AVOID_MC2_BOUNDARY:-1}"
export VLLM_ASCEND_MODE1_PROFILE_MC2_AVOID_TOKENS="${VLLM_ASCEND_MODE1_PROFILE_MC2_AVOID_TOKENS:-640}"
export VLLM_ASCEND_MODE1_USE_EXPLICIT_KV_CAP_FOR_INIT="${VLLM_ASCEND_MODE1_USE_EXPLICIT_KV_CAP_FOR_INIT:-0}"
export VLLM_ASCEND_MODE1_CLEAR_STALE_PARAM_DICTS_AFTER_OLD_KV=1
export VLLM_ASCEND_MODE1_AGGRESSIVE_RELEASE_OLD_PARAM_STORAGE="${VLLM_ASCEND_MODE1_AGGRESSIVE_RELEASE_OLD_PARAM_STORAGE:-1}"
export VLLM_ASCEND_MODE1_OFFLOAD_LOADED_WEIGHTS_AFTER_FULL_RESTORE="${VLLM_ASCEND_MODE1_OFFLOAD_LOADED_WEIGHTS_AFTER_FULL_RESTORE:-1}"
export VLLM_ASCEND_MODE1_OFFLOAD_CANONICAL_LOADED_WEIGHTS_AFTER_FULL_RESTORE="${VLLM_ASCEND_MODE1_OFFLOAD_CANONICAL_LOADED_WEIGHTS_AFTER_FULL_RESTORE:-0}"
export VLLM_ASCEND_MODE1_SYNC_AFTER_FULL_RESTORE_WEIGHT_OFFLOAD="${VLLM_ASCEND_MODE1_SYNC_AFTER_FULL_RESTORE_WEIGHT_OFFLOAD:-1}"
# Old KV is released before upward floor prepare, so avoid repeated allocator
# cache trims inside the per-layer compact loop.  The resize memory query later
# still performs one empty/sync before planning the new KV cache.
export VLLM_ASCEND_MODE1_EMPTY_CACHE_AFTER_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_EMPTY_CACHE_AFTER_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_BEFORE_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_EMPTY_CACHE_BEFORE_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_CLEAR_STALE_PARAMS_DURING_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_CLEAR_STALE_PARAMS_DURING_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_DURING_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_EMPTY_CACHE_DURING_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_UPWARD_COMPACT_RELEASE_EVERY_LAYERS="${VLLM_ASCEND_MODE1_UPWARD_COMPACT_RELEASE_EVERY_LAYERS:-48}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_BETWEEN_COMPACT_TENSORS="${VLLM_ASCEND_MODE1_EMPTY_CACHE_BETWEEN_COMPACT_TENSORS:-0}"
export VLLM_ASCEND_MODE1_UPWARD_CLEANUP_FINAL_EMPTY_CACHE="${VLLM_ASCEND_MODE1_UPWARD_CLEANUP_FINAL_EMPTY_CACHE:-0}"
export VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG=0
export VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG_ALL=0
export VLLM_ASCEND_CUSTOM_MODE1_ROLLOUT_RELOAD_DIAG=0
export VLLM_ASCEND_MODE1_FULLWORLD_RESTORE_DIAG="${VLLM_ASCEND_MODE1_FULLWORLD_RESTORE_DIAG:-0}"
export VLLM_ASCEND_MODE1_FULLWORLD_RESTORE_DIAG_DISPATCH_BUDGET="${VLLM_ASCEND_MODE1_FULLWORLD_RESTORE_DIAG_DISPATCH_BUDGET:-16}"
export VLLM_ASCEND_MODE1_MC2_RUNTIME_DIAG_SYNC="${VLLM_ASCEND_MODE1_MC2_RUNTIME_DIAG_SYNC:-0}"
export VLLM_ASCEND_MODE1_MC2_RUNTIME_DIAG_SYNC_ALL_LAYERS="${VLLM_ASCEND_MODE1_MC2_RUNTIME_DIAG_SYNC_ALL_LAYERS:-0}"
export VLLM_ASCEND_MODE1_MC2_RUNTIME_DIAG_SYNC_LOG_DONE="${VLLM_ASCEND_MODE1_MC2_RUNTIME_DIAG_SYNC_LOG_DONE:-0}"
export VLLM_ASCEND_MODE1_STEP_TIMELINE_LOG="${VLLM_ASCEND_MODE1_STEP_TIMELINE_LOG:-1}"
export VLLM_ASCEND_MODE1_RPC_PRE_NPU_SYNC="${VLLM_ASCEND_MODE1_RPC_PRE_NPU_SYNC:-1}"
export VLLM_ASCEND_MODE1_RESTORE_POST_NPU_SYNC="${VLLM_ASCEND_MODE1_RESTORE_POST_NPU_SYNC:-1}"
export VLLM_ASCEND_MODE1_RPC_PRE_BARRIER="${VLLM_ASCEND_MODE1_RPC_PRE_BARRIER:-0}"
export VLLM_ASCEND_MODE1_PAYLOAD_GATHER_TRACE="${VLLM_ASCEND_MODE1_PAYLOAD_GATHER_TRACE:-0}"
export VLLM_ASCEND_MODE1_PAYLOAD_GATHER_TRACE_MODULES="${VLLM_ASCEND_MODE1_PAYLOAD_GATHER_TRACE_MODULES:-8}"
export VLLM_ASCEND_MODE1_PAYLOAD_PLANNING_DIAG="${VLLM_ASCEND_MODE1_PAYLOAD_PLANNING_DIAG:-0}"
export VLLM_ASCEND_MODE1_LOG2PHY_SYNC_LOG="${VLLM_ASCEND_MODE1_LOG2PHY_SYNC_LOG:-0}"
export VLLM_ASCEND_MODE1_VALIDATE_EXPERT_MAPPING="${VLLM_ASCEND_MODE1_VALIDATE_EXPERT_MAPPING:-0}"
export VLLM_ASCEND_MODE1_VALIDATE_EXPERT_MAPPING_LOG="${VLLM_ASCEND_MODE1_VALIDATE_EXPERT_MAPPING_LOG:-0}"
export VLLM_ASCEND_MODE1_WEIGHT_RELOAD_CAPACITY_LOG="${VLLM_ASCEND_MODE1_WEIGHT_RELOAD_CAPACITY_LOG:-0}"
export VLLM_ASCEND_MODE1_FULL_RESTORE_OFFLOAD_STORAGE_DIAG="${VLLM_ASCEND_MODE1_FULL_RESTORE_OFFLOAD_STORAGE_DIAG:-0}"

# Content-corruption diagnostics.  The normal mapping checks only prove that
# expert_map/log2phy have valid shapes and slot ranges.  For floor2 we also need
# to prove that the active execution slots contain the expert weights implied by
# those maps; otherwise generation can collapse into repeated punctuation while
# all metadata still looks valid.
export VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_LOG="${VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_LOG:-0}"
export VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_REASONS="${VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_REASONS:-pre_generate,execute_single_wave}"
export VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_LAYERS="${VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_LAYERS:-0}"
export VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_EXPERTS="${VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_EXPERTS:-8}"
export VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_VALUES="${VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_VALUES:-16}"
export VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_DUMP="${VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_DUMP:-0}"
export VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_LAYERS="${VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_LAYERS:-0,1}"
export VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_MAX_LAYERS="${VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_MAX_LAYERS:-2}"
export VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_EXPERTS="${VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_EXPERTS:-8}"
export VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_VALUES="${VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_VALUES:-8}"
export VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_STRICT="${VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_STRICT:-1}"
export VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG="${VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG:-0}"
export VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG_LAYERS="${VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG_LAYERS:-0}"
export VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG_VALUES="${VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG_VALUES:-8}"
export VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG="${VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG:-0}"
export VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_LAYERS="${VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_LAYERS:-0}"
export VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_EP_RANKS="${VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_EP_RANKS:-0}"
export VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_EXPERTS="${VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_EXPERTS:-0,1,2,3,4,5,6,7}"
export VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_SHARDS="${VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_SHARDS:-w1,w2,w3}"
export VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_VALUES="${VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_VALUES:-4}"
export VLLM_ASCEND_MODE1_UPDATE_WEIGHTS_DIAG="${VLLM_ASCEND_MODE1_UPDATE_WEIGHTS_DIAG:-0}"
export VLLM_ASCEND_MODE1_UPDATE_WEIGHTS_SHARD_COUNTS="${VLLM_ASCEND_MODE1_UPDATE_WEIGHTS_SHARD_COUNTS:-1}"
export VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG="${VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG:-0}"
export VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG_LAYERS="${VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG_LAYERS:-0}"
export VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG_VALUES="${VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG_VALUES:-8}"
export VLLM_ASCEND_MODE1_EXECUTE_TOPK_DIAG="${VLLM_ASCEND_MODE1_EXECUTE_TOPK_DIAG:-0}"
export VLLM_ASCEND_MODE1_EXECUTE_SHAPE_LOG="${VLLM_ASCEND_MODE1_EXECUTE_SHAPE_LOG:-0}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_VERIFY_LOG="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_VERIFY_LOG:-0}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_VERIFY_VALUES="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_VERIFY_VALUES:-8}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_POSTCHECK_LOG="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_POSTCHECK_LOG:-0}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_POSTCHECK_EXPERTS="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_POSTCHECK_EXPERTS:-16}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_ROW_TRACE_LOG="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_ROW_TRACE_LOG:-0}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_ROW_TRACE_LAYERS="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_ROW_TRACE_LAYERS:-0}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_ROW_TRACE_ACTIVE_RANK_LIMIT="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_ROW_TRACE_ACTIVE_RANK_LIMIT:-8}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_ROW_TRACE_ROWS="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_ROW_TRACE_ROWS:-8}"
export VLLM_ASCEND_MODE1_SAFE_CPU_EXPORT="${VLLM_ASCEND_MODE1_SAFE_CPU_EXPORT:-0}"
export VLLM_ASCEND_MODE1_DISABLE_DIRECT_NPU_IMPORT="${VLLM_ASCEND_MODE1_DISABLE_DIRECT_NPU_IMPORT:-0}"
export VLLM_ASCEND_MODE1_ALLOW_DIRECT_SOURCE_RANGE_IMPORT="${VLLM_ASCEND_MODE1_ALLOW_DIRECT_SOURCE_RANGE_IMPORT:-1}"
export VLLM_ASCEND_MODE1_ALLOW_CONTIGUOUS_P2P_ALIAS_EXPORT="${VLLM_ASCEND_MODE1_ALLOW_CONTIGUOUS_P2P_ALIAS_EXPORT:-1}"
export VLLM_ASCEND_MODE1_DIAG_DURING_PROFILE="${VLLM_ASCEND_MODE1_DIAG_DURING_PROFILE:-0}"
export VLLM_ASCEND_CUSTOM_MODE1_KV_DIAG="${VLLM_ASCEND_CUSTOM_MODE1_KV_DIAG:-0}"
export VLLM_ASCEND_MODE1_KV_ALLOC_TRACE="${VLLM_ASCEND_MODE1_KV_ALLOC_TRACE:-0}"
export VLLM_ASCEND_MODE1_ENGINE_KV_INIT_DIAG="${VLLM_ASCEND_MODE1_ENGINE_KV_INIT_DIAG:-0}"

export TRAINER_SAVE_FREQ=-1
export SAVE_CKPT_ENABLE=0

echo "[floor2->floor4 kv probe] baseline=$BASELINE_EPOCH0"
echo "[floor2->floor4 kv probe] run_name=$DYNAMIC_RUN_NAME floors=$DYNAMIC_FORCE_SELECTED_FLOORS caps=$FLOOR_KV_CAPS"
echo "[floor2->floor4 kv probe] preserve_same_floor_kv=$VLLM_ASCEND_MODE1_PRESERVE_KV_ON_SAME_FLOOR_NEXT_STEP"
echo "[floor2->floor4 kv probe] stage_weights_before_kv_rebuild=$VLLM_ASCEND_MODE1_STAGE_WEIGHTS_BEFORE_KV_REBUILD"
echo "[floor2->floor4 kv probe] skip_pre_weight_kv_resume=$VLLM_ASCEND_MODE1_SKIP_PRE_WEIGHT_KV_RESUME"
echo "[floor2->floor4 kv probe] bootstrap_kv_before_weight_onload=$VLLM_ASCEND_MODE1_BOOTSTRAP_KV_BEFORE_WEIGHT_ONLOAD bootstrap_kv_tokens=$VLLM_ASCEND_MODE1_BOOTSTRAP_KV_TOKENS"
echo "[floor2->floor4 kv probe] cold_init_kv_tokens=$VLLM_ASCEND_MODE1_COLD_INIT_KV_TOKENS use_cold_init_kv_cap=$VLLM_ASCEND_MODE1_USE_COLD_INIT_KV_CAP"
echo "[floor2->floor4 kv probe] profile_max_tokens=$VLLM_ASCEND_MODE1_PROFILE_MAX_TOKENS avoid_mc2_boundary=$VLLM_ASCEND_MODE1_PROFILE_AVOID_MC2_BOUNDARY avoid_tokens=$VLLM_ASCEND_MODE1_PROFILE_MC2_AVOID_TOKENS extra_mc2_profile=$VLLM_ASCEND_MODE1_PROFILE_EXTRA_MC2_DUMMY mc2_profile_tokens=$VLLM_ASCEND_MODE1_PROFILE_MC2_DUMMY_TOKENS explicit_kv_cap_for_init=$VLLM_ASCEND_MODE1_USE_EXPLICIT_KV_CAP_FOR_INIT"
echo "[floor2->floor4 kv probe] memory_profile_log=$VLLM_ASCEND_FULL_REDUNDANCY_EXPERIMENT_LOG"
echo "[floor2->floor4 kv probe] runtime_caps_by_step=$DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP"
echo "[floor2->floor4 kv probe] weight_fingerprint_log=$VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_LOG reasons=$VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_REASONS layers=$VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_LAYERS experts=$VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_EXPERTS values=$VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_VALUES"
echo "[floor2->floor4 kv probe] pre_generate_state_dump=$VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_DUMP layers=$VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_LAYERS experts=$VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_EXPERTS values=$VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_VALUES"
echo "[floor2->floor4 kv probe] process_weight_diag=$VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG layers=$VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG_LAYERS update_weights_diag=$VLLM_ASCEND_MODE1_UPDATE_WEIGHTS_DIAG shard_counts=$VLLM_ASCEND_MODE1_UPDATE_WEIGHTS_SHARD_COUNTS reload_chain_diag=$VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG reload_layers=$VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG_LAYERS"
echo "[floor2->floor4 kv probe] weight_loader_diag=$VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG layers=$VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_LAYERS ep_ranks=$VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_EP_RANKS experts=$VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_EXPERTS shards=$VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_SHARDS values=$VLLM_ASCEND_MODE1_WEIGHT_LOADER_DIAG_VALUES"
echo "[floor2->floor4 kv probe] execute_shape_log=$VLLM_ASCEND_MODE1_EXECUTE_SHAPE_LOG execute_topk_diag=$VLLM_ASCEND_MODE1_EXECUTE_TOPK_DIAG"
echo "[floor2->floor4 kv probe] direct_npu_import_verify=$VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_VERIFY_LOG postcheck=$VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_POSTCHECK_LOG postcheck_experts=$VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_POSTCHECK_EXPERTS safe_cpu_export=$VLLM_ASCEND_MODE1_SAFE_CPU_EXPORT disable_direct_npu_import=$VLLM_ASCEND_MODE1_DISABLE_DIRECT_NPU_IMPORT allow_direct_source_range_import=$VLLM_ASCEND_MODE1_ALLOW_DIRECT_SOURCE_RANGE_IMPORT allow_contiguous_p2p_alias_export=$VLLM_ASCEND_MODE1_ALLOW_CONTIGUOUS_P2P_ALIAS_EXPORT"
echo "[floor2->floor4 kv probe] direct_npu_row_trace=$VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_ROW_TRACE_LOG layers=$VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_ROW_TRACE_LAYERS active_rank_limit=$VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_ROW_TRACE_ACTIVE_RANK_LIMIT rows=$VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_ROW_TRACE_ROWS"
echo "[floor2->floor4 kv probe] diag_during_profile=$VLLM_ASCEND_MODE1_DIAG_DURING_PROFILE"
echo "[floor2->floor4 kv probe] custom_mode1_kv_diag=$VLLM_ASCEND_CUSTOM_MODE1_KV_DIAG kv_alloc_trace=$VLLM_ASCEND_MODE1_KV_ALLOC_TRACE engine_kv_init_diag=$VLLM_ASCEND_MODE1_ENGINE_KV_INIT_DIAG"

exec "$SCRIPT_DIR/run_mode1_dynamic_length_aware_adaptive_floor4_epochs.sh" "$@"
