#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$SCRIPT_DIR"

timestamp=$(date -u +%Y%m%dT%H%M%SZ)

export DEEPSEEK_ACTOR_PROBE_RUN_NAME=${DEEPSEEK_WEIGHT_SYNC_SMOKE_RUN_NAME:-weight_sync_smoke_$timestamp}
export DEEPSEEK_ACTOR_PROBE_TRAINING_STEPS=1
export DEEPSEEK_ACTOR_PROBE_TRAIN_BATCH_SIZE=32
export DEEPSEEK_ACTOR_PROBE_MAX_PROMPT_LENGTH=1024
export DEEPSEEK_ACTOR_PROBE_MAX_RESPONSE_LENGTH=32
export DEEPSEEK_ACTOR_PROBE_ROLLOUT_N=1
export DEEPSEEK_ACTOR_PROBE_MAX_NUM_BATCHED_TOKENS=1056
export DEEPSEEK_ACTOR_PROBE_MAX_NUM_SEQS=32
export DEEPSEEK_ACTOR_PROBE_KV_TOKENS_PER_RANK=16384
export DEEPSEEK_ACTOR_PROBE_REQUIRE_SEMANTIC_OUTPUT=${DEEPSEEK_ACTOR_PROBE_REQUIRE_SEMANTIC_OUTPUT:-1}

exec "$SCRIPT_DIR/run_deepseek_v2_lite_actor_update_probe.sh" "$@"
