#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$SCRIPT_DIR"

env -u VERL_ELASTIC_TAIL_VALIDATE_LEVEL_TOKENS \
    -u MAX_RESPONSE_LENGTH \
    -u MAX_RESPONSE_LEN \
    -u ROLLOUT_MAX_NUM_BATCHED_TOKENS \
DYNAMIC_RUN_NAME="${DYNAMIC_RUN_NAME:-mode1_dynamic_length_aware_adaptive_floor4_natural_tailguard_full3}" \
DYNAMIC_TOTAL_EPOCHS="${DYNAMIC_TOTAL_EPOCHS:-3}" \
DYNAMIC_SHRINK_POLICY=natural \
DYNAMIC_PLAN_STEPS="${DYNAMIC_PLAN_STEPS:-5}" \
DYNAMIC_TRAIN_STEPS="${DYNAMIC_TRAIN_STEPS:-5}" \
DYNAMIC_ENABLE_THRESHOLD_CONTROL=0 \
DYNAMIC_SHORT_STEP_CAP_ENABLE="${DYNAMIC_SHORT_STEP_CAP_ENABLE:-1}" \
DYNAMIC_SHORT_STEP_EXIT_THRESHOLD="${DYNAMIC_SHORT_STEP_EXIT_THRESHOLD:-4096}" \
DYNAMIC_SHORT_STEP_CAP_TOKENS="${DYNAMIC_SHORT_STEP_CAP_TOKENS:-4096}" \
DYNAMIC_SHORT_STEP_CAP_FLOORS="${DYNAMIC_SHORT_STEP_CAP_FLOORS:-4}" \
DYNAMIC_TAIL_GUARD_RATIO_QUANTILE="${DYNAMIC_TAIL_GUARD_RATIO_QUANTILE:-0.95}" \
DYNAMIC_TAIL_GUARD_RATIO_WINDOW="${DYNAMIC_TAIL_GUARD_RATIO_WINDOW:-3}" \
DYNAMIC_TAIL_GUARD_DEFAULT_RATIO="${DYNAMIC_TAIL_GUARD_DEFAULT_RATIO:-1.20}" \
DYNAMIC_TAIL_GUARD_MIN_CAP="${DYNAMIC_TAIL_GUARD_MIN_CAP:-4096}" \
DYNAMIC_TAIL_GUARD_ROUND_TO="${DYNAMIC_TAIL_GUARD_ROUND_TO:-512}" \
DYNAMIC_IGNORE_TAIL_TIES_AT_RESPONSE_CAP=0 \
DYNAMIC_RESET_PROGRESS_AFTER_RESUME=1 \
TRAINER_SAVE_FREQ="${TRAINER_SAVE_FREQ:-5}" \
MAX_ACTOR_CKPT_TO_KEEP="${MAX_ACTOR_CKPT_TO_KEEP:-1}" \
./run_mode1_dynamic_length_aware_adaptive_floor4_epochs.sh "$@"
