#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
RUN_TAG=${SIDECAR_RUN_TAG:-"$(date -u +%Y%m%dT%H%M%SZ)"}

export FAIR_OUTPUT_ROOT=${FAIR_OUTPUT_ROOT:-"/data/adafloor_sidecar_runs/${RUN_TAG}"}
export DYNAMIC_RUN_NAME=${DYNAMIC_RUN_NAME:-"adafloor_natural_floor2_qwen3_8b_sidecar"}
export VERL_SIDECAR_ENABLE=1
export VERL_SIDECAR_MODEL_PATH=${VERL_SIDECAR_MODEL_PATH:-/data/Qwen3-8B}
export VERL_SIDECAR_PROMPTS_FILE=${VERL_SIDECAR_PROMPTS_FILE:-/data/gsm8k}
export VERL_SIDECAR_DATA_SPLIT=${VERL_SIDECAR_DATA_SPLIT:-train}
export VERL_SIDECAR_PARALLEL_MODE=${VERL_SIDECAR_PARALLEL_MODE:-hybrid}
export VERL_SIDECAR_TENSOR_PARALLEL_SIZE=${VERL_SIDECAR_TENSOR_PARALLEL_SIZE:-8}
export VERL_SIDECAR_REPLICA_COUNT=${VERL_SIDECAR_REPLICA_COUNT:-1}
export VERL_SIDECAR_ENABLE_EXPERT_PARALLEL=${VERL_SIDECAR_ENABLE_EXPERT_PARALLEL:-0}
export VERL_SIDECAR_EXPECTED_ACTIVE_RANKS=${VERL_SIDECAR_EXPECTED_ACTIVE_RANKS:-8}
export VERL_SIDECAR_GPU_MEMORY_UTILIZATION=${VERL_SIDECAR_GPU_MEMORY_UTILIZATION:-0.90}
export VERL_SIDECAR_MAX_MODEL_LEN=${VERL_SIDECAR_MAX_MODEL_LEN:-6144}
export VERL_SIDECAR_MAX_TOKENS=${VERL_SIDECAR_MAX_TOKENS:-4096}
export VERL_SIDECAR_MAX_NUM_SEQS=${VERL_SIDECAR_MAX_NUM_SEQS:-278}
export VERL_SIDECAR_MAX_NUM_BATCHED_TOKENS=${VERL_SIDECAR_MAX_NUM_BATCHED_TOKENS:-65536}
export VERL_SIDECAR_MAX_PROMPTS_PER_REPLICA=${VERL_SIDECAR_MAX_PROMPTS_PER_REPLICA:-556}
export VERL_SIDECAR_GENERATE_CHUNK_SIZE=${VERL_SIDECAR_GENERATE_CHUNK_SIZE:-556}
export VERL_SIDECAR_REPEAT_UNTIL_KILLED=${VERL_SIDECAR_REPEAT_UNTIL_KILLED:-1}
export VERL_SIDECAR_STREAM_CHECKPOINT=${VERL_SIDECAR_STREAM_CHECKPOINT:-1}

[[ -f "${VERL_SIDECAR_MODEL_PATH}/config.json" ]] || {
    echo "missing sidecar model at ${VERL_SIDECAR_MODEL_PATH}" >&2
    exit 2
}
[[ -e "${VERL_SIDECAR_PROMPTS_FILE}" ]] || {
    echo "missing sidecar prompts at ${VERL_SIDECAR_PROMPTS_FILE}" >&2
    exit 2
}

if [[ "${SIDECAR_DRY_RUN:-0}" == "1" ]]; then
    export FAIR_DRY_RUN=1
fi

exec "${ROOT_DIR}/run_paper_fair_epoch1_2_from_common_epoch0.sh" adafloor_n_f2 "$@"
