#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Full-length dynamic natural-policy validation with floor2 enabled.
#
# This reuses the existing mode0 probe from the floor4 natural tailguard run for
# length history, so it only executes two mode1 epochs: epoch_001 and epoch_002.
# If DYNAMIC_INITIAL_RESUME_CKPT is not provided, epoch_001 starts from the base
# model and epoch_002 resumes from epoch_001.  The floor2 cap is the largest
# no-trim value verified by the threshold-controlled floor2 sweep.

BASELINE_EPOCH0="${DYNAMIC_INITIAL_BASELINE_DIR:-$SCRIPT_DIR/mode1_dynamic_length_aware_adaptive_floor4_natural_tailguard_full3/epoch_000_mode0_probe}"
DYNAMIC_DISABLE_TAIL_GUARD="${DYNAMIC_DISABLE_TAIL_GUARD:-0}"
DYNAMIC_SHORT_STEP_CAP_ENABLE="${DYNAMIC_SHORT_STEP_CAP_ENABLE:-1}"
DYNAMIC_EXPECT_NO_RESPONSE_CAPS="${DYNAMIC_EXPECT_NO_RESPONSE_CAPS:-0}"

if [[ ! -d "$BASELINE_EPOCH0/rollout_data" ]]; then
    echo "missing reusable epoch0 rollout data: $BASELINE_EPOCH0/rollout_data" >&2
    exit 2
fi

export VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY=natural
export VLLM_ASCEND_SHRINK_AWARE_STAGES="${VLLM_ASCEND_SHRINK_AWARE_STAGES:-8,4,2}"
export VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE="${VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE:-2}"
export MIN_ADAPTIVE_FLOOR="${MIN_ADAPTIVE_FLOOR:-2}"
export ACTIVE_PEAK_SAFETY_FACTOR="${ACTIVE_PEAK_SAFETY_FACTOR:-1.16}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2:-131072}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4:-280576}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8:-315648}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS:-380800}"
export VLLM_ASCEND_MODE1_RELOAD_TRIM_ALLOCATOR="${VLLM_ASCEND_MODE1_RELOAD_TRIM_ALLOCATOR:-0}"
export VLLM_ASCEND_MODE1_RELOAD_SYNC_ON_TRIM="${VLLM_ASCEND_MODE1_RELOAD_SYNC_ON_TRIM:-0}"
export VLLM_ASCEND_FULL_REDUNDANCY_EXPERIMENT_LOG="${VLLM_ASCEND_FULL_REDUNDANCY_EXPERIMENT_LOG:-0}"
export VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC="${VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC:-1}"
export VLLM_ASCEND_MODE1_REFRESH_GROUPS_ON_KV_RESIZE="${VLLM_ASCEND_MODE1_REFRESH_GROUPS_ON_KV_RESIZE:-1}"
export VLLM_ASCEND_MODE1_FULLWORLD_REFRESH_MC2_WARMUP="${VLLM_ASCEND_MODE1_FULLWORLD_REFRESH_MC2_WARMUP:-1}"
export VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_MC2_WARMUP="${VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_MC2_WARMUP:-1}"
export VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_MC2_WARMUP_TOKENS="${VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_MC2_WARMUP_TOKENS:-32}"
export VLLM_ASCEND_MODE1_PARITY_MC2_WARMUP_ROUTE="${VLLM_ASCEND_MODE1_PARITY_MC2_WARMUP_ROUTE:-global}"
export VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG="${VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG:-0}"
export VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG_LIMIT="${VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG_LIMIT:-40}"
export VLLM_ASCEND_MODE1_FULLWORLD_RESTORE_DIAG="${VLLM_ASCEND_MODE1_FULLWORLD_RESTORE_DIAG:-0}"
export VLLM_ASCEND_MODE1_STEP_TIMELINE_LOG="${VLLM_ASCEND_MODE1_STEP_TIMELINE_LOG:-0}"
export VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG="${VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG:-0}"
export VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG_ALL="${VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG_ALL:-0}"
export VLLM_ASCEND_MODE1_CLEAR_STALE_PARAM_DICTS_AFTER_OLD_KV="${VLLM_ASCEND_MODE1_CLEAR_STALE_PARAM_DICTS_AFTER_OLD_KV:-1}"
export VLLM_ASCEND_MODE1_PRESERVE_KV_ON_SAME_FLOOR_NEXT_STEP=0
export VLLM_ASCEND_MODE1_STAGE_WEIGHTS_BEFORE_KV_REBUILD="${VLLM_ASCEND_MODE1_STAGE_WEIGHTS_BEFORE_KV_REBUILD:-1}"
export VLLM_ASCEND_MODE1_BOOTSTRAP_KV_BEFORE_WEIGHT_ONLOAD="${VLLM_ASCEND_MODE1_BOOTSTRAP_KV_BEFORE_WEIGHT_ONLOAD:-1}"
export VLLM_ASCEND_MODE1_BOOTSTRAP_KV_TOKENS="${VLLM_ASCEND_MODE1_BOOTSTRAP_KV_TOKENS:-${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2}}"
export VLLM_ASCEND_MODE1_COLD_INIT_KV_TOKENS="${VLLM_ASCEND_MODE1_COLD_INIT_KV_TOKENS:-2048}"
export VLLM_ASCEND_MODE1_USE_COLD_INIT_KV_CAP="${VLLM_ASCEND_MODE1_USE_COLD_INIT_KV_CAP:-1}"
export VLLM_ASCEND_MODE1_PROFILE_EXTRA_MC2_DUMMY="${VLLM_ASCEND_MODE1_PROFILE_EXTRA_MC2_DUMMY:-0}"
export VLLM_ASCEND_MODE1_PROFILE_MC2_DUMMY_TOKENS="${VLLM_ASCEND_MODE1_PROFILE_MC2_DUMMY_TOKENS:-128}"
export VLLM_ASCEND_MODE1_PROFILE_MAX_TOKENS="${VLLM_ASCEND_MODE1_PROFILE_MAX_TOKENS:-2048}"
export VLLM_ASCEND_MODE1_PROFILE_AVOID_MC2_BOUNDARY="${VLLM_ASCEND_MODE1_PROFILE_AVOID_MC2_BOUNDARY:-1}"
export VLLM_ASCEND_MODE1_PROFILE_MC2_AVOID_TOKENS="${VLLM_ASCEND_MODE1_PROFILE_MC2_AVOID_TOKENS:-640}"
export VLLM_ASCEND_MODE1_USE_EXPLICIT_KV_CAP_FOR_INIT="${VLLM_ASCEND_MODE1_USE_EXPLICIT_KV_CAP_FOR_INIT:-0}"
export FLOOR_KV_CAPS="${FLOOR_KV_CAPS:-2:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2},4:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4},8:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8},16:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS}}"

# Upward transitions such as floor2->floor4 release old KV before floor prepare,
# then compact MoE state.  Avoid repeated allocator trims inside that compact
# loop; the later resize memory query still performs one trim/sync before
# allocating the new KV cache.
export VLLM_ASCEND_MODE1_CLEAR_OLD_KV_BEFORE_UPWARD_FLOOR_PREPARE="${VLLM_ASCEND_MODE1_CLEAR_OLD_KV_BEFORE_UPWARD_FLOOR_PREPARE:-1}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_BEFORE_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_EMPTY_CACHE_BEFORE_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_DURING_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_EMPTY_CACHE_DURING_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_AFTER_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_EMPTY_CACHE_AFTER_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_BETWEEN_COMPACT_TENSORS="${VLLM_ASCEND_MODE1_EMPTY_CACHE_BETWEEN_COMPACT_TENSORS:-0}"
export VLLM_ASCEND_MODE1_UPWARD_CLEANUP_FINAL_EMPTY_CACHE="${VLLM_ASCEND_MODE1_UPWARD_CLEANUP_FINAL_EMPTY_CACHE:-0}"
export VLLM_ASCEND_MODE1_UPWARD_COMPACT_RELEASE_EVERY_LAYERS="${VLLM_ASCEND_MODE1_UPWARD_COMPACT_RELEASE_EVERY_LAYERS:-48}"

# Natural should not retain planned floor communicators.  Keep these explicit so
# the floor2 test does not accidentally inherit planner-residency settings.
export VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_COMM_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_DISPATCH_WARMUP=0
export VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE=0

# Lightweight corruption diagnostics.  These only dump layer shape/state and a
# few active-slot samples before generate; they avoid the heavier per-execute
# fingerprint logs unless explicitly enabled by the caller.
export VLLM_ASCEND_MODE1_EXECUTE_SHAPE_LOG="${VLLM_ASCEND_MODE1_EXECUTE_SHAPE_LOG:-0}"
export VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_DUMP="${VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_DUMP:-0}"
export VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_LAYERS="${VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_LAYERS:-0}"
export VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_MAX_LAYERS="${VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_MAX_LAYERS:-1}"
export VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_EXPERTS="${VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_EXPERTS:-8}"
export VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_VALUES="${VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_VALUES:-8}"
export VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_STRICT="${VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_STRICT:-1}"
export VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_LOG="${VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_LOG:-0}"
export VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG="${VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG:-0}"
export VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG_LAYERS="${VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG_LAYERS:-0}"
export VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG_VALUES="${VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG_VALUES:-8}"
export VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG="${VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG:-0}"
export VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG_LAYERS="${VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG_LAYERS:-0}"
export VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG_VALUES="${VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG_VALUES:-8}"
export VLLM_ASCEND_MODE1_DIAG_DURING_PROFILE="${VLLM_ASCEND_MODE1_DIAG_DURING_PROFILE:-0}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_VERIFY_LOG="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_VERIFY_LOG:-0}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_VERIFY_VALUES="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_VERIFY_VALUES:-8}"
export VLLM_ASCEND_MODE1_LOG2PHY_SYNC_LOG="${VLLM_ASCEND_MODE1_LOG2PHY_SYNC_LOG:-0}"
export VLLM_ASCEND_MODE1_VALIDATE_EXPERT_MAPPING="${VLLM_ASCEND_MODE1_VALIDATE_EXPERT_MAPPING:-0}"
export VLLM_ASCEND_MODE1_VALIDATE_EXPERT_MAPPING_LOG="${VLLM_ASCEND_MODE1_VALIDATE_EXPERT_MAPPING_LOG:-0}"
export VLLM_ASCEND_MODE1_WEIGHT_RELOAD_CAPACITY_LOG="${VLLM_ASCEND_MODE1_WEIGHT_RELOAD_CAPACITY_LOG:-0}"
export VLLM_ASCEND_MODE1_FULL_RESTORE_OFFLOAD_STORAGE_DIAG="${VLLM_ASCEND_MODE1_FULL_RESTORE_OFFLOAD_STORAGE_DIAG:-0}"
export VLLM_ASCEND_CUSTOM_MODE1_KV_DIAG="${VLLM_ASCEND_CUSTOM_MODE1_KV_DIAG:-0}"
export VLLM_ASCEND_MODE1_KV_ALLOC_TRACE="${VLLM_ASCEND_MODE1_KV_ALLOC_TRACE:-0}"
export VLLM_ASCEND_MODE1_ENGINE_KV_INIT_DIAG="${VLLM_ASCEND_MODE1_ENGINE_KV_INIT_DIAG:-0}"

echo "[dynamic floor2 natural] reusable_epoch0=$BASELINE_EPOCH0"
echo "[dynamic floor2 natural] initial_resume_ckpt=${DYNAMIC_INITIAL_RESUME_CKPT:-<none>}"
echo "[dynamic floor2 natural] stages=$VLLM_ASCEND_SHRINK_AWARE_STAGES min_floor=$MIN_ADAPTIVE_FLOOR active_peak_safety_factor=$ACTIVE_PEAK_SAFETY_FACTOR floor_caps=$FLOOR_KV_CAPS"
echo "[dynamic floor2 natural] preserve_same_floor_kv=$VLLM_ASCEND_MODE1_PRESERVE_KV_ON_SAME_FLOOR_NEXT_STEP"
echo "[dynamic floor2 natural] stage_weights_before_kv_rebuild=$VLLM_ASCEND_MODE1_STAGE_WEIGHTS_BEFORE_KV_REBUILD"
echo "[dynamic floor2 natural] bootstrap_kv_before_weight_onload=$VLLM_ASCEND_MODE1_BOOTSTRAP_KV_BEFORE_WEIGHT_ONLOAD bootstrap_kv_tokens=$VLLM_ASCEND_MODE1_BOOTSTRAP_KV_TOKENS"
echo "[dynamic floor2 natural] cold_init_kv_tokens=$VLLM_ASCEND_MODE1_COLD_INIT_KV_TOKENS use_cold_init_kv_cap=$VLLM_ASCEND_MODE1_USE_COLD_INIT_KV_CAP"
echo "[dynamic floor2 natural] profile_max_tokens=$VLLM_ASCEND_MODE1_PROFILE_MAX_TOKENS avoid_mc2_boundary=$VLLM_ASCEND_MODE1_PROFILE_AVOID_MC2_BOUNDARY avoid_tokens=$VLLM_ASCEND_MODE1_PROFILE_MC2_AVOID_TOKENS extra_mc2_profile=$VLLM_ASCEND_MODE1_PROFILE_EXTRA_MC2_DUMMY mc2_profile_tokens=$VLLM_ASCEND_MODE1_PROFILE_MC2_DUMMY_TOKENS explicit_kv_cap_for_init=$VLLM_ASCEND_MODE1_USE_EXPLICIT_KV_CAP_FOR_INIT"
echo "[dynamic floor2 natural] memory_profile_log=$VLLM_ASCEND_FULL_REDUNDANCY_EXPERIMENT_LOG"
echo "[dynamic floor2 natural] reload_trim=$VLLM_ASCEND_MODE1_RELOAD_TRIM_ALLOCATOR sync_on_trim=$VLLM_ASCEND_MODE1_RELOAD_SYNC_ON_TRIM"
echo "[dynamic floor2 natural] cpu_dp_metadata_sync=$VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC"
echo "[dynamic floor2 natural] refresh_groups_on_kv_resize=$VLLM_ASCEND_MODE1_REFRESH_GROUPS_ON_KV_RESIZE fullworld_refresh_mc2_warmup=$VLLM_ASCEND_MODE1_FULLWORLD_REFRESH_MC2_WARMUP post_restore_mc2_warmup=$VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_MC2_WARMUP warmup_tokens=$VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_MC2_WARMUP_TOKENS warmup_route=$VLLM_ASCEND_MODE1_PARITY_MC2_WARMUP_ROUTE"
echo "[dynamic floor2 natural] kv_preempt_diag=$VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG limit=$VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG_LIMIT"
echo "[dynamic floor2 natural] clear_stale_param_dicts_after_old_kv=$VLLM_ASCEND_MODE1_CLEAR_STALE_PARAM_DICTS_AFTER_OLD_KV"
echo "[dynamic floor2 natural] upward_cleanup_fastpath=old_kv_before_prepare:$VLLM_ASCEND_MODE1_CLEAR_OLD_KV_BEFORE_UPWARD_FLOOR_PREPARE compact_empty_between:$VLLM_ASCEND_MODE1_EMPTY_CACHE_BETWEEN_COMPACT_TENSORS final_empty:$VLLM_ASCEND_MODE1_UPWARD_CLEANUP_FINAL_EMPTY_CACHE"
echo "[dynamic floor2 natural] execute_shape_log=$VLLM_ASCEND_MODE1_EXECUTE_SHAPE_LOG pre_generate_state_dump=$VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_DUMP layers=$VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_LAYERS experts=$VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_EXPERTS values=$VLLM_ASCEND_MODE1_PRE_GENERATE_STATE_VALUES"
echo "[dynamic floor2 natural] weight_fingerprint_log=$VLLM_ASCEND_MODE1_WEIGHT_FINGERPRINT_LOG diag_during_profile=$VLLM_ASCEND_MODE1_DIAG_DURING_PROFILE direct_npu_import_verify=$VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_VERIFY_LOG"
echo "[dynamic floor2 natural] process_weight_diag=$VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG layers=$VLLM_ASCEND_MODE1_PROCESS_WEIGHT_DIAG_LAYERS reload_chain_diag=$VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG reload_layers=$VLLM_ASCEND_MODE1_RELOAD_CHAIN_DIAG_LAYERS"
echo "[dynamic floor2 natural] custom_mode1_kv_diag=$VLLM_ASCEND_CUSTOM_MODE1_KV_DIAG kv_alloc_trace=$VLLM_ASCEND_MODE1_KV_ALLOC_TRACE engine_kv_init_diag=$VLLM_ASCEND_MODE1_ENGINE_KV_INIT_DIAG"
echo "[dynamic floor2 natural] disable_tail_guard=$DYNAMIC_DISABLE_TAIL_GUARD short_step_cap_enable=$DYNAMIC_SHORT_STEP_CAP_ENABLE expect_no_response_caps=$DYNAMIC_EXPECT_NO_RESPONSE_CAPS"

DYNAMIC_RUN_NAME="${DYNAMIC_RUN_NAME:-mode1_dynamic_length_aware_adaptive_floor2_natural_tailguard_reuse_epoch0_2epoch}" \
DYNAMIC_TOTAL_EPOCHS="${DYNAMIC_TOTAL_EPOCHS:-3}" \
DYNAMIC_START_EPOCH="${DYNAMIC_START_EPOCH:-1}" \
DYNAMIC_SHRINK_POLICY=natural \
DYNAMIC_SKIP_MODE0_PROBE=1 \
DYNAMIC_INITIAL_BASELINE_DIR="$BASELINE_EPOCH0" \
DYNAMIC_ENABLE_CKPT_CHAIN="${DYNAMIC_ENABLE_CKPT_CHAIN:-1}" \
DYNAMIC_PLAN_STEPS="${DYNAMIC_PLAN_STEPS:-5}" \
DYNAMIC_TRAIN_STEPS="${DYNAMIC_TRAIN_STEPS:-5}" \
DYNAMIC_ENABLE_THRESHOLD_CONTROL=0 \
DYNAMIC_DISABLE_TAIL_GUARD="$DYNAMIC_DISABLE_TAIL_GUARD" \
DYNAMIC_EXPECT_NO_RESPONSE_CAPS="$DYNAMIC_EXPECT_NO_RESPONSE_CAPS" \
DYNAMIC_SHORT_STEP_CAP_ENABLE="$DYNAMIC_SHORT_STEP_CAP_ENABLE" \
DYNAMIC_SHORT_STEP_EXIT_THRESHOLD="${DYNAMIC_SHORT_STEP_EXIT_THRESHOLD:-4096}" \
DYNAMIC_SHORT_STEP_CAP_TOKENS="${DYNAMIC_SHORT_STEP_CAP_TOKENS:-4096}" \
DYNAMIC_SHORT_STEP_CAP_FLOORS="${DYNAMIC_SHORT_STEP_CAP_FLOORS:-2,4}" \
DYNAMIC_TAIL_GUARD_RATIO_QUANTILE="${DYNAMIC_TAIL_GUARD_RATIO_QUANTILE:-0.95}" \
DYNAMIC_TAIL_GUARD_RATIO_WINDOW="${DYNAMIC_TAIL_GUARD_RATIO_WINDOW:-3}" \
DYNAMIC_TAIL_GUARD_DEFAULT_RATIO="${DYNAMIC_TAIL_GUARD_DEFAULT_RATIO:-1.20}" \
DYNAMIC_TAIL_GUARD_MIN_CAP="${DYNAMIC_TAIL_GUARD_MIN_CAP:-4096}" \
DYNAMIC_TAIL_GUARD_ROUND_TO="${DYNAMIC_TAIL_GUARD_ROUND_TO:-512}" \
DYNAMIC_IGNORE_TAIL_TIES_AT_RESPONSE_CAP="${DYNAMIC_IGNORE_TAIL_TIES_AT_RESPONSE_CAP:-0}" \
DYNAMIC_RESET_PROGRESS_AFTER_RESUME="${DYNAMIC_RESET_PROGRESS_AFTER_RESUME:-1}" \
"$SCRIPT_DIR/run_mode1_dynamic_length_aware_adaptive_floor4_epochs.sh" "$@"
