#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Fast planned-policy floor=2 feasibility smoke test.
#
# This is the planned-mode counterpart of the natural floor2 threshold smoke
# test.  It keeps generation short, forces selected_floor=2, and keeps planned
# floor communicators/topology residency enabled so the result reflects the
# planned path rather than natural cleanup behavior.

export TRAINER_TOTAL_EPOCHS="${TRAINER_TOTAL_EPOCHS:-1}"
export OUTPUT_SUBDIR="${OUTPUT_SUBDIR:-mode1_length_sorted_e2e_adaptive_floor2_planned_threshold}"
export PLAN_DIR="${PLAN_DIR:-$SCRIPT_DIR/$OUTPUT_SUBDIR/oracle}"

export VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY=planned
export VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE=1
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS=1
export VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS=1
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_COMM_CACHE=1
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_DISPATCH_WARMUP=1
export VLLM_ASCEND_MODE1_PARITY_PREFILL_PLANNED_EXPERT_SLOTS=1
export VLLM_ASCEND_MODE1_PARITY_PREFILL_PLANNED_EXPERT_SLOTS_ON_RESIZE=1
export VLLM_ASCEND_MODE1_STEP_KV_CAP_INCLUDES_PLANNED_HEADROOM="${VLLM_ASCEND_MODE1_STEP_KV_CAP_INCLUDES_PLANNED_HEADROOM:-0}"
export VLLM_ASCEND_MODE1_PARITY_FORCE_DESTROY_PLANNED_PRUNE=1
export VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY=1
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_PRE_REBUILD=1
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_STASH=1
export VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC=1
export VLLM_ASCEND_MODE1_RELOAD_TRIM_ALLOCATOR=0
export VLLM_ASCEND_MODE1_RELOAD_SYNC_ON_TRIM=0

# Keep the Ascend platform plugin enabled while skipping unrelated entry-point
# plugins that only add noisy non-fatal ERROR logs.
export VLLM_PLUGINS="${VLLM_PLUGINS:-ascend}"

export VERL_ELASTIC_TAIL_VALIDATE_LEVEL_TOKENS="${VERL_ELASTIC_TAIL_VALIDATE_LEVEL_TOKENS:-256,512,640,768,896}"
export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-1024}"
export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-896}"
export MAX_RESPONSE_LEN="${MAX_RESPONSE_LEN:-896}"
export ROLLOUT_MAX_NUM_SEQS="${ROLLOUT_MAX_NUM_SEQS:-32}"
export ROLLOUT_MAX_NUM_BATCHED_TOKENS="${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-$((MAX_PROMPT_LENGTH + MAX_RESPONSE_LENGTH))}"

export VLLM_ASCEND_SHRINK_AWARE_STAGES=8,4,2
export VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE=2
export MIN_ADAPTIVE_FLOOR=2
export FORCE_SELECTED_FLOOR="${FORCE_SELECTED_FLOOR:-2}"
export ACTIVE_PEAK_SAFETY_FACTOR="${ACTIVE_PEAK_SAFETY_FACTOR:-1.16}"

if [[ "${VLLM_ASCEND_MODE1_AUTO_KV_SIZE_HEADROOM_ONLY:-0}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
    # Runtime KV sizing should come from vLLM's measured available memory.
    # Keep planner constraints separate via FLOOR_KV_CAPS so the smoke test
    # still uses the intended small-threshold prompt/rank plan.
    export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS:-0}"
    export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2:-0}"
    export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4:-0}"
    export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8:-0}"
else
    export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS:-377344}"
    export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2:-147456}"
    export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4:-280576}"
    export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8:-377344}"
fi
PLANNER_KV_CAP_FLOOR2="${PLANNER_KV_CAP_FLOOR2:-147456}"
PLANNER_KV_CAP_FLOOR4="${PLANNER_KV_CAP_FLOOR4:-280576}"
PLANNER_KV_CAP_FLOOR8="${PLANNER_KV_CAP_FLOOR8:-377344}"
PLANNER_KV_CAP_FLOOR16="${PLANNER_KV_CAP_FLOOR16:-377344}"
export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS:-0}"
export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2:-$VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS}"
export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4:-147456}"
export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8:-114688}"
export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16:-0}"

runtime_effective_floor2_cap=$(( VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2 > VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2 ? VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2 - VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2 : 0 ))
runtime_effective_floor4_cap=$(( VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4 > VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4 ? VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4 - VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4 : 0 ))
runtime_effective_floor8_cap=$(( VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8 > VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8 ? VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8 - VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8 : 0 ))
runtime_effective_floor16_cap=$(( VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS > VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16 ? VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS - VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16 : 0 ))
export FLOOR_KV_CAPS="${FLOOR_KV_CAPS:-2:${PLANNER_KV_CAP_FLOOR2},4:${PLANNER_KV_CAP_FLOOR4},8:${PLANNER_KV_CAP_FLOOR8},16:${PLANNER_KV_CAP_FLOOR16}}"
export MAX_RANK_PEAK_TOKENS="${MAX_RANK_PEAK_TOKENS:-$PLANNER_KV_CAP_FLOOR16}"

printf '[mode1 floor2 planned threshold] output=%s levels=%s max_response=%s\n' \
    "$OUTPUT_SUBDIR" "$VERL_ELASTIC_TAIL_VALIDATE_LEVEL_TOKENS" "$MAX_RESPONSE_LENGTH"
printf '[mode1 floor2 planned threshold] planner_floor_kv_caps=%s nominal_kv_caps=2:%s,4:%s,8:%s,16:%s\n' \
    "$FLOOR_KV_CAPS" \
    "$VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2" \
    "$VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4" \
    "$VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8" \
    "$VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS"
printf '[mode1 floor2 planned threshold] planned_headroom_by_floor=2:%s,4:%s,8:%s,16:%s includes_headroom=%s\n' \
    "$VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2" \
    "$VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4" \
    "$VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8" \
    "$VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16" \
    "$VLLM_ASCEND_MODE1_STEP_KV_CAP_INCLUDES_PLANNED_HEADROOM"
printf '[mode1 floor2 planned threshold] auto_kv_size_headroom_only=%s\n' \
    "${VLLM_ASCEND_MODE1_AUTO_KV_SIZE_HEADROOM_ONLY:-0}"
printf '[mode1 floor2 planned threshold] runtime_effective_kv_after_headroom=2:%s,4:%s,8:%s,16:%s\n' \
    "$runtime_effective_floor2_cap" \
    "$runtime_effective_floor4_cap" \
    "$runtime_effective_floor8_cap" \
    "$runtime_effective_floor16_cap"
printf '[mode1 floor2 planned threshold] policy=%s fixed_reuse=%s precreate=%s prefill_slots=%s cpu_dp_meta=%s\n' \
    "$VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY" \
    "$VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE" \
    "$VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS" \
    "$VLLM_ASCEND_MODE1_PARITY_PREFILL_PLANNED_EXPERT_SLOTS" \
    "$VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC"

exec "$SCRIPT_DIR/run_mode1_local_length_sorted_e2e_adaptive_floor2.sh" "$@"
