#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
RUN_STAMP="${RUN_STAMP:-$(date -u +%Y%m%dT%H%M%SZ)}"

BASELINE_EPOCH0="${DYNAMIC_INITIAL_BASELINE_DIR:-$SCRIPT_DIR/mode1_dynamic_length_aware_adaptive_floor4_natural_tailguard_full3/epoch_000_mode0_probe}"
if [[ ! -d "$BASELINE_EPOCH0/rollout_data" ]]; then
    echo "missing reusable epoch0 rollout data: $BASELINE_EPOCH0/rollout_data" >&2
    exit 2
fi

# Minimal control for the floor2-history probe:
#   treatment: 2,2,4,4,16
#   control:   4,4,4,4,16
# Steps 1-4 stay short; step5 keeps the full 16k decode length so preemption
# pressure and KV block availability are comparable to the full epoch1 tail.
export DYNAMIC_RUN_NAME="${DYNAMIC_RUN_NAME:-mode1_dynamic_floor4_to_floor16_kv_diag_5step_step5full_${RUN_STAMP}}"
export DYNAMIC_TOTAL_EPOCHS=2
export DYNAMIC_START_EPOCH=1
export DYNAMIC_SKIP_MODE0_PROBE=1
export DYNAMIC_INITIAL_BASELINE_DIR="$BASELINE_EPOCH0"
export DYNAMIC_ENABLE_CKPT_CHAIN=0
export DYNAMIC_SHRINK_POLICY=natural
export DYNAMIC_PLAN_STEPS="${DYNAMIC_PLAN_STEPS:-5}"
export DYNAMIC_TRAIN_STEPS="${DYNAMIC_TRAIN_STEPS:-5}"
export DYNAMIC_DATASET_FRACTION="${DYNAMIC_DATASET_FRACTION:-0.005}"
export DYNAMIC_FORCE_SELECTED_FLOORS="${DYNAMIC_FORCE_SELECTED_FLOORS:-4,4,4,4,16}"

export VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY=natural
export VLLM_ASCEND_SHRINK_AWARE_STAGES="${VLLM_ASCEND_SHRINK_AWARE_STAGES:-8,4}"
export VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE="${VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE:-4}"
export MIN_ADAPTIVE_FLOOR="${MIN_ADAPTIVE_FLOOR:-4}"

export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4:-280576}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8:-315648}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR16="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR16:-380800}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS:-$VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR16}"
export FLOOR_KV_CAPS="${FLOOR_KV_CAPS:-4:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4},8:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8},16:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR16}}"

export DYNAMIC_ENABLE_THRESHOLD_CONTROL=0
export DYNAMIC_SHORT_STEP_CAP_ENABLE=0
export DYNAMIC_TAIL_GUARD_MIN_CAP="${DYNAMIC_TAIL_GUARD_MIN_CAP:-1024}"
export DYNAMIC_TAIL_GUARD_ROUND_TO="${DYNAMIC_TAIL_GUARD_ROUND_TO:-64}"
export DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP="${DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP:-8,16,32,64,64;8,16,32,64,64;8,16,32,64,64;8,16,32,64,64;16384,16384,16384,16384,16384}"
export DYNAMIC_FULL_MAX_RESPONSE_LENGTH="${DYNAMIC_FULL_MAX_RESPONSE_LENGTH:-16384}"
export DYNAMIC_FULL_MAX_RESPONSE_LEN="${DYNAMIC_FULL_MAX_RESPONSE_LEN:-16384}"
export DYNAMIC_FULL_MAX_NUM_BATCHED_TOKENS="${DYNAMIC_FULL_MAX_NUM_BATCHED_TOKENS:-17408}"
export DYNAMIC_FULL_MAX_PROMPT_LENGTH="${DYNAMIC_FULL_MAX_PROMPT_LENGTH:-1024}"

export VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC="${VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC:-1}"
export VLLM_ASCEND_MODE1_REFRESH_GROUPS_ON_KV_RESIZE="${VLLM_ASCEND_MODE1_REFRESH_GROUPS_ON_KV_RESIZE:-1}"
export VLLM_ASCEND_MODE1_FULLWORLD_REFRESH_MC2_WARMUP="${VLLM_ASCEND_MODE1_FULLWORLD_REFRESH_MC2_WARMUP:-1}"
export VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_MC2_WARMUP="${VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_MC2_WARMUP:-1}"
export VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_MC2_WARMUP_TOKENS="${VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_MC2_WARMUP_TOKENS:-32}"
export VLLM_ASCEND_MODE1_PARITY_MC2_WARMUP_ROUTE="${VLLM_ASCEND_MODE1_PARITY_MC2_WARMUP_ROUTE:-global}"
export VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG="${VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG:-1}"
export VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG_LIMIT="${VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG_LIMIT:-40}"

export VLLM_ASCEND_MODE1_RELOAD_TRIM_ALLOCATOR="${VLLM_ASCEND_MODE1_RELOAD_TRIM_ALLOCATOR:-0}"
export VLLM_ASCEND_MODE1_RELOAD_SYNC_ON_TRIM="${VLLM_ASCEND_MODE1_RELOAD_SYNC_ON_TRIM:-0}"
export VLLM_ASCEND_FULL_REDUNDANCY_EXPERIMENT_LOG="${VLLM_ASCEND_FULL_REDUNDANCY_EXPERIMENT_LOG:-0}"
export VLLM_ASCEND_MODE1_STEP_TIMELINE_LOG="${VLLM_ASCEND_MODE1_STEP_TIMELINE_LOG:-1}"
export VLLM_ASCEND_MODE1_PRESERVE_KV_ON_SAME_FLOOR_NEXT_STEP=0

export TRAINER_SAVE_FREQ=-1
export SAVE_CKPT_ENABLE=0

echo "[floor4->floor16 kv diag 5step step5full] baseline=$BASELINE_EPOCH0"
echo "[floor4->floor16 kv diag 5step step5full] run_name=$DYNAMIC_RUN_NAME floors=$DYNAMIC_FORCE_SELECTED_FLOORS caps=$FLOOR_KV_CAPS"
echo "[floor4->floor16 kv diag 5step step5full] runtime_caps_by_step=$DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP"
echo "[floor4->floor16 kv diag 5step step5full] kv_preempt_diag=$VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG limit=$VLLM_ASCEND_MODE1_KV_PREEMPT_DIAG_LIMIT"

exec "$SCRIPT_DIR/run_mode1_dynamic_length_aware_adaptive_floor4_epochs.sh" "$@"
