#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
timestamp=$(date -u +%Y%m%dT%H%M%SZ)

export DEEPSEEK_ADAFLOOR_SMOKE_FLOOR=2
export DEEPSEEK_ADAFLOOR_SMOKE_RUN_NAME="${DEEPSEEK_ADAFLOOR_SMOKE_RUN_NAME:-adafloor_ep16_floor2_threshold_2step_$timestamp}"
export DEEPSEEK_ADAFLOOR_SMOKE_BASELINE_DIR="${DEEPSEEK_ADAFLOOR_SMOKE_BASELINE_DIR:-/data/adafloor_shared_state/deepseek_v2_lite/threshold_actor_2step_n16_tq1_no_overlap_20260804T031350Z/epoch_000_mode0_probe}"
export DEEPSEEK_ADAFLOOR_SMOKE_TRAINING_STEPS=2
export DEEPSEEK_ADAFLOOR_SMOKE_TRAIN_BATCH_SIZE=32
export DEEPSEEK_ADAFLOOR_SMOKE_ROLLOUT_N=16
export DEEPSEEK_ADAFLOOR_SMOKE_MAX_PROMPT_LENGTH=1024
export DEEPSEEK_ADAFLOOR_SMOKE_MAX_RESPONSE_LENGTH=64
export DEEPSEEK_ADAFLOOR_SMOKE_TAIL_VALIDATE_LEVEL_TOKENS='4,16,32,64,64'
export DEEPSEEK_ADAFLOOR_SMOKE_TASK_QUEUE_ENABLE=1
export DEEPSEEK_ADAFLOOR_SMOKE_RECOMPUTE_METHOD=uniform
export DEEPSEEK_ADAFLOOR_SMOKE_RECOMPUTE_NUM_LAYERS=1
export DEEPSEEK_ADAFLOOR_SMOKE_MOE_ALLTOALL_OVERLAP_COMM=False
export DEEPSEEK_ADAFLOOR_SMOKE_MOE_SHARED_EXPERT_OVERLAP=False
export DEEPSEEK_ADAFLOOR_SMOKE_DEALLOCATE_PIPELINE_OUTPUTS=False

echo "[DeepSeek floor2 threshold smoke] topology=EP16 stages=8,4,2 steps=2 n=16"
exec "$SCRIPT_DIR/run_deepseek_v2_lite_adafloor_smoke.sh" "$@"
