#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$SCRIPT_DIR"

unset LOCAL_TEST_LAUNCHER

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    cat <<'EOF'
Usage:
  ./run_mode1_dynamic_length_aware_adaptive_floor4_planned_tailguard_resume_epoch2.sh [extra hydra args...]

Resume only epoch_002_mode1_planned in the existing
mode1_dynamic_length_aware_adaptive_floor4_planned_tailguard_full3 run.
It preserves epoch0/epoch1, resumes from epoch1/global_step_5, and moves any
existing epoch2 directory to a timestamped backup before rerunning epoch2.
EOF
    exit 0
fi

if [[ "${DYNAMIC_RESUME_EPOCH2_XTRACE:-0}" == "1" ]]; then
    set -x
fi

RUN_NAME="${DYNAMIC_RUN_NAME:-mode1_dynamic_length_aware_adaptive_floor4_planned_tailguard_full3}"
BASE="$SCRIPT_DIR/$RUN_NAME"
EPOCH0="$BASE/epoch_000_mode0_probe"
EPOCH1="$BASE/epoch_001_mode1_planned"
EPOCH2="$BASE/epoch_002_mode1_planned"
RESUME_CKPT="${DYNAMIC_INITIAL_RESUME_CKPT:-$EPOCH1/checkpoints/qwen3moe_for_eagle3/global_step_5}"

if [[ ! -d "$EPOCH0/rollout_data" || ! -d "$EPOCH1/rollout_data" ]]; then
    echo "Missing epoch0/epoch1 rollout history under $BASE" >&2
    exit 2
fi
if [[ ! -d "$RESUME_CKPT" ]]; then
    echo "Missing resume checkpoint: $RESUME_CKPT" >&2
    exit 2
fi

if [[ -d "$EPOCH2" ]]; then
    backup="${EPOCH2}_before_resume_$(date -u +%Y%m%dT%H%M%SZ)"
    echo "[resume epoch2] moving existing incomplete epoch2 to $backup"
    mv "$EPOCH2" "$backup"
fi

DYNAMIC_RUN_NAME="$RUN_NAME" \
DYNAMIC_DRIVER_XTRACE="${DYNAMIC_DRIVER_XTRACE:-${DYNAMIC_RESUME_EPOCH2_XTRACE:-0}}" \
DYNAMIC_TOTAL_EPOCHS=3 \
DYNAMIC_START_EPOCH=2 \
DYNAMIC_SHRINK_POLICY=planned \
DYNAMIC_SKIP_MODE0_PROBE=1 \
DYNAMIC_INITIAL_BASELINE_DIR="$EPOCH0,$EPOCH1" \
DYNAMIC_INITIAL_RESUME_CKPT="$RESUME_CKPT" \
DYNAMIC_ENABLE_CKPT_CHAIN=1 \
DYNAMIC_PLAN_STEPS="${DYNAMIC_PLAN_STEPS:-5}" \
DYNAMIC_TRAIN_STEPS="${DYNAMIC_TRAIN_STEPS:-5}" \
DYNAMIC_ENABLE_THRESHOLD_CONTROL=0 \
DYNAMIC_SHORT_STEP_CAP_ENABLE="${DYNAMIC_SHORT_STEP_CAP_ENABLE:-1}" \
DYNAMIC_SHORT_STEP_EXIT_THRESHOLD="${DYNAMIC_SHORT_STEP_EXIT_THRESHOLD:-4096}" \
DYNAMIC_SHORT_STEP_CAP_TOKENS="${DYNAMIC_SHORT_STEP_CAP_TOKENS:-4096}" \
DYNAMIC_SHORT_STEP_CAP_FLOORS="${DYNAMIC_SHORT_STEP_CAP_FLOORS:-4}" \
DYNAMIC_TAIL_GUARD_RATIO_QUANTILE="${DYNAMIC_TAIL_GUARD_RATIO_QUANTILE:-0.95}" \
DYNAMIC_TAIL_GUARD_RATIO_WINDOW="${DYNAMIC_TAIL_GUARD_RATIO_WINDOW:-3}" \
DYNAMIC_TAIL_GUARD_DEFAULT_RATIO="${DYNAMIC_TAIL_GUARD_DEFAULT_RATIO:-1.20}" \
DYNAMIC_TAIL_GUARD_MIN_CAP="${DYNAMIC_TAIL_GUARD_MIN_CAP:-4096}" \
DYNAMIC_TAIL_GUARD_ROUND_TO="${DYNAMIC_TAIL_GUARD_ROUND_TO:-512}" \
DYNAMIC_IGNORE_TAIL_TIES_AT_RESPONSE_CAP="${DYNAMIC_IGNORE_TAIL_TIES_AT_RESPONSE_CAP:-0}" \
DYNAMIC_RESET_PROGRESS_AFTER_RESUME="${DYNAMIC_RESET_PROGRESS_AFTER_RESUME:-1}" \
VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS:-380800}" \
VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4:-280576}" \
VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8:-377344}" \
VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS="${VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS:-1}" \
VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS="${VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS:-1}" \
VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS:-147456}" \
VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4:-147456}" \
VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8:-114688}" \
VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16:-0}" \
TRAINER_SAVE_FREQ="${TRAINER_SAVE_FREQ:-5}" \
MAX_ACTOR_CKPT_TO_KEEP="${MAX_ACTOR_CKPT_TO_KEEP:-1}" \
./run_mode1_dynamic_length_aware_adaptive_floor4_epochs.sh "$@"
