#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
  ./run_mode1_local_baseline_random_batch.sh [extra hydra args...]

Baseline local test:
  - uses elastic shrink mode=1 with floor=4
  - disables length-aware regroup and shrink-aware prompt scheduling
  - lets the dataset shuffle randomly form batches

Local path overrides:
  MODEL_PATH=/data/Qwen3-30B-A3B
  DISTCP_PATH=/data/Qwen3-30B-A3B_megatron
  TRAIN_FILE=/data/deepscaler/train.parquet
  TEST_FILE=/data/deepscaler/test.parquet
  CHECK_LOCAL_INPUTS=0  # skip path checks
EOF
}

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT="${REPO_ROOT:-$SCRIPT_DIR}"
PATCH_TREE="${PATCH_TREE:-$REPO_ROOT}"
LAUNCHER="${LOCAL_TEST_LAUNCHER:-$PATCH_TREE/internal/wj_train_grpo_qwen30b_a3b_16die_true_weight_regroup.sh}"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

MODEL_PATH="${MODEL_PATH:-/data/Qwen3-30B-A3B}"
DISTCP_PATH="${DISTCP_PATH:-/data/Qwen3-30B-A3B_megatron}"
TRAIN_FILE="${TRAIN_FILE:-/data/deepscaler/train.parquet}"
TEST_FILE="${TEST_FILE:-/data/deepscaler/test.parquet}"

if [[ "${CHECK_LOCAL_INPUTS:-1}" == "1" ]]; then
    for required_path in "$MODEL_PATH" "$DISTCP_PATH" "$TRAIN_FILE" "$TEST_FILE"; do
        if [[ ! -e "$required_path" ]]; then
            echo "missing local input path: $required_path" >&2
            echo "Set MODEL_PATH/DISTCP_PATH/TRAIN_FILE/TEST_FILE, or CHECK_LOCAL_INPUTS=0 to skip checks." >&2
            exit 2
        fi
    done
fi

floor="${MODE1_FLOOR:-4}"
case "$floor" in
    4) ;;
    *)
        echo "baseline local test is fixed to mode=1 shrink floor=4; got MODE1_FLOOR=$floor" >&2
        exit 2
        ;;
esac

export VLLM_ASCEND_ENABLE_ELASTIC_PARALLEL_SHRINK=1
export VLLM_ASCEND_ELASTIC_EXECUTION_MODE=1
export VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE=4
export VLLM_ASCEND_SHRINK_AWARE_ENABLE=0
export VLLM_ASCEND_REGISTER_CUSTOM_MODELS="${VLLM_ASCEND_REGISTER_CUSTOM_MODELS:-1}"
export VLLM_ASCEND_USE_NATIVE_QWEN3_MOE=0
export VLLM_EAGER_BASELINE_NO_RESAMPLE=1
export VLLM_EPOCH_LENGTH_REGROUP_ENABLE=0
export VLLM_ROLLOUT_EARLY_STOP_ENABLE="${VLLM_ROLLOUT_EARLY_STOP_ENABLE:-0}"
export VLLM_ROLLOUT_EARLY_STOP_FACTOR="${VLLM_ROLLOUT_EARLY_STOP_FACTOR:-2.0}"
export VLLM_ROLLOUT_EARLY_STOP_MIN_TOKENS="${VLLM_ROLLOUT_EARLY_STOP_MIN_TOKENS:-10000}"
export VERL_SIDECAR_ENABLE="${VERL_SIDECAR_ENABLE:-0}"
export VLLM_MOE_PATTERN_STATS=0
export VLLM_MOE_STATS=0
export VLLM_MOE_STATS_TIMING=0
export VLLM_ASCEND_NATIVE_MOE_TOPK_DEBUG=0

export VLLM_ASCEND_CUSTOM_MODE1_KV_MATERIALIZE_HEADROOM_BYTES="${VLLM_ASCEND_CUSTOM_MODE1_KV_MATERIALIZE_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_KV_CACHE_INIT_HEADROOM_BYTES="${VLLM_ASCEND_KV_CACHE_INIT_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_HEADROOM_BYTES="${VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_LOW_FLOOR_HEADROOM_BYTES="${VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_LOW_FLOOR_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_SHRINK_PREFILL_ALLTOALL_HEADROOM_BYTES="${VLLM_ASCEND_POST_SHRINK_PREFILL_ALLTOALL_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_RESTORE_DP_HEADROOM_BYTES="${VLLM_ASCEND_POST_RESTORE_DP_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_RESTORE_EP_HEADROOM_BYTES="${VLLM_ASCEND_POST_RESTORE_EP_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_RESTORE_MOE_DISPATCH_HEADROOM_BYTES="${VLLM_ASCEND_POST_RESTORE_MOE_DISPATCH_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_FIRST_LIVE_PREFILL_HEADROOM_BYTES="${VLLM_ASCEND_FIRST_LIVE_PREFILL_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_FIRST_LIVE_PREFILL_LOW_FLOOR_HEADROOM_BYTES="${VLLM_ASCEND_FIRST_LIVE_PREFILL_LOW_FLOOR_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_EXTRA_ELASTIC_SAFETY_HEADROOM_BYTES="${VLLM_ASCEND_EXTRA_ELASTIC_SAFETY_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_FLOOR_PREALLOC_HEADROOM_SAFETY_BYTES="${VLLM_ASCEND_FLOOR_PREALLOC_HEADROOM_SAFETY_BYTES:-0}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS:-377344}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4:-321408}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_FULLWORLD_EP_CACHE="${VLLM_ASCEND_MODE1_PARITY_KEEP_FULLWORLD_EP_CACHE:-1}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE="${VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE:-0}"
export VLLM_ASCEND_MODE1_PARITY_DROP_STALE_CACHE_AFTER_SHRINK="${VLLM_ASCEND_MODE1_PARITY_DROP_STALE_CACHE_AFTER_SHRINK:-0}"
export VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS="${VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS:-0}"
export VLLM_ASCEND_MODE1_PARITY_FORCE_CLEANUP_AFTER_FLOOR_GROUP_RELEASE="${VLLM_ASCEND_MODE1_PARITY_FORCE_CLEANUP_AFTER_FLOOR_GROUP_RELEASE:-1}"
export VLLM_ASCEND_MODE1_PARITY_SINGLE_LIVE_MC2_GROUP="${VLLM_ASCEND_MODE1_PARITY_SINGLE_LIVE_MC2_GROUP:-0}"
export VLLM_ASCEND_DISABLE_ELASTIC_MC2_GROUP_CACHE="${VLLM_ASCEND_DISABLE_ELASTIC_MC2_GROUP_CACHE:-0}"
export VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_ALLTOALL_WARMUP="${VLLM_ASCEND_MODE1_PARITY_POST_RESTORE_ALLTOALL_WARMUP:-0}"
export VLLM_ASCEND_POST_SHRINK_STAGING_RELEASE_EMPTY_CACHE="${VLLM_ASCEND_POST_SHRINK_STAGING_RELEASE_EMPTY_CACHE:-1}"
export VLLM_ASCEND_POST_SHRINK_STAGING_RELEASE_SYNC="${VLLM_ASCEND_POST_SHRINK_STAGING_RELEASE_SYNC:-1}"
export VLLM_ASCEND_MODE1_PARITY_SYNC_AFTER_MC2_GROUP_DESTROY="${VLLM_ASCEND_MODE1_PARITY_SYNC_AFTER_MC2_GROUP_DESTROY:-0}"
export VLLM_ASCEND_MODE1_PARITY_GC_AFTER_MC2_GROUP_DESTROY="${VLLM_ASCEND_MODE1_PARITY_GC_AFTER_MC2_GROUP_DESTROY:-0}"
export VLLM_ASCEND_MODE1_PARITY_RELEASE_DP_WARMUP_CACHE="${VLLM_ASCEND_MODE1_PARITY_RELEASE_DP_WARMUP_CACHE:-0}"
export VLLM_ASCEND_MODE1_PARITY_RELEASE_WARMUP_CACHE="${VLLM_ASCEND_MODE1_PARITY_RELEASE_WARMUP_CACHE:-1}"
export VLLM_ASCEND_MODE1_PARITY_PRE_MOE_WARMUP_EMPTY_CACHE="${VLLM_ASCEND_MODE1_PARITY_PRE_MOE_WARMUP_EMPTY_CACHE:-1}"
export VLLM_ASCEND_MODE1_PARITY_POST_SHRINK_WARMUP="${VLLM_ASCEND_MODE1_PARITY_POST_SHRINK_WARMUP:-1}"
export VLLM_ASCEND_REPEAT_POST_SHRINK_MOE_DISPATCH_WARMUP="${VLLM_ASCEND_REPEAT_POST_SHRINK_MOE_DISPATCH_WARMUP:-1}"
export VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG="${VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG:-1}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE="${VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE:-0}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_KINDS="${VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_KINDS:-dp,ep}"
export VLLM_ASCEND_MODE1_PARITY_DROP_OLD_FLOOR_BEFORE_REBUILD="${VLLM_ASCEND_MODE1_PARITY_DROP_OLD_FLOOR_BEFORE_REBUILD:-1}"
export VLLM_ASCEND_MODE1_PARITY_RELEASE_LIVE_OLD_FLOOR_ON_REBUILD="${VLLM_ASCEND_MODE1_PARITY_RELEASE_LIVE_OLD_FLOOR_ON_REBUILD:-1}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY="${VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY:-1}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_FULL_RESTORE="${VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_FULL_RESTORE:-0}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_PRE_REBUILD="${VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_PRE_REBUILD:-0}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_STASH="${VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_STASH:-0}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_DESTROY_FLOOR_GROUP_SIZES="${VLLM_ASCEND_MODE1_PARITY_DEFER_DESTROY_FLOOR_GROUP_SIZES:-1,2,4,8}"
export VLLM_ASCEND_MODE1_PARITY_SYNC_BEFORE_DEVICE_PG_RETIRE="${VLLM_ASCEND_MODE1_PARITY_SYNC_BEFORE_DEVICE_PG_RETIRE:-1}"
export VLLM_ASCEND_MODE1_PARITY_DESTROY_DEVICE_PG_ON_RETIRE="${VLLM_ASCEND_MODE1_PARITY_DESTROY_DEVICE_PG_ON_RETIRE:-1}"
export VLLM_ASCEND_MODE1_PARITY_DESTROY_CPU_PG_ON_RETIRE="${VLLM_ASCEND_MODE1_PARITY_DESTROY_CPU_PG_ON_RETIRE:-1}"
export VLLM_ASCEND_MODE1_PARITY_ENABLE_POST_SHRINK_DP_WARMUP="${VLLM_ASCEND_MODE1_PARITY_ENABLE_POST_SHRINK_DP_WARMUP:-0}"
export VLLM_ASCEND_CUSTOM_MODE1_DEBUG=0
export VLLM_ASCEND_CUSTOM_MODE1_TIMING_EVENTS=0
export VLLM_ASCEND_CUSTOM_MODE1_KV_DIAG=0
export VLLM_ASCEND_CUSTOM_MODE1_ROLLOUT_RELOAD_DIAG="${VLLM_ASCEND_CUSTOM_MODE1_ROLLOUT_RELOAD_DIAG:-0}"
export VLLM_ASCEND_CUSTOM_MODE1_GLOBAL_TENSOR_SCAN="${VLLM_ASCEND_CUSTOM_MODE1_GLOBAL_TENSOR_SCAN:-0}"
export VLLM_ASCEND_MODE1_BATCH_DIRECT_NPU_IMPORT="${VLLM_ASCEND_MODE1_BATCH_DIRECT_NPU_IMPORT:-1}"
export VLLM_ASCEND_MODE1_ALLOW_SCALAR_DIRECT_NPU_IMPORT="${VLLM_ASCEND_MODE1_ALLOW_SCALAR_DIRECT_NPU_IMPORT:-0}"
export VLLM_ASCEND_MODE1_ALLOW_BATCH_INDEX_SELECT_EXPORT="${VLLM_ASCEND_MODE1_ALLOW_BATCH_INDEX_SELECT_EXPORT:-0}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_BATCH_EXPERTS="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_BATCH_EXPERTS:-8}"
export VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC="${VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC:-0}"

export HCCL_IF_BASE_PORT="${HCCL_IF_BASE_PORT:-47241}"
export MASTER_PORT="${MASTER_PORT:-26240}"
export VERL_HCCL_IF_BASE_PORT_START="${VERL_HCCL_IF_BASE_PORT_START:-47241}"

export HOME="$REPO_ROOT"
export OUTPUT_ROOT="${OUTPUT_ROOT:-$REPO_ROOT}"
export OUTPUT_SUBDIR="${OUTPUT_SUBDIR:-mode1_baseline_random_batch_floor4}"
export CONFIG_DIR="$PATCH_TREE/verl/trainer/config"
export PYTHONPATH="$PATCH_TREE${PYTHONPATH:+:$PYTHONPATH}"
export MODEL_PATH DISTCP_PATH TRAIN_FILE TEST_FILE

TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-32}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-1024}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-16384}"
ROLLOUT_N="${ROLLOUT_N:-16}"
ROLLOUT_MAX_NUM_SEQS="${ROLLOUT_MAX_NUM_SEQS:-32}"
ROLLOUT_MAX_NUM_BATCHED_TOKENS="${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-$((MAX_PROMPT_LENGTH + MAX_RESPONSE_LENGTH))}"
ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.8}"
TRAINER_TOTAL_EPOCHS="${TRAINER_TOTAL_EPOCHS:-1}"
EXTRA_OVERRIDES=()
if [[ -n "${DATASET_FRACTION:-}" ]]; then
    EXTRA_OVERRIDES+=("data.dataset_fraction=$DATASET_FRACTION")
fi

cd "$PATCH_TREE"
stamp=$(date -u +%Y%m%dT%H%M%SZ)
tee_log="$REPO_ROOT/mode1_local_baseline_random_batch_floor4_${stamp}.log"

printf '[mode1 local baseline random] runtime_cwd=%s\n' "$PATCH_TREE"
printf '[mode1 local baseline random] launcher=%s tee_log=%s\n' "$LAUNCHER" "$tee_log"
printf '[mode1 local baseline random] model=%s distcp=%s train=%s test=%s\n' \
    "$MODEL_PATH" "$DISTCP_PATH" "$TRAIN_FILE" "$TEST_FILE"
printf '[mode1 local baseline random] mode=1 floor=4 length_regroup=%s baseline_no_resample=%s dataset_shuffle=True\n' \
    "$VLLM_EPOCH_LENGTH_REGROUP_ENABLE" "$VLLM_EAGER_BASELINE_NO_RESAMPLE"
printf '[mode1 local baseline random] dataset_fraction=%s moe_stats=%s moe_stats_timing=%s native_topk_debug=%s\n' \
    "${DATASET_FRACTION:-launcher_default}" \
    "$VLLM_MOE_PATTERN_STATS" \
    "$VLLM_MOE_STATS_TIMING" \
    "$VLLM_ASCEND_NATIVE_MOE_TOPK_DEBUG"
printf '[mode1 local baseline random] rollout_early_stop=%s factor=%s min_tokens=%s max_response=%s max_batched_tokens=%s total_epochs=%s\n' \
    "$VLLM_ROLLOUT_EARLY_STOP_ENABLE" \
    "$VLLM_ROLLOUT_EARLY_STOP_FACTOR" \
    "$VLLM_ROLLOUT_EARLY_STOP_MIN_TOKENS" \
    "$MAX_RESPONSE_LENGTH" \
    "$ROLLOUT_MAX_NUM_BATCHED_TOKENS" \
    "$TRAINER_TOTAL_EPOCHS"
printf '[mode1 local baseline random] kv_cap=%s kv_cap_floor4=%s custom_kv_headroom=%s kv_init_headroom=%s custom_models=%s native_qwen3=%s\n' \
    "$VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS" \
    "$VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4" \
    "$VLLM_ASCEND_CUSTOM_MODE1_KV_MATERIALIZE_HEADROOM_BYTES" \
    "$VLLM_ASCEND_KV_CACHE_INIT_HEADROOM_BYTES" \
    "$VLLM_ASCEND_REGISTER_CUSTOM_MODELS" \
    "$VLLM_ASCEND_USE_NATIVE_QWEN3_MOE"
printf '[mode1 local baseline random] generic_headroom post_shrink_moe=%s post_shrink_prefill=%s post_restore_dp=%s post_restore_ep=%s post_restore_moe=%s first_prefill=%s extra_safety=%s floor_prealloc_safety=%s cache_floor_groups=%s force_floor_cleanup=%s\n' \
    "$VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_LOW_FLOOR_HEADROOM_BYTES" \
    "$VLLM_ASCEND_POST_SHRINK_PREFILL_ALLTOALL_HEADROOM_BYTES" \
    "$VLLM_ASCEND_POST_RESTORE_DP_HEADROOM_BYTES" \
    "$VLLM_ASCEND_POST_RESTORE_EP_HEADROOM_BYTES" \
    "$VLLM_ASCEND_POST_RESTORE_MOE_DISPATCH_HEADROOM_BYTES" \
    "$VLLM_ASCEND_FIRST_LIVE_PREFILL_LOW_FLOOR_HEADROOM_BYTES" \
    "$VLLM_ASCEND_EXTRA_ELASTIC_SAFETY_HEADROOM_BYTES" \
    "$VLLM_ASCEND_FLOOR_PREALLOC_HEADROOM_SAFETY_BYTES" \
    "$VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS" \
    "$VLLM_ASCEND_MODE1_PARITY_FORCE_CLEANUP_AFTER_FLOOR_GROUP_RELEASE"

bash "$LAUNCHER" \
    data.train_files="$TRAIN_FILE" \
    data.val_files="$TEST_FILE" \
    data.train_batch_size="$TRAIN_BATCH_SIZE" \
    data.max_prompt_length="$MAX_PROMPT_LENGTH" \
    data.max_response_length="$MAX_RESPONSE_LENGTH" \
    data.shuffle=True \
    actor_rollout_ref.model.path="$MODEL_PATH" \
    actor_rollout_ref.actor.megatron.dist_checkpointing_path="$DISTCP_PATH" \
    actor_rollout_ref.ref.megatron.dist_checkpointing_path="$DISTCP_PATH" \
    actor_rollout_ref.rollout.max_num_batched_tokens="$ROLLOUT_MAX_NUM_BATCHED_TOKENS" \
    actor_rollout_ref.rollout.max_num_seqs="$ROLLOUT_MAX_NUM_SEQS" \
    actor_rollout_ref.rollout.n="$ROLLOUT_N" \
    actor_rollout_ref.rollout.gpu_memory_utilization="$ROLLOUT_GPU_MEMORY_UTILIZATION" \
    actor_rollout_ref.rollout.shrink_aware.enable_shrink_aware_scheduling=false \
    actor_rollout_ref.rollout.shrink_aware.shrink_aware_mode=off \
    actor_rollout_ref.rollout.shrink_aware.enable_shrink_aware_logging=false \
    trainer.total_epochs="$TRAINER_TOTAL_EPOCHS" \
    "${EXTRA_OVERRIDES[@]}" \
    "$@" 2>&1 | tee "$tee_log"
