#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
  ./run_mode1_local_length_sorted_e2e_adaptive_floor4.sh [extra hydra args...]

Mode=1 adaptive-floor length-sorted end-to-end rollout-time experiment:
  1. Reads baseline rollout responses from mode1_baseline_random_batch_floor4.
  2. Sorts prompts by baseline max response length and chunks every 32 prompts
     into one rollout step.
  3. Assigns each 32-prompt step to 16 ranks with KV-aware pair matching.
  4. Selects each step's lowest KV-feasible floor from 4/8/16.
     This keeps the runtime floor at 4 while floor=2 is investigated separately.
  5. Runs mode=1 with per-step survivor plans.
EOF
}

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT="${REPO_ROOT:-$SCRIPT_DIR}"
PATCH_TREE="${PATCH_TREE:-$REPO_ROOT}"
LAUNCHER="${LOCAL_TEST_LAUNCHER:-$PATCH_TREE/internal/wj_train_grpo_qwen30b_a3b_16die_true_weight_regroup.sh}"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

MODEL_PATH="${MODEL_PATH:-/data/Qwen3-30B-A3B}"
DISTCP_PATH="${DISTCP_PATH:-/data/Qwen3-30B-A3B_megatron}"
TRAIN_FILE_ORIG="${TRAIN_FILE_ORIG:-/data/deepscaler/train.parquet}"
TEST_FILE="${TEST_FILE:-/data/deepscaler/test.parquet}"
BASELINE_DIR="${BASELINE_DIR:-$REPO_ROOT/mode1_baseline_random_batch_floor4}"
BASELINE_DIRS="${BASELINE_DIRS:-$BASELINE_DIR}"
IFS=':' read -r -a BASELINE_DIR_ARRAY <<< "$BASELINE_DIRS"

if [[ "${CHECK_LOCAL_INPUTS:-1}" == "1" ]]; then
    for required_path in "$MODEL_PATH" "$DISTCP_PATH" "$TRAIN_FILE_ORIG" "$TEST_FILE"; do
        if [[ ! -e "$required_path" ]]; then
            echo "missing local input path: $required_path" >&2
            exit 2
        fi
    done
    for required_path in "${BASELINE_DIR_ARRAY[@]}"; do
        if [[ ! -e "$required_path" ]]; then
            echo "missing baseline input path: $required_path" >&2
            exit 2
        fi
    done
fi

export VLLM_ASCEND_ENABLE_ELASTIC_PARALLEL_SHRINK=1
export VLLM_ASCEND_ELASTIC_EXECUTION_MODE=1
export VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE=4
export VLLM_ASCEND_SHRINK_AWARE_ENABLE=1
export VLLM_ASCEND_REGISTER_CUSTOM_MODELS="${VLLM_ASCEND_REGISTER_CUSTOM_MODELS:-1}"
export VLLM_ASCEND_USE_NATIVE_QWEN3_MOE=0
export VLLM_ASCEND_SHRINK_AWARE_MODE=staged
export VLLM_ASCEND_SHRINK_AWARE_STAGES=8,4
export VLLM_ASCEND_SHRINK_AWARE_SURVIVOR_POLICY=manual
export VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY=${VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY:-natural}
export VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE=${VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE:-$([[ "${VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY}" =~ ^(planned|fixed|plan)$ ]] && echo 1 || echo 0)}
export VLLM_ASCEND_SHRINK_AWARE_INTERMEDIATE_RANKS=8,9,10,11,12,13,14,15
export VLLM_ASCEND_SHRINK_AWARE_FINAL_RANKS=12,13,14,15
export VLLM_EAGER_BASELINE_NO_RESAMPLE=0
export VLLM_EPOCH_LENGTH_REGROUP_ENABLE=0
export ROLLOUT_ENFORCE_EAGER="${ROLLOUT_ENFORCE_EAGER:-True}"
export VLLM_ROLLOUT_EARLY_STOP_ENABLE="${VLLM_ROLLOUT_EARLY_STOP_ENABLE:-0}"
export VERL_SIDECAR_ENABLE="${VERL_SIDECAR_ENABLE:-0}"
export VLLM_MOE_PATTERN_STATS=0
export VLLM_MOE_STATS=0
export VLLM_MOE_STATS_TIMING=0
export VLLM_ASCEND_NATIVE_MOE_TOPK_DEBUG=0

export VLLM_ASCEND_CUSTOM_MODE1_KV_MATERIALIZE_HEADROOM_BYTES="${VLLM_ASCEND_CUSTOM_MODE1_KV_MATERIALIZE_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_KV_CACHE_INIT_HEADROOM_BYTES="${VLLM_ASCEND_KV_CACHE_INIT_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_HEADROOM_BYTES="${VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_LOW_FLOOR_HEADROOM_BYTES="${VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_LOW_FLOOR_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_SHRINK_PREFILL_ALLTOALL_HEADROOM_BYTES="${VLLM_ASCEND_POST_SHRINK_PREFILL_ALLTOALL_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_RESTORE_DP_HEADROOM_BYTES="${VLLM_ASCEND_POST_RESTORE_DP_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_RESTORE_EP_HEADROOM_BYTES="${VLLM_ASCEND_POST_RESTORE_EP_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_RESTORE_MOE_DISPATCH_HEADROOM_BYTES="${VLLM_ASCEND_POST_RESTORE_MOE_DISPATCH_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_FIRST_LIVE_PREFILL_HEADROOM_BYTES="${VLLM_ASCEND_FIRST_LIVE_PREFILL_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_FIRST_LIVE_PREFILL_LOW_FLOOR_HEADROOM_BYTES="${VLLM_ASCEND_FIRST_LIVE_PREFILL_LOW_FLOOR_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_EXTRA_ELASTIC_SAFETY_HEADROOM_BYTES="${VLLM_ASCEND_EXTRA_ELASTIC_SAFETY_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_FLOOR_PREALLOC_HEADROOM_SAFETY_BYTES="${VLLM_ASCEND_FLOOR_PREALLOC_HEADROOM_SAFETY_BYTES:-0}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS:-380800}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2:-147456}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4:-280576}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8:-377344}"
export VLLM_ASCEND_MODE1_ADAPTIVE_KV_RESIZE="${VLLM_ASCEND_MODE1_ADAPTIVE_KV_RESIZE:-1}"
export VLLM_ASCEND_MODE1_ADAPTIVE_KV_RESIZE_HEADROOM_BYTES="${VLLM_ASCEND_MODE1_ADAPTIVE_KV_RESIZE_HEADROOM_BYTES:-536870912}"
export VLLM_ASCEND_MODE1_STEP_KV_CAP_INCLUDES_PLANNED_HEADROOM="${VLLM_ASCEND_MODE1_STEP_KV_CAP_INCLUDES_PLANNED_HEADROOM:-1}"
export VLLM_ASCEND_MODE1_REFRESH_GROUPS_ON_KV_RESIZE="${VLLM_ASCEND_MODE1_REFRESH_GROUPS_ON_KV_RESIZE:-0}"
export VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE="${VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE:-0}"
if [[ "${VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY}" =~ ^(planned|fixed|plan)$ ]]; then
    DEFAULT_PRECREATE_PLANNED_FLOOR_GROUPS=1
    DEFAULT_CACHE_PLANNED_FLOOR_GROUPS=1
    DEFAULT_PRECREATE_COMM_CACHE=1
    DEFAULT_PRECREATE_DISPATCH_WARMUP=1
    DEFAULT_COMM_CACHE_STATE_LOG=1
    DEFAULT_PREFILL_PLANNED_EXPERT_SLOTS=1
    DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS=147456
    DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2=147456
    DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4=147456
    DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8=114688
    DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16=0
else
    DEFAULT_PRECREATE_PLANNED_FLOOR_GROUPS=0
    DEFAULT_CACHE_PLANNED_FLOOR_GROUPS=0
    DEFAULT_PRECREATE_COMM_CACHE=0
    DEFAULT_PRECREATE_DISPATCH_WARMUP=0
    DEFAULT_COMM_CACHE_STATE_LOG=0
    DEFAULT_PREFILL_PLANNED_EXPERT_SLOTS=0
    DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS=0
    DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2=0
    DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4=0
    DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8=0
    DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16=0
fi
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS="${VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS:-$DEFAULT_PRECREATE_PLANNED_FLOOR_GROUPS}"
if [[ "${VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
    export VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS="${VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS:-$DEFAULT_CACHE_PLANNED_FLOOR_GROUPS}"
    export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS:-$DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS}"
    export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2:-$DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2}"
    export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4:-$DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4}"
    export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8:-$DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8}"
    export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16:-$DEFAULT_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16}"
else
    export VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS="${VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS:-$DEFAULT_CACHE_PLANNED_FLOOR_GROUPS}"
    export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS:-0}"
    export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2:-0}"
    export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4:-0}"
    export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8:-0}"
    export VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16="${VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16:-0}"
fi
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_COMM_CACHE="${VLLM_ASCEND_MODE1_PARITY_PRECREATE_COMM_CACHE:-$DEFAULT_PRECREATE_COMM_CACHE}"
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_DISPATCH_WARMUP="${VLLM_ASCEND_MODE1_PARITY_PRECREATE_DISPATCH_WARMUP:-$DEFAULT_PRECREATE_DISPATCH_WARMUP}"
export VLLM_ASCEND_MODE1_COMM_CACHE_STATE_LOG="${VLLM_ASCEND_MODE1_COMM_CACHE_STATE_LOG:-$DEFAULT_COMM_CACHE_STATE_LOG}"
export VLLM_ASCEND_MODE1_PARITY_PREFILL_PLANNED_EXPERT_SLOTS="${VLLM_ASCEND_MODE1_PARITY_PREFILL_PLANNED_EXPERT_SLOTS:-$DEFAULT_PREFILL_PLANNED_EXPERT_SLOTS}"
export VLLM_ASCEND_MODE1_PARITY_PREFILL_PLANNED_EXPERT_SLOTS_ON_RESIZE="${VLLM_ASCEND_MODE1_PARITY_PREFILL_PLANNED_EXPERT_SLOTS_ON_RESIZE:-1}"
export VLLM_ASCEND_MODE1_PARITY_FORCE_DESTROY_PLANNED_PRUNE="${VLLM_ASCEND_MODE1_PARITY_FORCE_DESTROY_PLANNED_PRUNE:-1}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_FULLWORLD_EP_CACHE="${VLLM_ASCEND_MODE1_PARITY_KEEP_FULLWORLD_EP_CACHE:-1}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE="${VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE:-0}"
export VLLM_ASCEND_MODE1_PARITY_DROP_STALE_CACHE_AFTER_SHRINK="${VLLM_ASCEND_MODE1_PARITY_DROP_STALE_CACHE_AFTER_SHRINK:-0}"
export VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS="${VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS:-0}"
export VLLM_ASCEND_MODE1_PARITY_FORCE_CLEANUP_AFTER_FLOOR_GROUP_RELEASE="${VLLM_ASCEND_MODE1_PARITY_FORCE_CLEANUP_AFTER_FLOOR_GROUP_RELEASE:-1}"
export VLLM_ASCEND_MODE1_PARITY_SINGLE_LIVE_MC2_GROUP="${VLLM_ASCEND_MODE1_PARITY_SINGLE_LIVE_MC2_GROUP:-0}"
export VLLM_ASCEND_DISABLE_ELASTIC_MC2_GROUP_CACHE="${VLLM_ASCEND_DISABLE_ELASTIC_MC2_GROUP_CACHE:-0}"
export VLLM_ASCEND_POST_SHRINK_STAGING_RELEASE_EMPTY_CACHE="${VLLM_ASCEND_POST_SHRINK_STAGING_RELEASE_EMPTY_CACHE:-1}"
export VLLM_ASCEND_POST_SHRINK_STAGING_RELEASE_SYNC="${VLLM_ASCEND_POST_SHRINK_STAGING_RELEASE_SYNC:-1}"
export VLLM_ASCEND_MODE1_PARITY_RELEASE_WARMUP_CACHE="${VLLM_ASCEND_MODE1_PARITY_RELEASE_WARMUP_CACHE:-1}"
export VLLM_ASCEND_MODE1_PARITY_PRE_MOE_WARMUP_EMPTY_CACHE="${VLLM_ASCEND_MODE1_PARITY_PRE_MOE_WARMUP_EMPTY_CACHE:-1}"
export VLLM_ASCEND_MODE1_PARITY_POST_SHRINK_WARMUP="${VLLM_ASCEND_MODE1_PARITY_POST_SHRINK_WARMUP:-0}"
export VLLM_ASCEND_MODE1_PARITY_POST_SHRINK_WARMUP_KIND="${VLLM_ASCEND_MODE1_PARITY_POST_SHRINK_WARMUP_KIND:-mc2_dispatcher_only}"
export VLLM_ASCEND_REPEAT_POST_SHRINK_MOE_DISPATCH_WARMUP="${VLLM_ASCEND_REPEAT_POST_SHRINK_MOE_DISPATCH_WARMUP:-0}"
export VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG="${VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG:-1}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE="${VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE:-0}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_KINDS="${VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_KINDS:-dp,ep}"
export VLLM_ASCEND_MODE1_PARITY_DROP_OLD_FLOOR_BEFORE_REBUILD="${VLLM_ASCEND_MODE1_PARITY_DROP_OLD_FLOOR_BEFORE_REBUILD:-1}"
export VLLM_ASCEND_MODE1_PARITY_RELEASE_LIVE_OLD_FLOOR_ON_REBUILD="${VLLM_ASCEND_MODE1_PARITY_RELEASE_LIVE_OLD_FLOOR_ON_REBUILD:-1}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY="${VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY:-1}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_FULL_RESTORE="${VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_FULL_RESTORE:-0}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_PRE_REBUILD="${VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_PRE_REBUILD:-0}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_STASH="${VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_STASH:-0}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_DESTROY_FLOOR_GROUP_SIZES="${VLLM_ASCEND_MODE1_PARITY_DEFER_DESTROY_FLOOR_GROUP_SIZES:-1,2,4,8}"
export VLLM_ASCEND_MODE1_PARITY_SYNC_BEFORE_DEVICE_PG_RETIRE="${VLLM_ASCEND_MODE1_PARITY_SYNC_BEFORE_DEVICE_PG_RETIRE:-1}"
export VLLM_ASCEND_MODE1_PARITY_DESTROY_DEVICE_PG_ON_RETIRE="${VLLM_ASCEND_MODE1_PARITY_DESTROY_DEVICE_PG_ON_RETIRE:-1}"
export VLLM_ASCEND_MODE1_PARITY_DESTROY_CPU_PG_ON_RETIRE="${VLLM_ASCEND_MODE1_PARITY_DESTROY_CPU_PG_ON_RETIRE:-1}"
export VLLM_ASCEND_CUSTOM_MODE1_DEBUG=0
export VLLM_ASCEND_CUSTOM_MODE1_TIMING_EVENTS=0
export VLLM_ASCEND_CUSTOM_MODE1_KV_DIAG=0
export VLLM_ASCEND_CUSTOM_MODE1_ROLLOUT_RELOAD_DIAG="${VLLM_ASCEND_CUSTOM_MODE1_ROLLOUT_RELOAD_DIAG:-0}"
export VLLM_ASCEND_CUSTOM_MODE1_GLOBAL_TENSOR_SCAN="${VLLM_ASCEND_CUSTOM_MODE1_GLOBAL_TENSOR_SCAN:-0}"
export VLLM_ASCEND_MODE1_BATCH_DIRECT_NPU_IMPORT="${VLLM_ASCEND_MODE1_BATCH_DIRECT_NPU_IMPORT:-1}"
export VLLM_ASCEND_MODE1_ALLOW_SCALAR_DIRECT_NPU_IMPORT="${VLLM_ASCEND_MODE1_ALLOW_SCALAR_DIRECT_NPU_IMPORT:-0}"
export VLLM_ASCEND_MODE1_ALLOW_BATCH_INDEX_SELECT_EXPORT="${VLLM_ASCEND_MODE1_ALLOW_BATCH_INDEX_SELECT_EXPORT:-0}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_BATCH_EXPERTS="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_BATCH_EXPERTS:-8}"
export VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC="${VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC:-0}"

export HCCL_IF_BASE_PORT="${HCCL_IF_BASE_PORT:-47241}"
export MASTER_PORT="${MASTER_PORT:-26240}"
export VERL_HCCL_IF_BASE_PORT_START="${VERL_HCCL_IF_BASE_PORT_START:-47241}"

export HOME="$REPO_ROOT"
export OUTPUT_ROOT="${OUTPUT_ROOT:-$REPO_ROOT}"
export OUTPUT_SUBDIR="${OUTPUT_SUBDIR:-mode1_length_sorted_e2e_adaptive_floor4}"
export CONFIG_DIR="$PATCH_TREE/verl/trainer/config"
export PYTHONPATH="$PATCH_TREE${PYTHONPATH:+:$PYTHONPATH}"
export MODEL_PATH DISTCP_PATH TEST_FILE

TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-32}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-1024}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-16384}"
ROLLOUT_N="${ROLLOUT_N:-16}"
ROLLOUT_MAX_NUM_SEQS="${ROLLOUT_MAX_NUM_SEQS:-32}"
ROLLOUT_MAX_NUM_BATCHED_TOKENS="${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-$((MAX_PROMPT_LENGTH + MAX_RESPONSE_LENGTH))}"
ROLLOUT_GPU_MEMORY_UTILIZATION="${ROLLOUT_GPU_MEMORY_UTILIZATION:-0.9}"
TRAINER_TOTAL_EPOCHS="${TRAINER_TOTAL_EPOCHS:-1}"
PLAN_STEPS="${PLAN_STEPS:-5}"
DATASET_FRACTION_FOR_ORACLE="${DATASET_FRACTION_FOR_ORACLE:-0.005}"
SHRINK_AWARE_LOGGING="${SHRINK_AWARE_LOGGING:-false}"
planned_headroom_tokens=0
planned_headroom_tokens_floor2=0
planned_headroom_tokens_floor4=0
planned_headroom_tokens_floor8=0
planned_headroom_tokens_floor16=0
if [[ "${VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS}" =~ ^(1|true|TRUE|yes|YES|on|ON)$ ]]; then
    planned_headroom_tokens="$VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS"
    planned_headroom_tokens_floor2="$VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR2"
    planned_headroom_tokens_floor4="$VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR4"
    planned_headroom_tokens_floor8="$VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR8"
    planned_headroom_tokens_floor16="$VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS_FLOOR16"
fi
effective_floor2_cap=$(( VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2 > planned_headroom_tokens_floor2 ? VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2 - planned_headroom_tokens_floor2 : 0 ))
effective_floor4_cap=$(( VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4 > planned_headroom_tokens_floor4 ? VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4 - planned_headroom_tokens_floor4 : 0 ))
effective_floor8_cap=$(( VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8 > planned_headroom_tokens_floor8 ? VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8 - planned_headroom_tokens_floor8 : 0 ))
effective_floor16_cap=$(( VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS > planned_headroom_tokens_floor16 ? VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS - planned_headroom_tokens_floor16 : 0 ))
MAX_RANK_PEAK_TOKENS="${MAX_RANK_PEAK_TOKENS:-$effective_floor16_cap}"
FLOOR_KV_CAPS="${FLOOR_KV_CAPS:-2:$effective_floor2_cap,4:$effective_floor4_cap,8:$effective_floor8_cap,16:$effective_floor16_cap}"
MIN_ADAPTIVE_FLOOR="${MIN_ADAPTIVE_FLOOR:-4}"
ACTIVE_PEAK_SAFETY_FACTOR="${ACTIVE_PEAK_SAFETY_FACTOR:-1.16}"
LENGTH_EMA_DECAY="${LENGTH_EMA_DECAY:-0.7}"
MAX_RESPONSE_LEN="${MAX_RESPONSE_LEN:-16384}"
IGNORE_TAIL_TIES_AT_RESPONSE_CAP="${IGNORE_TAIL_TIES_AT_RESPONSE_CAP:-0}"
MAX_CROSS_STEP_REPAIR_SWAPS="${MAX_CROSS_STEP_REPAIR_SWAPS:-8}"
REPAIR_CANDIDATE_LIMIT="${REPAIR_CANDIDATE_LIMIT:-8}"

PLAN_DIR="${PLAN_DIR:-$REPO_ROOT/mode1_length_sorted_e2e_adaptive_floor4/oracle}"
OPT_TRAIN_FILE="${OPT_TRAIN_FILE:-$PLAN_DIR/length_sorted_train.parquet}"
OPT_RANK_PLAN="${OPT_RANK_PLAN:-$PLAN_DIR/length_sorted_rank_plan.json}"
OPT_SUMMARY="${OPT_SUMMARY:-$PLAN_DIR/length_sorted_rank_plan_summary.json}"
OPT_ORACLE="${OPT_ORACLE:-$PLAN_DIR/length_sorted_length_oracle.json}"
mkdir -p "$PLAN_DIR"

baseline_args=()
for baseline_dir_item in "${BASELINE_DIR_ARRAY[@]}"; do
    if [[ -n "$baseline_dir_item" ]]; then
        baseline_args+=(--baseline-dir "$baseline_dir_item")
    fi
done
planner_extra_args=()
if [[ "$IGNORE_TAIL_TIES_AT_RESPONSE_CAP" == "1" ]]; then
    planner_extra_args+=(--ignore-tail-ties-at-response-cap)
fi

python3 "$PATCH_TREE/tools/build_mode1_length_sorted_e2e_plan.py" \
    "${baseline_args[@]}" \
    "${planner_extra_args[@]}" \
    --length-ema-decay "$LENGTH_EMA_DECAY" \
    --train-file "$TRAIN_FILE_ORIG" \
    --output-train "$OPT_TRAIN_FILE" \
    --output-plan "$OPT_RANK_PLAN" \
    --output-summary "$OPT_SUMMARY" \
    --output-oracle "$OPT_ORACLE" \
    --steps "$PLAN_STEPS" \
    --batch-size "$TRAIN_BATCH_SIZE" \
    --responses-per-prompt "$ROLLOUT_N" \
    --dataset-fraction "$DATASET_FRACTION_FOR_ORACLE" \
    --max-rank-peak-tokens "$MAX_RANK_PEAK_TOKENS" \
    --adaptive-floor \
    --min-adaptive-floor "$MIN_ADAPTIVE_FLOOR" \
    --floor-kv-caps "$FLOOR_KV_CAPS" \
    --active-peak-safety-factor "$ACTIVE_PEAK_SAFETY_FACTOR" \
    --max-response-len "$MAX_RESPONSE_LEN" \
    --tail-guard-ratio-quantile "${TAIL_GUARD_RATIO_QUANTILE:-0.95}" \
    --tail-guard-ratio-window "${TAIL_GUARD_RATIO_WINDOW:-3}" \
    --tail-guard-default-ratio "${TAIL_GUARD_DEFAULT_RATIO:-1.20}" \
    --tail-guard-min-cap "${TAIL_GUARD_MIN_CAP:-4096}" \
    --tail-guard-round-to "${TAIL_GUARD_ROUND_TO:-512}" \
    --max-cross-step-repair-swaps "$MAX_CROSS_STEP_REPAIR_SWAPS" \
    --repair-candidate-limit "$REPAIR_CANDIDATE_LIMIT"

if [[ "${FAST_STEP_SUBSET:-0}" == "1" ]]; then
    FAST_STEP_SUBSET_STEPS="${FAST_STEP_SUBSET_STEPS:-1,5}"
    fast_slug="${FAST_STEP_SUBSET_STEPS//,/}"
    FAST_TRAIN_FILE="${FAST_TRAIN_FILE:-$PLAN_DIR/length_sorted_fast_steps_${fast_slug}_train.parquet}"
    FAST_RANK_PLAN="${FAST_RANK_PLAN:-$PLAN_DIR/length_sorted_fast_steps_${fast_slug}_rank_plan.json}"
    FAST_ORACLE="${FAST_ORACLE:-$PLAN_DIR/length_sorted_fast_steps_${fast_slug}_length_oracle.json}"
    python3 "$PATCH_TREE/tools/build_mode1_fast_step_subset.py" \
        --input-train "$OPT_TRAIN_FILE" \
        --input-plan "$OPT_RANK_PLAN" \
        --input-oracle "$OPT_ORACLE" \
        --output-train "$FAST_TRAIN_FILE" \
        --output-plan "$FAST_RANK_PLAN" \
        --output-oracle "$FAST_ORACLE" \
        --steps "$FAST_STEP_SUBSET_STEPS"
    OPT_TRAIN_FILE="$FAST_TRAIN_FILE"
    OPT_RANK_PLAN="$FAST_RANK_PLAN"
    OPT_ORACLE="$FAST_ORACLE"
fi

TRAIN_FILE="$OPT_TRAIN_FILE"
export TRAIN_FILE

cd "$PATCH_TREE"
stamp=$(date -u +%Y%m%dT%H%M%SZ)
tee_log="$REPO_ROOT/mode1_local_length_sorted_e2e_adaptive_floor4_${stamp}.log"

printf '[mode1 length-sorted e2e] runtime_cwd=%s\n' "$PATCH_TREE"
printf '[mode1 length-sorted e2e] launcher=%s tee_log=%s\n' "$LAUNCHER" "$tee_log"
printf '[mode1 length-sorted e2e] train=%s plan=%s summary=%s oracle=%s baseline_dirs=%s\n' \
    "$TRAIN_FILE" "$OPT_RANK_PLAN" "$OPT_SUMMARY" "$OPT_ORACLE" "$BASELINE_DIRS"
printf '[mode1 length-sorted e2e] model=%s distcp=%s test=%s\n' \
    "$MODEL_PATH" "$DISTCP_PATH" "$TEST_FILE"
printf '[mode1 length-sorted e2e adaptive] mode=1 global_floor=4 util=%s kv_caps=%s total_epochs=%s\n' \
    "$ROLLOUT_GPU_MEMORY_UTILIZATION" \
    "$FLOOR_KV_CAPS" \
    "$TRAINER_TOTAL_EPOCHS"
printf '[mode1 length-sorted e2e adaptive] max_rank_peak_tokens=%s min_adaptive_floor=%s active_peak_safety_factor=%s max_response_len=%s shrink_not_required=true\n' \
    "$MAX_RANK_PEAK_TOKENS" "$MIN_ADAPTIVE_FLOOR" "$ACTIVE_PEAK_SAFETY_FACTOR" "$MAX_RESPONSE_LEN"
printf '[mode1 length-sorted e2e adaptive] ignore_tail_ties_at_response_cap=%s\n' \
    "$IGNORE_TAIL_TIES_AT_RESPONSE_CAP"
printf '[mode1 length-sorted e2e adaptive] length_ema_decay=%s history_dirs=%s\n' \
    "$LENGTH_EMA_DECAY" "${#BASELINE_DIR_ARRAY[@]}"
printf '[mode1 length-sorted e2e adaptive] plan_steps=%s dataset_fraction_for_oracle=%s\n' \
    "$PLAN_STEPS" "$DATASET_FRACTION_FOR_ORACLE"
printf '[mode1 length-sorted e2e adaptive] target_policy=%s fixed_topology_reuse=%s precreate_planned_floor_groups=%s cache_planned_floor_groups=%s\n' \
    "$VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY" \
    "$VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE" \
    "$VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS" \
    "$VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS"
printf '[mode1 length-sorted e2e adaptive] planned_floor_headroom_tokens=%s precreate_comm_cache=%s precreate_dispatch_warmup=%s\n' \
    "$VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS" \
    "$VLLM_ASCEND_MODE1_PARITY_PRECREATE_COMM_CACHE" \
    "$VLLM_ASCEND_MODE1_PARITY_PRECREATE_DISPATCH_WARMUP"
printf '[mode1 length-sorted e2e adaptive] prefill_planned_expert_slots=%s prefill_on_resize=%s\n' \
    "$VLLM_ASCEND_MODE1_PARITY_PREFILL_PLANNED_EXPERT_SLOTS" \
    "$VLLM_ASCEND_MODE1_PARITY_PREFILL_PLANNED_EXPERT_SLOTS_ON_RESIZE"
printf '[mode1 length-sorted e2e adaptive] planned_floor_headroom_by_floor=2:%s,4:%s,8:%s,16:%s\n' \
    "$planned_headroom_tokens_floor2" \
    "$planned_headroom_tokens_floor4" \
    "$planned_headroom_tokens_floor8" \
    "$planned_headroom_tokens_floor16"
printf '[mode1 length-sorted e2e] max_cross_step_repair_swaps=%s repair_candidate_limit=%s\n' \
    "$MAX_CROSS_STEP_REPAIR_SWAPS" "$REPAIR_CANDIDATE_LIMIT"

set +e
bash "$LAUNCHER" \
    data.train_files="$TRAIN_FILE" \
    data.val_files="$TEST_FILE" \
    data.train_batch_size="$TRAIN_BATCH_SIZE" \
    data.max_prompt_length="$MAX_PROMPT_LENGTH" \
    data.max_response_length="$MAX_RESPONSE_LENGTH" \
    data.shuffle=False \
    data.dataset_fraction=1.0 \
    actor_rollout_ref.model.path="$MODEL_PATH" \
    actor_rollout_ref.actor.megatron.dist_checkpointing_path="$DISTCP_PATH" \
    actor_rollout_ref.ref.megatron.dist_checkpointing_path="$DISTCP_PATH" \
    actor_rollout_ref.rollout.max_num_batched_tokens="$ROLLOUT_MAX_NUM_BATCHED_TOKENS" \
    actor_rollout_ref.rollout.max_num_seqs="$ROLLOUT_MAX_NUM_SEQS" \
    actor_rollout_ref.rollout.n="$ROLLOUT_N" \
    actor_rollout_ref.rollout.gpu_memory_utilization="$ROLLOUT_GPU_MEMORY_UTILIZATION" \
    actor_rollout_ref.rollout.shrink_aware.enable_shrink_aware_scheduling=true \
    actor_rollout_ref.rollout.shrink_aware.shrink_aware_mode=staged \
    actor_rollout_ref.rollout.shrink_aware.shrink_stages='[8,4]' \
    actor_rollout_ref.rollout.shrink_aware.survivor_selection_policy=manual \
    actor_rollout_ref.rollout.shrink_aware.intermediate_survivor_ranks='[8,9,10,11,12,13,14,15]' \
    actor_rollout_ref.rollout.shrink_aware.final_survivor_ranks='[12,13,14,15]' \
    actor_rollout_ref.rollout.shrink_aware.length_prediction_source=oracle_trace \
    actor_rollout_ref.rollout.shrink_aware.oracle_trace_path="$OPT_ORACLE" \
    actor_rollout_ref.rollout.shrink_aware.assignment_policy=optimized_rank_plan \
    actor_rollout_ref.rollout.shrink_aware.optimized_rank_plan_path="$OPT_RANK_PLAN" \
    actor_rollout_ref.rollout.shrink_aware.enable_shrink_aware_logging="$SHRINK_AWARE_LOGGING" \
    trainer.total_epochs="$TRAINER_TOTAL_EPOCHS" \
    "$@" 2>&1 | tee "$tee_log"
status=${PIPESTATUS[0]}
set -e

latest_log=$(ls -t "$OUTPUT_ROOT/$OUTPUT_SUBDIR"/logs/*.txt 2>/dev/null | head -1 || true)
if [[ -n "$latest_log" ]]; then
    summary_path="${latest_log%.txt}.comm_cache_summary.tsv"
    python3 "$PATCH_TREE/tools/summarize_mode1_comm_cache_log.py" \
        "$latest_log" > "$summary_path" || true
    printf '[mode1 length-sorted e2e] latest_log=%s\n' "$latest_log"
    printf '[mode1 length-sorted e2e] comm_cache_summary=%s\n' "$summary_path"
fi

exit "$status"
