#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'USAGE'
Usage:
  bash run_mode1_floor4_overlap4group_quiesce_destroy_test.sh

Purpose:
  Same partial-overlap floor=4 test as run_mode1_floor4_overlap4group_destroy_test.sh,
  but enables an experimental floor4 MC2 quiesce-before-destroy path.

Default pattern:
  - step 1 floor4 survivor tends to [12,13,14,15]
  - step 2 floor4 survivor tends to [10,11,12,13]
  - overlap is [12,13]

Useful overrides:
  BASELINE_TOTAL_TRAINING_STEPS=3
  VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_OP=all_reduce
  VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_SLEEP_MS=0
  VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_ASYNC_TRIM_DESTROYED_PG_REF=1
  VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_DESTROYED_PG_REF_LIMIT=1
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

export BASELINE_TOTAL_TRAINING_STEPS="${BASELINE_TOTAL_TRAINING_STEPS:-3}"
export VERL_ELASTIC_TAIL_VALIDATE_ROTATE_BUCKETS="${VERL_ELASTIC_TAIL_VALIDATE_ROTATE_BUCKETS:-1}"
export VERL_ELASTIC_TAIL_VALIDATE_ROTATE_MODES="${VERL_ELASTIC_TAIL_VALIDATE_ROTATE_MODES:-tail,shift2}"

# Keep the hot-path destroy visible, but force a small subgroup drain first.
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE="${VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE:-0}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_FLOOR4_MC2_DEVICE_PG_DESTROY="${VLLM_ASCEND_MODE1_PARITY_DEFER_FLOOR4_MC2_DEVICE_PG_DESTROY:-0}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_BEFORE_DESTROY="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_BEFORE_DESTROY:-1}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_CPU_BARRIER="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_CPU_BARRIER:-1}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_PRE_SYNC="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_PRE_SYNC:-1}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_POST_SYNC="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_POST_SYNC:-1}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_OP="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_OP:-all_reduce}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_SLEEP_MS="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_SLEEP_MS:-0}"
# Keep the next run close to the real hot path. Verbose lifecycle/cache-hit
# logs can back-pressure Ray stdout and show up as fake shrink RPC latency.
# Force them off for this diagnostic unless explicitly requested.
if [[ "${VLLM_ASCEND_MODE1_PARITY_VERBOSE_GROUP_LOGS:-0}" != "1" ]]; then
    export VLLM_ASCEND_ELASTIC_GROUP_LIFECYCLE_LOG=0
    export VLLM_ASCEND_ELASTIC_GROUP_CACHE_HIT_LOG=0
fi
export VLLM_ASCEND_ELASTIC_SLOW_TIMING_LOG_MS="${VLLM_ASCEND_ELASTIC_SLOW_TIMING_LOG_MS:-1000}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUARANTINE_TRACE="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUARANTINE_TRACE:-1}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_DROP_DEFERRED_CPU_PG="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_DROP_DEFERRED_CPU_PG:-1}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_ASYNC_TRIM_DESTROYED_PG_REF="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_ASYNC_TRIM_DESTROYED_PG_REF:-0}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_ASYNC_TRIM_DELAY_MS="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_ASYNC_TRIM_DELAY_MS:-0}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_DESTROYED_PG_REF_LIMIT="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_DESTROYED_PG_REF_LIMIT:--1}"

export RUN_ROOT="${RUN_ROOT:-$SCRIPT_DIR/mode1_floor4_overlap4group_quiesce_destroy_runs/$(date -u +%Y%m%dT%H%M%SZ)}"

printf '[mode1 floor4 overlap4 quiesce destroy test] modes=%s steps=%s run_root=%s op=%s async_trim=%s trim_limit=%s trim_delay_ms=%s\n' \
    "$VERL_ELASTIC_TAIL_VALIDATE_ROTATE_MODES" \
    "$BASELINE_TOTAL_TRAINING_STEPS" \
    "$RUN_ROOT" \
    "$VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_QUIESCE_OP" \
    "$VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_ASYNC_TRIM_DESTROYED_PG_REF" \
    "$VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_DESTROYED_PG_REF_LIMIT" \
    "$VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_ASYNC_TRIM_DELAY_MS"

exec bash "$SCRIPT_DIR/run_mode1_floor4_rotate4group_destroy_test.sh"
