#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'USAGE'
Usage:
  bash run_mode1_floor4_rotate4group_destroy_test.sh

Purpose:
  Diagnose whether the floor=4 HCCL/MC2 destroy latency only happens when the
  same 4-rank tail group is reused across steps, or whether repeated creation
  of different 4-rank groups also triggers it.

Behavior:
  - floor=4, mode=1, threshold-controlled rollout.
  - Step/rollout bucket order alternates tail/head by default:
      step 1 floor4 survivor tends to [12,13,14,15]
      step 2 floor4 survivor tends to [0,1,2,3]
  - floor4 MC2 keep-cache is disabled so the test exercises hot-path destroy.

Useful overrides:
  BASELINE_TOTAL_TRAINING_STEPS=3
  VERL_ELASTIC_TAIL_VALIDATE_ROTATE_MODES=tail,head
  VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE=0
USAGE
}

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT="${REPO_ROOT:-$SCRIPT_DIR}"
PATCH_TREE="${PATCH_TREE:-$REPO_ROOT}"
LAUNCHER="$PATCH_TREE/internal/wj_train_grpo_qwen30b_a3b_16die_true_weight_eager.sh"

cd "$PATCH_TREE"

stamp=$(date -u +%Y%m%dT%H%M%SZ)
run_root="${RUN_ROOT:-$REPO_ROOT/mode1_floor4_rotate4group_destroy_runs/$stamp}"
mkdir -p "$run_root"
tee_log="$run_root/launcher.log"

export VLLM_ASCEND_ELASTIC_EXECUTION_MODE=1
export VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE=4
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS:-288000}"

# This test intentionally disables the workaround so HCCL destroy behavior is visible.
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE="${VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE:-0}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_KINDS="${VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_KINDS:-mc2}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_FLOOR4_MC2_DEVICE_PG_DESTROY="${VLLM_ASCEND_MODE1_PARITY_DEFER_FLOOR4_MC2_DEVICE_PG_DESTROY:-0}"
export VLLM_ASCEND_ELASTIC_GROUP_CACHE_HIT_LOG="${VLLM_ASCEND_ELASTIC_GROUP_CACHE_HIT_LOG:-0}"
export VLLM_ASCEND_ELASTIC_GROUP_LIFECYCLE_LOG="${VLLM_ASCEND_ELASTIC_GROUP_LIFECYCLE_LOG:-0}"
export VLLM_ASCEND_ELASTIC_SLOW_TIMING_LOG_MS="${VLLM_ASCEND_ELASTIC_SLOW_TIMING_LOG_MS:-${VLLM_ASCEND_ELASTIC_SLOW_TIMING_LOG_THRESHOLD_MS:-1000}}"
export VLLM_ASCEND_ELASTIC_SLOW_TIMING_LOG_THRESHOLD_MS="$VLLM_ASCEND_ELASTIC_SLOW_TIMING_LOG_MS"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_ASYNC_TRIM_DESTROYED_PG_REF="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_ASYNC_TRIM_DESTROYED_PG_REF:-0}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_ASYNC_TRIM_DELAY_MS="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_ASYNC_TRIM_DELAY_MS:-0}"
export VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_DESTROYED_PG_REF_LIMIT="${VLLM_ASCEND_MODE1_PARITY_FLOOR4_MC2_DESTROYED_PG_REF_LIMIT:--1}"

export VLLM_ASCEND_CUSTOM_MODE1_DEBUG=0
export VLLM_ASCEND_CUSTOM_MODE1_TIMING_EVENTS=0
export VLLM_ASCEND_CUSTOM_MODE1_KV_DIAG=0
export VLLM_ASCEND_MODE1_BATCH_DIRECT_NPU_IMPORT="${VLLM_ASCEND_MODE1_BATCH_DIRECT_NPU_IMPORT:-1}"
export VLLM_ASCEND_MODE1_ALLOW_SCALAR_DIRECT_NPU_IMPORT="${VLLM_ASCEND_MODE1_ALLOW_SCALAR_DIRECT_NPU_IMPORT:-0}"
export VLLM_ASCEND_MODE1_ALLOW_BATCH_INDEX_SELECT_EXPORT="${VLLM_ASCEND_MODE1_ALLOW_BATCH_INDEX_SELECT_EXPORT:-0}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_BATCH_EXPERTS="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_BATCH_EXPERTS:-8}"
export VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC="${VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC:-1}"

export MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-896}"
export MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-1024}"
export ROLLOUT_MAX_NUM_BATCHED_TOKENS="${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-$((MAX_PROMPT_LENGTH + MAX_RESPONSE_LENGTH))}"
export ROLLOUT_MAX_NUM_SEQS="${ROLLOUT_MAX_NUM_SEQS:-32}"
export ROLLOUT_N="${ROLLOUT_N:-16}"
export TRAINER_TOTAL_EPOCHS="${TRAINER_TOTAL_EPOCHS:-1}"
export BASELINE_TOTAL_TRAINING_STEPS="${BASELINE_TOTAL_TRAINING_STEPS:-3}"
export DATASET_FRACTION="${DATASET_FRACTION:-0.005}"
export VERL_ELASTIC_TAIL_VALIDATE_LEVEL_TOKENS="${VERL_ELASTIC_TAIL_VALIDATE_LEVEL_TOKENS:-256,512,640,768,896}"
export VERL_ELASTIC_TAIL_VALIDATE_ROTATE_BUCKETS="${VERL_ELASTIC_TAIL_VALIDATE_ROTATE_BUCKETS:-1}"
export VERL_ELASTIC_TAIL_VALIDATE_ROTATE_MODES="${VERL_ELASTIC_TAIL_VALIDATE_ROTATE_MODES:-tail,head}"

export PRINT_MEMORY="${PRINT_MEMORY:-1}"
export VLLM_ASCEND_FULL_REDUNDANCY_EXPERIMENT_LOG="${VLLM_ASCEND_FULL_REDUNDANCY_EXPERIMENT_LOG:-1}"
export VLLM_ASCEND_MODE3_TRANSFER_LOG=0
export VLLM_ASCEND_MODE3_TRANSFER_PLAN_LOG=0
export VLLM_ASCEND_MODE3_TIMING_LOG=0
export VLLM_ASCEND_MODE3_TIMING_SYNC=0
export VLLM_ASCEND_STAGE_DECODE_PROFILE_MARKERS=0
export VLLM_ASCEND_BUCKET_OP_PROFILE=0
export VLLM_ASCEND_BUCKET_OP_PROFILE_BY_STAGE=0
export VLLM_ASCEND_BUCKET_OP_PROFILE_CONTENTS=""
export VLLM_ASCEND_DUMMY_WASTE_TIMING=0
export VLLM_ASCEND_DUMMY_WASTE_TIMING_SYNC=0
export VLLM_ASCEND_DUMMY_WASTE_TIMING_PROFILE=0
export VLLM_ASCEND_DUMMY_WASTE_PROFILE_MARKERS=0

export HCCL_IF_BASE_PORT="${HCCL_IF_BASE_PORT:-47241}"
export MASTER_PORT="${MASTER_PORT:-26240}"
export VERL_HCCL_IF_BASE_PORT_START="${VERL_HCCL_IF_BASE_PORT_START:-47241}"
export HOME="$run_root"
export CONFIG_DIR="$PATCH_TREE/verl/trainer/config"
export PYTHONPATH="$PATCH_TREE${PYTHONPATH:+:$PYTHONPATH}"

printf '[mode1 floor4 rotate4 destroy test] runtime_cwd=%s\n' "$PATCH_TREE"
printf '[mode1 floor4 rotate4 destroy test] run_root=%s\n' "$run_root"
printf '[mode1 floor4 rotate4 destroy test] launcher=%s\n' "$LAUNCHER"
printf '[mode1 floor4 rotate4 destroy test] steps=%s tail_validate=%s rotate=%s modes=%s keep_floor4_cache=%s keep_kinds=%s\n' \
    "$BASELINE_TOTAL_TRAINING_STEPS" \
    "$VERL_ELASTIC_TAIL_VALIDATE_LEVEL_TOKENS" \
    "$VERL_ELASTIC_TAIL_VALIDATE_ROTATE_BUCKETS" \
    "$VERL_ELASTIC_TAIL_VALIDATE_ROTATE_MODES" \
    "$VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE" \
    "$VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_KINDS"
printf '[mode1 floor4 rotate4 destroy test] tee_log=%s\n' "$tee_log"

bash "$LAUNCHER" \
    data.dataset_fraction="$DATASET_FRACTION" \
    trainer.total_training_steps="$BASELINE_TOTAL_TRAINING_STEPS" \
    2>&1 | tee "$tee_log"
