#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Full-length dynamic natural-policy validation with floor2 enabled.
#
# This reuses the existing mode0 probe from the floor4 natural tailguard run for
# length history, so it only executes two mode1 epochs: epoch_001 and epoch_002.
# If DYNAMIC_INITIAL_RESUME_CKPT is not provided, epoch_001 starts from the base
# model and epoch_002 resumes from epoch_001.  The floor2 cap is the largest
# no-trim value verified by the threshold-controlled floor2 sweep.

BASELINE_EPOCH0="${DYNAMIC_INITIAL_BASELINE_DIR:-$SCRIPT_DIR/mode1_dynamic_length_aware_adaptive_floor4_natural_tailguard_full3/epoch_000_mode0_probe}"

if [[ ! -d "$BASELINE_EPOCH0/rollout_data" ]]; then
    echo "missing reusable epoch0 rollout data: $BASELINE_EPOCH0/rollout_data" >&2
    exit 2
fi

export VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY=natural
export VLLM_ASCEND_SHRINK_AWARE_STAGES="${VLLM_ASCEND_SHRINK_AWARE_STAGES:-8,4,2}"
export VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE="${VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE:-2}"
export MIN_ADAPTIVE_FLOOR="${MIN_ADAPTIVE_FLOOR:-2}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2:-131072}"
export VLLM_ASCEND_MODE1_RELOAD_TRIM_ALLOCATOR="${VLLM_ASCEND_MODE1_RELOAD_TRIM_ALLOCATOR:-0}"
export VLLM_ASCEND_MODE1_RELOAD_SYNC_ON_TRIM="${VLLM_ASCEND_MODE1_RELOAD_SYNC_ON_TRIM:-0}"
export VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG="${VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG:-0}"
export VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG_ALL="${VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG_ALL:-0}"
export VLLM_ASCEND_MODE1_CLEAR_STALE_PARAM_DICTS_AFTER_OLD_KV="${VLLM_ASCEND_MODE1_CLEAR_STALE_PARAM_DICTS_AFTER_OLD_KV:-1}"
export FLOOR_KV_CAPS="${FLOOR_KV_CAPS:-2:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2},4:280576,8:315648,16:380800}"

# Upward transitions such as floor2->floor4 release old KV before floor prepare,
# then compact MoE state.  Avoid repeated allocator trims inside that compact
# loop; the later resize memory query still performs one trim/sync before
# allocating the new KV cache.
export VLLM_ASCEND_MODE1_CLEAR_OLD_KV_BEFORE_UPWARD_FLOOR_PREPARE="${VLLM_ASCEND_MODE1_CLEAR_OLD_KV_BEFORE_UPWARD_FLOOR_PREPARE:-1}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_BEFORE_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_EMPTY_CACHE_BEFORE_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_DURING_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_EMPTY_CACHE_DURING_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_AFTER_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_EMPTY_CACHE_AFTER_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_BETWEEN_COMPACT_TENSORS="${VLLM_ASCEND_MODE1_EMPTY_CACHE_BETWEEN_COMPACT_TENSORS:-0}"
export VLLM_ASCEND_MODE1_UPWARD_CLEANUP_FINAL_EMPTY_CACHE="${VLLM_ASCEND_MODE1_UPWARD_CLEANUP_FINAL_EMPTY_CACHE:-0}"
export VLLM_ASCEND_MODE1_UPWARD_COMPACT_RELEASE_EVERY_LAYERS="${VLLM_ASCEND_MODE1_UPWARD_COMPACT_RELEASE_EVERY_LAYERS:-48}"

# Natural should not retain planned floor communicators.  Keep these explicit so
# the floor2 test does not accidentally inherit planner-residency settings.
export VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_COMM_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_DISPATCH_WARMUP=0
export VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE=0

echo "[dynamic floor2 natural] reusable_epoch0=$BASELINE_EPOCH0"
echo "[dynamic floor2 natural] initial_resume_ckpt=${DYNAMIC_INITIAL_RESUME_CKPT:-<none>}"
echo "[dynamic floor2 natural] stages=$VLLM_ASCEND_SHRINK_AWARE_STAGES min_floor=$MIN_ADAPTIVE_FLOOR floor_caps=$FLOOR_KV_CAPS"
echo "[dynamic floor2 natural] reload_trim=$VLLM_ASCEND_MODE1_RELOAD_TRIM_ALLOCATOR sync_on_trim=$VLLM_ASCEND_MODE1_RELOAD_SYNC_ON_TRIM"
echo "[dynamic floor2 natural] clear_stale_param_dicts_after_old_kv=$VLLM_ASCEND_MODE1_CLEAR_STALE_PARAM_DICTS_AFTER_OLD_KV"
echo "[dynamic floor2 natural] upward_cleanup_fastpath=old_kv_before_prepare:$VLLM_ASCEND_MODE1_CLEAR_OLD_KV_BEFORE_UPWARD_FLOOR_PREPARE compact_empty_between:$VLLM_ASCEND_MODE1_EMPTY_CACHE_BETWEEN_COMPACT_TENSORS final_empty:$VLLM_ASCEND_MODE1_UPWARD_CLEANUP_FINAL_EMPTY_CACHE"

DYNAMIC_RUN_NAME="${DYNAMIC_RUN_NAME:-mode1_dynamic_length_aware_adaptive_floor2_natural_tailguard_reuse_epoch0_2epoch}" \
DYNAMIC_TOTAL_EPOCHS="${DYNAMIC_TOTAL_EPOCHS:-3}" \
DYNAMIC_START_EPOCH="${DYNAMIC_START_EPOCH:-1}" \
DYNAMIC_SHRINK_POLICY=natural \
DYNAMIC_SKIP_MODE0_PROBE=1 \
DYNAMIC_INITIAL_BASELINE_DIR="$BASELINE_EPOCH0" \
DYNAMIC_ENABLE_CKPT_CHAIN="${DYNAMIC_ENABLE_CKPT_CHAIN:-1}" \
DYNAMIC_PLAN_STEPS="${DYNAMIC_PLAN_STEPS:-5}" \
DYNAMIC_TRAIN_STEPS="${DYNAMIC_TRAIN_STEPS:-5}" \
DYNAMIC_ENABLE_THRESHOLD_CONTROL=0 \
DYNAMIC_SHORT_STEP_CAP_ENABLE="${DYNAMIC_SHORT_STEP_CAP_ENABLE:-1}" \
DYNAMIC_SHORT_STEP_EXIT_THRESHOLD="${DYNAMIC_SHORT_STEP_EXIT_THRESHOLD:-4096}" \
DYNAMIC_SHORT_STEP_CAP_TOKENS="${DYNAMIC_SHORT_STEP_CAP_TOKENS:-4096}" \
DYNAMIC_SHORT_STEP_CAP_FLOORS="${DYNAMIC_SHORT_STEP_CAP_FLOORS:-2,4}" \
DYNAMIC_TAIL_GUARD_RATIO_QUANTILE="${DYNAMIC_TAIL_GUARD_RATIO_QUANTILE:-0.95}" \
DYNAMIC_TAIL_GUARD_RATIO_WINDOW="${DYNAMIC_TAIL_GUARD_RATIO_WINDOW:-3}" \
DYNAMIC_TAIL_GUARD_DEFAULT_RATIO="${DYNAMIC_TAIL_GUARD_DEFAULT_RATIO:-1.20}" \
DYNAMIC_TAIL_GUARD_MIN_CAP="${DYNAMIC_TAIL_GUARD_MIN_CAP:-4096}" \
DYNAMIC_TAIL_GUARD_ROUND_TO="${DYNAMIC_TAIL_GUARD_ROUND_TO:-512}" \
DYNAMIC_IGNORE_TAIL_TIES_AT_RESPONSE_CAP="${DYNAMIC_IGNORE_TAIL_TIES_AT_RESPONSE_CAP:-0}" \
DYNAMIC_RESET_PROGRESS_AFTER_RESUME="${DYNAMIC_RESET_PROGRESS_AFTER_RESUME:-1}" \
"$SCRIPT_DIR/run_mode1_dynamic_length_aware_adaptive_floor4_epochs.sh" "$@"
