#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd "$(dirname "$0")" && pwd)
cd "${script_dir}"

# Full mode=0 baseline:
# - no elastic shrink
# - no shrink-aware / length-aware regroup
# - no response-length thresholding
# - 3 epochs, 5 rollout steps per epoch

OUTPUT_ROOT="${OUTPUT_ROOT:-${script_dir}}"
OUTPUT_SUBDIR="${OUTPUT_SUBDIR:-mode0_no_shrink_baseline_full3}"
RECORD_DIR="${OUTPUT_ROOT}/${OUTPUT_SUBDIR}"

echo "[mode0 full3] output=${RECORD_DIR}"
echo "[mode0 full3] epochs=3 steps_per_epoch=5 total_steps=15"
echo "[mode0 full3] shrink=off regroup=off threshold=off max_response_length=16384"

exec env \
    -u VERL_ELASTIC_TAIL_VALIDATE_LEVEL_TOKENS \
    -u VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY \
    -u VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS \
    -u VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2 \
    -u VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4 \
    -u VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8 \
    -u VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS \
    -u VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS \
    -u VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS \
    -u VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE \
    -u VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR_GROUP_KV_HEADROOM_TOKENS \
    -u VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR8_GROUP_KV_HEADROOM_TOKENS \
    -u VLLM_ASCEND_MODE1_PARITY_PLANNED_FLOOR16_GROUP_KV_HEADROOM_TOKENS \
    OUTPUT_ROOT="${OUTPUT_ROOT}" \
    OUTPUT_SUBDIR="${OUTPUT_SUBDIR}" \
    RECORD_DIR="${RECORD_DIR}" \
    TRAINER_TOTAL_EPOCHS=3 \
    DATASET_FRACTION=0.005 \
    DATA_SHUFFLE=False \
    TRAIN_BATCH_SIZE=32 \
    MAX_PROMPT_LENGTH=1024 \
    MAX_RESPONSE_LENGTH=16384 \
    MAX_RESPONSE_LEN=16384 \
    ROLLOUT_MAX_NUM_BATCHED_TOKENS=17408 \
    ROLLOUT_MAX_NUM_SEQS=32 \
    ROLLOUT_N=16 \
    MODE0_SAVE_ROLLOUT_ARTIFACTS=1 \
    SAVE_CKPT_ENABLE="${SAVE_CKPT_ENABLE:-1}" \
    TRAINER_SAVE_FREQ="${TRAINER_SAVE_FREQ:-15}" \
    MAX_ACTOR_CKPT_TO_KEEP="${MAX_ACTOR_CKPT_TO_KEEP:-1}" \
    MAX_CRITIC_CKPT_TO_KEEP="${MAX_CRITIC_CKPT_TO_KEEP:-1}" \
    VLLM_ASCEND_ENABLE_ELASTIC_PARALLEL_SHRINK=0 \
    VLLM_ASCEND_ELASTIC_EXECUTION_MODE=0 \
    VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE=16 \
    VLLM_ASCEND_SHRINK_AWARE_ENABLE=0 \
    VLLM_EPOCH_LENGTH_REGROUP_ENABLE=0 \
    VLLM_ROLLOUT_EARLY_STOP_ENABLE=0 \
    ./run_mode0_no_shrink_baseline.sh \
    trainer.total_training_steps=15 \
    "$@"
