#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

# Short natural-policy probe for the floor2 -> floor4 KV recovery path.
#
# Shape:
#   step1 selected_floor=2, short caps by rank bucket: 8*8,16*4,32*2,64*2
#   step2 selected_floor=2, same caps
#   step3 selected_floor=4, short caps by rank bucket: 8*8,16*4,32*4
#
# The goal is not rollout quality.  It is to quickly check whether the KV cache
# planning before step3 can return to the normal natural floor4 budget.

BASELINE_EPOCH0="${DYNAMIC_INITIAL_BASELINE_DIR:-$SCRIPT_DIR/mode1_dynamic_length_aware_adaptive_floor4_natural_tailguard_full3/epoch_000_mode0_probe}"

if [[ ! -d "$BASELINE_EPOCH0/rollout_data" ]]; then
    echo "missing reusable epoch0 rollout data: $BASELINE_EPOCH0/rollout_data" >&2
    exit 2
fi

export DYNAMIC_RUN_NAME="${DYNAMIC_RUN_NAME:-mode1_dynamic_floor2_to_floor4_kv_probe}"
export DYNAMIC_TOTAL_EPOCHS=2
export DYNAMIC_START_EPOCH=1
export DYNAMIC_SHRINK_POLICY=natural
export DYNAMIC_SKIP_MODE0_PROBE=1
export DYNAMIC_INITIAL_BASELINE_DIR="$BASELINE_EPOCH0"
export DYNAMIC_ENABLE_CKPT_CHAIN=0
export DYNAMIC_PLAN_STEPS=3
export DYNAMIC_TRAIN_STEPS=3
export DYNAMIC_DATASET_FRACTION="${DYNAMIC_DATASET_FRACTION:-0.005}"

export VLLM_ASCEND_SHRINK_AWARE_TARGET_POLICY=natural
export VLLM_ASCEND_SHRINK_AWARE_STAGES=8,4,2
export VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE=2
export MIN_ADAPTIVE_FLOOR=2
export DYNAMIC_FORCE_SELECTED_FLOORS="${DYNAMIC_FORCE_SELECTED_FLOORS:-2,2,4}"
export MAX_CROSS_STEP_REPAIR_SWAPS=0
export IGNORE_TAIL_TIES_AT_RESPONSE_CAP=1

export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2:-131072}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4:-280576}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8:-315648}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR16="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR16:-380800}"
export FLOOR_KV_CAPS="${FLOOR_KV_CAPS:-2:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR2},4:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4},8:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8},16:${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR16}}"

export DYNAMIC_ENABLE_THRESHOLD_CONTROL=0
# Tail validate caps are applied to the repeated-halving rank buckets [8, 4, 2, 1, 1].
# Steps 1-2: 8*8, 16*4, 32*2, 64*2. Step 3: 8*8, 16*4, 32*4.
# Keep the synthetic decode tail identical across forced 2,2,4 steps so
# timing differences reflect floor transitions rather than different lengths.
export DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP="${DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP:-8,16,32,64,64;8,16,32,64,64;8,16,32,64,64}"
export DYNAMIC_FULL_MAX_PROMPT_LENGTH="${DYNAMIC_FULL_MAX_PROMPT_LENGTH:-1024}"
export DYNAMIC_FULL_MAX_RESPONSE_LENGTH="${DYNAMIC_FULL_MAX_RESPONSE_LENGTH:-1024}"
export DYNAMIC_FULL_MAX_RESPONSE_LEN="${DYNAMIC_FULL_MAX_RESPONSE_LEN:-1024}"
export DYNAMIC_FULL_MAX_NUM_BATCHED_TOKENS="${DYNAMIC_FULL_MAX_NUM_BATCHED_TOKENS:-2048}"

export DYNAMIC_SHORT_STEP_CAP_ENABLE=0
export DYNAMIC_TAIL_GUARD_MIN_CAP="${DYNAMIC_TAIL_GUARD_MIN_CAP:-1024}"
export DYNAMIC_TAIL_GUARD_ROUND_TO="${DYNAMIC_TAIL_GUARD_ROUND_TO:-64}"

# Natural mode should not retain planned floor communicators.
export VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_PLANNED_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_CACHE_PLANNED_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_COMM_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_PRECREATE_DISPATCH_WARMUP=0
export VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS=0
export VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE=0
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY=0
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_FULL_RESTORE=0
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_PRE_REBUILD=0
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_STASH=0
export VLLM_ASCEND_MODE1_PARITY_DEFER_DESTROY_FLOOR_GROUP_SIZES="${VLLM_ASCEND_MODE1_PARITY_DEFER_DESTROY_FLOOR_GROUP_SIZES:-1,2,4,8}"
export VLLM_ASCEND_MODE1_PARITY_PRESERVE_DEVICE_PG_ON_FULL_RESTORE=0
export VLLM_ASCEND_MODE1_PARITY_PRESERVE_GROUP_REFS_ON_FULL_RESTORE=0
export VLLM_ASCEND_MODE1_PARITY_SKIP_CLEANUP_ON_PRESERVED_FULL_RESTORE=0

# Keep only the useful memory/KV timeline logs; avoid the very hot MC2 logs.
export VLLM_ASCEND_MODE1_RELOAD_TRIM_ALLOCATOR=0
export VLLM_ASCEND_MODE1_RELOAD_SYNC_ON_TRIM=0
export VLLM_ASCEND_MODE1_CLEAR_STALE_PARAM_DICTS_AFTER_OLD_KV=1
export VLLM_ASCEND_MODE1_AGGRESSIVE_RELEASE_OLD_PARAM_STORAGE="${VLLM_ASCEND_MODE1_AGGRESSIVE_RELEASE_OLD_PARAM_STORAGE:-1}"
export VLLM_ASCEND_MODE1_OFFLOAD_LOADED_WEIGHTS_AFTER_FULL_RESTORE="${VLLM_ASCEND_MODE1_OFFLOAD_LOADED_WEIGHTS_AFTER_FULL_RESTORE:-1}"
export VLLM_ASCEND_MODE1_OFFLOAD_CANONICAL_LOADED_WEIGHTS_AFTER_FULL_RESTORE="${VLLM_ASCEND_MODE1_OFFLOAD_CANONICAL_LOADED_WEIGHTS_AFTER_FULL_RESTORE:-0}"
export VLLM_ASCEND_MODE1_SYNC_AFTER_FULL_RESTORE_WEIGHT_OFFLOAD="${VLLM_ASCEND_MODE1_SYNC_AFTER_FULL_RESTORE_WEIGHT_OFFLOAD:-1}"
# Old KV is released before upward floor prepare, so avoid repeated allocator
# cache trims inside the per-layer compact loop.  The resize memory query later
# still performs one empty/sync before planning the new KV cache.
export VLLM_ASCEND_MODE1_EMPTY_CACHE_AFTER_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_EMPTY_CACHE_AFTER_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_BEFORE_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_EMPTY_CACHE_BEFORE_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_CLEAR_STALE_PARAMS_DURING_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_CLEAR_STALE_PARAMS_DURING_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_DURING_UPWARD_COMPACT="${VLLM_ASCEND_MODE1_EMPTY_CACHE_DURING_UPWARD_COMPACT:-0}"
export VLLM_ASCEND_MODE1_UPWARD_COMPACT_RELEASE_EVERY_LAYERS="${VLLM_ASCEND_MODE1_UPWARD_COMPACT_RELEASE_EVERY_LAYERS:-48}"
export VLLM_ASCEND_MODE1_EMPTY_CACHE_BETWEEN_COMPACT_TENSORS="${VLLM_ASCEND_MODE1_EMPTY_CACHE_BETWEEN_COMPACT_TENSORS:-0}"
export VLLM_ASCEND_MODE1_UPWARD_CLEANUP_FINAL_EMPTY_CACHE="${VLLM_ASCEND_MODE1_UPWARD_CLEANUP_FINAL_EMPTY_CACHE:-0}"
export VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG=0
export VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG_ALL=0
export VLLM_ASCEND_CUSTOM_MODE1_ROLLOUT_RELOAD_DIAG=0
export VLLM_ASCEND_MODE1_FULLWORLD_RESTORE_DIAG="${VLLM_ASCEND_MODE1_FULLWORLD_RESTORE_DIAG:-1}"
export VLLM_ASCEND_MODE1_FULLWORLD_RESTORE_DIAG_DISPATCH_BUDGET="${VLLM_ASCEND_MODE1_FULLWORLD_RESTORE_DIAG_DISPATCH_BUDGET:-16}"
export VLLM_ASCEND_MODE1_MC2_RUNTIME_DIAG_SYNC="${VLLM_ASCEND_MODE1_MC2_RUNTIME_DIAG_SYNC:-1}"
export VLLM_ASCEND_MODE1_MC2_RUNTIME_DIAG_SYNC_ALL_LAYERS="${VLLM_ASCEND_MODE1_MC2_RUNTIME_DIAG_SYNC_ALL_LAYERS:-1}"
export VLLM_ASCEND_MODE1_MC2_RUNTIME_DIAG_SYNC_LOG_DONE="${VLLM_ASCEND_MODE1_MC2_RUNTIME_DIAG_SYNC_LOG_DONE:-0}"
export VLLM_ASCEND_MODE1_STEP_TIMELINE_LOG="${VLLM_ASCEND_MODE1_STEP_TIMELINE_LOG:-1}"
export VLLM_ASCEND_MODE1_RPC_PRE_NPU_SYNC="${VLLM_ASCEND_MODE1_RPC_PRE_NPU_SYNC:-1}"
export VLLM_ASCEND_MODE1_RESTORE_POST_NPU_SYNC="${VLLM_ASCEND_MODE1_RESTORE_POST_NPU_SYNC:-1}"
export VLLM_ASCEND_MODE1_RPC_PRE_BARRIER="${VLLM_ASCEND_MODE1_RPC_PRE_BARRIER:-0}"
export VLLM_ASCEND_MODE1_PAYLOAD_GATHER_TRACE="${VLLM_ASCEND_MODE1_PAYLOAD_GATHER_TRACE:-1}"
export VLLM_ASCEND_MODE1_PAYLOAD_GATHER_TRACE_MODULES="${VLLM_ASCEND_MODE1_PAYLOAD_GATHER_TRACE_MODULES:-8}"
export VLLM_ASCEND_MODE1_PAYLOAD_PLANNING_DIAG="${VLLM_ASCEND_MODE1_PAYLOAD_PLANNING_DIAG:-1}"

export TRAINER_SAVE_FREQ=999999
export SAVE_CKPT_ENABLE=0

echo "[floor2->floor4 kv probe] baseline=$BASELINE_EPOCH0"
echo "[floor2->floor4 kv probe] run_name=$DYNAMIC_RUN_NAME floors=$DYNAMIC_FORCE_SELECTED_FLOORS caps=$FLOOR_KV_CAPS"
echo "[floor2->floor4 kv probe] runtime_caps_by_step=$DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS_BY_STEP"

exec "$SCRIPT_DIR/run_mode1_dynamic_length_aware_adaptive_floor4_epochs.sh" "$@"
