#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
cd "$SCRIPT_DIR"

BASE_RUN_DIR="${BASE_RUN_DIR:-$SCRIPT_DIR/mode1_dynamic_length_aware_adaptive_floor4_natural_full3}"
BASELINE_HISTORY="${BASELINE_HISTORY:-$BASE_RUN_DIR/epoch_000_mode0_probe,$BASE_RUN_DIR/epoch_001_mode1_natural}"
RESUME_CKPT="${RESUME_CKPT:-$BASE_RUN_DIR/epoch_001_mode1_natural/checkpoints/qwen3moe_for_eagle3/global_step_5}"
QUICK_RUNTIME_ONLY="${QUICK_RUNTIME_ONLY:-1}"
QUICK_TAIL_VALIDATE_LEVEL_TOKENS="${QUICK_TAIL_VALIDATE_LEVEL_TOKENS:-256,512,640,768,896}"

if [[ ! -d "$RESUME_CKPT" ]]; then
    echo "missing resume checkpoint: $RESUME_CKPT" >&2
    exit 2
fi

for history_dir in ${BASELINE_HISTORY//,/ }; do
    if [[ ! -d "$history_dir/rollout_data" ]]; then
        echo "missing rollout history: $history_dir/rollout_data" >&2
        exit 2
    fi
done

if [[ "$QUICK_RUNTIME_ONLY" == "1" ]]; then
    export DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS="$QUICK_TAIL_VALIDATE_LEVEL_TOKENS"
else
    unset DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS
fi

env -u MAX_RESPONSE_LENGTH \
    -u MAX_RESPONSE_LEN \
    -u ROLLOUT_MAX_NUM_BATCHED_TOKENS \
DYNAMIC_RUN_NAME="${DYNAMIC_RUN_NAME:-mode1_dynamic_length_aware_adaptive_floor4_natural_floor8cap377344_quick}" \
DYNAMIC_TOTAL_EPOCHS=2 \
DYNAMIC_SHRINK_POLICY=natural \
DYNAMIC_SKIP_MODE0_PROBE=1 \
DYNAMIC_INITIAL_BASELINE_DIR="$BASELINE_HISTORY" \
DYNAMIC_INITIAL_RESUME_CKPT="$RESUME_CKPT" \
DYNAMIC_ENABLE_CKPT_CHAIN=1 \
DYNAMIC_PLAN_STEPS=5 \
DYNAMIC_TRAIN_STEPS="${DYNAMIC_TRAIN_STEPS:-5}" \
DYNAMIC_ENABLE_THRESHOLD_CONTROL=0 \
DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS="${DYNAMIC_RUNTIME_TAIL_VALIDATE_LEVEL_TOKENS:-}" \
DYNAMIC_IGNORE_TAIL_TIES_AT_RESPONSE_CAP=0 \
DYNAMIC_RESET_PROGRESS_AFTER_RESUME=1 \
DYNAMIC_NATURAL_FLOOR8_RUNTIME_CAP=377344 \
VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR8=377344 \
VLLM_ASCEND_MODE1_NATURAL_PRUNE_RUNTIME_ON_KV_RESIZE=1 \
VLLM_ASCEND_MODE1_NATURAL_FORCE_DESTROY_FLOOR_GROUPS_ON_KV_RESIZE=1 \
VLLM_ASCEND_MODE1_COMM_CACHE_STATE_LOG=1 \
TRAINER_SAVE_FREQ="${TRAINER_SAVE_FREQ:-5}" \
MAX_ACTOR_CKPT_TO_KEEP="${MAX_ACTOR_CKPT_TO_KEEP:-1}" \
./run_mode1_dynamic_length_aware_adaptive_floor4_epochs.sh "$@"
