#!/usr/bin/env bash
set -euo pipefail

usage() {
    cat <<'EOF'
Usage:
  ./run_mode1_local_shrinkaware_521_oracle.sh [extra hydra args...]

Mode=1 floor=4 shrink-aware 5:2:1 oracle experiment:
  1. Reads the completed baseline rollout lengths from
     mode1_baseline_random_batch_floor4/{rollout_data,rollout_length}.
  2. Aggregates every prompt's 16 responses into one mean response length.
  3. Uses those known lengths to sort each 32-prompt batch by short->long.
  4. Applies the fixed 5:2:1 bucket/rank assignment:
       bucket1 shortest 20 prompts:
         ranks 0-7 get 2 prompts each; ranks 8-11 get 1 prompt each
       bucket2 middle 8 prompts:
         ranks 12-15 get 2 prompts each
       bucket3 longest 4 prompts:
         ranks 8-11 get 1 prompt each
EOF
}

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT="${REPO_ROOT:-$SCRIPT_DIR}"
PATCH_TREE="${PATCH_TREE:-$REPO_ROOT}"
LAUNCHER="${LOCAL_TEST_LAUNCHER:-$PATCH_TREE/internal/wj_train_grpo_qwen30b_a3b_16die_true_weight_regroup.sh}"

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
    usage
    exit 0
fi

MODEL_PATH="${MODEL_PATH:-/data/Qwen3-30B-A3B}"
DISTCP_PATH="${DISTCP_PATH:-/data/Qwen3-30B-A3B_megatron}"
TRAIN_FILE="${TRAIN_FILE:-/data/deepscaler/train.parquet}"
TEST_FILE="${TEST_FILE:-/data/deepscaler/test.parquet}"
BASELINE_DIR="${BASELINE_DIR:-$REPO_ROOT/mode1_baseline_random_batch_floor4}"

if [[ "${CHECK_LOCAL_INPUTS:-1}" == "1" ]]; then
    for required_path in "$MODEL_PATH" "$DISTCP_PATH" "$TRAIN_FILE" "$TEST_FILE" "$BASELINE_DIR"; do
        if [[ ! -e "$required_path" ]]; then
            echo "missing local input path: $required_path" >&2
            exit 2
        fi
    done
fi

export VLLM_ASCEND_ENABLE_ELASTIC_PARALLEL_SHRINK=1
export VLLM_ASCEND_ELASTIC_EXECUTION_MODE=1
export VLLM_ASCEND_ELASTIC_MIN_COMPUTE_GROUP_SIZE=4
export VLLM_ASCEND_SHRINK_AWARE_ENABLE=1
export VLLM_ASCEND_REGISTER_CUSTOM_MODELS="${VLLM_ASCEND_REGISTER_CUSTOM_MODELS:-1}"
export VLLM_ASCEND_USE_NATIVE_QWEN3_MOE=0
export VLLM_ASCEND_SHRINK_AWARE_MODE=staged
export VLLM_ASCEND_SHRINK_AWARE_STAGES=8,4
export VLLM_ASCEND_SHRINK_AWARE_SURVIVOR_POLICY=manual
export VLLM_ASCEND_SHRINK_AWARE_INTERMEDIATE_RANKS=8,9,10,11,12,13,14,15
export VLLM_ASCEND_SHRINK_AWARE_FINAL_RANKS=8,9,10,11
export VLLM_EAGER_BASELINE_NO_RESAMPLE=0
export VLLM_EPOCH_LENGTH_REGROUP_ENABLE=0
export ROLLOUT_ENFORCE_EAGER="${ROLLOUT_ENFORCE_EAGER:-True}"
export VLLM_ROLLOUT_EARLY_STOP_ENABLE="${VLLM_ROLLOUT_EARLY_STOP_ENABLE:-0}"
export VERL_SIDECAR_ENABLE="${VERL_SIDECAR_ENABLE:-0}"
export VLLM_MOE_PATTERN_STATS=0
export VLLM_MOE_STATS=0
export VLLM_MOE_STATS_TIMING=0
export VLLM_ASCEND_NATIVE_MOE_TOPK_DEBUG=0

export VLLM_ASCEND_CUSTOM_MODE1_KV_MATERIALIZE_HEADROOM_BYTES="${VLLM_ASCEND_CUSTOM_MODE1_KV_MATERIALIZE_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_KV_CACHE_INIT_HEADROOM_BYTES="${VLLM_ASCEND_KV_CACHE_INIT_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_HEADROOM_BYTES="${VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_LOW_FLOOR_HEADROOM_BYTES="${VLLM_ASCEND_POST_SHRINK_MOE_DISPATCH_LOW_FLOOR_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_SHRINK_PREFILL_ALLTOALL_HEADROOM_BYTES="${VLLM_ASCEND_POST_SHRINK_PREFILL_ALLTOALL_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_RESTORE_DP_HEADROOM_BYTES="${VLLM_ASCEND_POST_RESTORE_DP_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_RESTORE_EP_HEADROOM_BYTES="${VLLM_ASCEND_POST_RESTORE_EP_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_POST_RESTORE_MOE_DISPATCH_HEADROOM_BYTES="${VLLM_ASCEND_POST_RESTORE_MOE_DISPATCH_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_FIRST_LIVE_PREFILL_HEADROOM_BYTES="${VLLM_ASCEND_FIRST_LIVE_PREFILL_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_FIRST_LIVE_PREFILL_LOW_FLOOR_HEADROOM_BYTES="${VLLM_ASCEND_FIRST_LIVE_PREFILL_LOW_FLOOR_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_EXTRA_ELASTIC_SAFETY_HEADROOM_BYTES="${VLLM_ASCEND_EXTRA_ELASTIC_SAFETY_HEADROOM_BYTES:-0}"
export VLLM_ASCEND_FLOOR_PREALLOC_HEADROOM_SAFETY_BYTES="${VLLM_ASCEND_FLOOR_PREALLOC_HEADROOM_SAFETY_BYTES:-0}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS:-377344}"
export VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4="${VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4:-280576}"
export VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE="${VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE:-0}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_FULLWORLD_EP_CACHE="${VLLM_ASCEND_MODE1_PARITY_KEEP_FULLWORLD_EP_CACHE:-1}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE="${VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE:-0}"
export VLLM_ASCEND_MODE1_PARITY_DROP_STALE_CACHE_AFTER_SHRINK="${VLLM_ASCEND_MODE1_PARITY_DROP_STALE_CACHE_AFTER_SHRINK:-0}"
export VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS="${VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS:-0}"
export VLLM_ASCEND_MODE1_PARITY_FORCE_CLEANUP_AFTER_FLOOR_GROUP_RELEASE="${VLLM_ASCEND_MODE1_PARITY_FORCE_CLEANUP_AFTER_FLOOR_GROUP_RELEASE:-1}"
export VLLM_ASCEND_MODE1_PARITY_SINGLE_LIVE_MC2_GROUP="${VLLM_ASCEND_MODE1_PARITY_SINGLE_LIVE_MC2_GROUP:-0}"
export VLLM_ASCEND_DISABLE_ELASTIC_MC2_GROUP_CACHE="${VLLM_ASCEND_DISABLE_ELASTIC_MC2_GROUP_CACHE:-0}"
export VLLM_ASCEND_POST_SHRINK_STAGING_RELEASE_EMPTY_CACHE="${VLLM_ASCEND_POST_SHRINK_STAGING_RELEASE_EMPTY_CACHE:-1}"
export VLLM_ASCEND_POST_SHRINK_STAGING_RELEASE_SYNC="${VLLM_ASCEND_POST_SHRINK_STAGING_RELEASE_SYNC:-1}"
export VLLM_ASCEND_MODE1_PARITY_RELEASE_WARMUP_CACHE="${VLLM_ASCEND_MODE1_PARITY_RELEASE_WARMUP_CACHE:-1}"
export VLLM_ASCEND_MODE1_PARITY_PRE_MOE_WARMUP_EMPTY_CACHE="${VLLM_ASCEND_MODE1_PARITY_PRE_MOE_WARMUP_EMPTY_CACHE:-1}"
export VLLM_ASCEND_MODE1_PARITY_POST_SHRINK_WARMUP="${VLLM_ASCEND_MODE1_PARITY_POST_SHRINK_WARMUP:-0}"
export VLLM_ASCEND_REPEAT_POST_SHRINK_MOE_DISPATCH_WARMUP="${VLLM_ASCEND_REPEAT_POST_SHRINK_MOE_DISPATCH_WARMUP:-0}"
export VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG="${VLLM_ASCEND_MODE1_PARITY_MC2_MEM_LOG:-1}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE="${VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE:-0}"
export VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_KINDS="${VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_KINDS:-dp,ep}"
export VLLM_ASCEND_MODE1_PARITY_DROP_OLD_FLOOR_BEFORE_REBUILD="${VLLM_ASCEND_MODE1_PARITY_DROP_OLD_FLOOR_BEFORE_REBUILD:-1}"
export VLLM_ASCEND_MODE1_PARITY_RELEASE_LIVE_OLD_FLOOR_ON_REBUILD="${VLLM_ASCEND_MODE1_PARITY_RELEASE_LIVE_OLD_FLOOR_ON_REBUILD:-1}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY="${VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY:-1}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_FULL_RESTORE="${VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_FULL_RESTORE:-0}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_PRE_REBUILD="${VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_PRE_REBUILD:-0}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_STASH="${VLLM_ASCEND_MODE1_PARITY_DEFER_GROUP_DESTROY_ON_STASH:-0}"
export VLLM_ASCEND_MODE1_PARITY_DEFER_DESTROY_FLOOR_GROUP_SIZES="${VLLM_ASCEND_MODE1_PARITY_DEFER_DESTROY_FLOOR_GROUP_SIZES:-1,2,4,8}"
export VLLM_ASCEND_MODE1_PARITY_SYNC_BEFORE_DEVICE_PG_RETIRE="${VLLM_ASCEND_MODE1_PARITY_SYNC_BEFORE_DEVICE_PG_RETIRE:-1}"
export VLLM_ASCEND_MODE1_PARITY_DESTROY_DEVICE_PG_ON_RETIRE="${VLLM_ASCEND_MODE1_PARITY_DESTROY_DEVICE_PG_ON_RETIRE:-1}"
export VLLM_ASCEND_MODE1_PARITY_DESTROY_CPU_PG_ON_RETIRE="${VLLM_ASCEND_MODE1_PARITY_DESTROY_CPU_PG_ON_RETIRE:-1}"
export VLLM_ASCEND_CUSTOM_MODE1_DEBUG=0
export VLLM_ASCEND_CUSTOM_MODE1_TIMING_EVENTS=0
export VLLM_ASCEND_CUSTOM_MODE1_KV_DIAG=0
export VLLM_ASCEND_CUSTOM_MODE1_ROLLOUT_RELOAD_DIAG="${VLLM_ASCEND_CUSTOM_MODE1_ROLLOUT_RELOAD_DIAG:-0}"
export VLLM_ASCEND_CUSTOM_MODE1_GLOBAL_TENSOR_SCAN="${VLLM_ASCEND_CUSTOM_MODE1_GLOBAL_TENSOR_SCAN:-0}"
export VLLM_ASCEND_MODE1_BATCH_DIRECT_NPU_IMPORT="${VLLM_ASCEND_MODE1_BATCH_DIRECT_NPU_IMPORT:-1}"
export VLLM_ASCEND_MODE1_ALLOW_SCALAR_DIRECT_NPU_IMPORT="${VLLM_ASCEND_MODE1_ALLOW_SCALAR_DIRECT_NPU_IMPORT:-0}"
export VLLM_ASCEND_MODE1_ALLOW_BATCH_INDEX_SELECT_EXPORT="${VLLM_ASCEND_MODE1_ALLOW_BATCH_INDEX_SELECT_EXPORT:-0}"
export VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_BATCH_EXPERTS="${VLLM_ASCEND_MODE1_DIRECT_NPU_IMPORT_BATCH_EXPERTS:-8}"
export VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC="${VLLM_ASCEND_MODE1_CPU_DP_METADATA_SYNC:-0}"

export HCCL_IF_BASE_PORT="${HCCL_IF_BASE_PORT:-47241}"
export MASTER_PORT="${MASTER_PORT:-26240}"
export VERL_HCCL_IF_BASE_PORT_START="${VERL_HCCL_IF_BASE_PORT_START:-47241}"

export HOME="$REPO_ROOT"
export OUTPUT_ROOT="${OUTPUT_ROOT:-$REPO_ROOT}"
export OUTPUT_SUBDIR="${OUTPUT_SUBDIR:-mode1_shrinkaware_521_oracle_floor4}"
export CONFIG_DIR="$PATCH_TREE/verl/trainer/config"
export PYTHONPATH="$PATCH_TREE${PYTHONPATH:+:$PYTHONPATH}"
export MODEL_PATH DISTCP_PATH TRAIN_FILE TEST_FILE

TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-32}"
MAX_PROMPT_LENGTH="${MAX_PROMPT_LENGTH:-1024}"
MAX_RESPONSE_LENGTH="${MAX_RESPONSE_LENGTH:-16384}"
ROLLOUT_N="${ROLLOUT_N:-16}"
ROLLOUT_MAX_NUM_SEQS="${ROLLOUT_MAX_NUM_SEQS:-32}"
ROLLOUT_MAX_NUM_BATCHED_TOKENS="${ROLLOUT_MAX_NUM_BATCHED_TOKENS:-$((MAX_PROMPT_LENGTH + MAX_RESPONSE_LENGTH))}"
ROLLOUT_GPU_MEMORY_UTILIZATION=0.9
TRAINER_TOTAL_EPOCHS="${TRAINER_TOTAL_EPOCHS:-1}"
DATASET_FRACTION_FOR_ORACLE="${DATASET_FRACTION_FOR_ORACLE:-0.005}"
SHRINK_AWARE_LOGGING="${SHRINK_AWARE_LOGGING:-false}"

ORACLE_DIR="${ORACLE_DIR:-$REPO_ROOT/mode1_shrinkaware_521_oracle_floor4/oracle}"
ORACLE_TRACE="${ORACLE_TRACE:-$ORACLE_DIR/baseline_mean_response_length_by_dataset_idx.json}"
ORACLE_PLAN="${ORACLE_PLAN:-$ORACLE_DIR/manual_521_rank_plan_summary.json}"
mkdir -p "$ORACLE_DIR"

python3 "$PATCH_TREE/tools/build_mode1_521_length_oracle.py" \
    --baseline-dir "$BASELINE_DIR" \
    --train-file "$TRAIN_FILE" \
    --output "$ORACLE_TRACE" \
    --plan-summary "$ORACLE_PLAN" \
    --steps 5 \
    --batch-size "$TRAIN_BATCH_SIZE" \
    --dataset-fraction "$DATASET_FRACTION_FOR_ORACLE"

cd "$PATCH_TREE"
stamp=$(date -u +%Y%m%dT%H%M%SZ)
tee_log="$REPO_ROOT/mode1_local_shrinkaware_521_oracle_floor4_${stamp}.log"

printf '[mode1 shrink-aware 5:2:1 oracle] runtime_cwd=%s\n' "$PATCH_TREE"
printf '[mode1 shrink-aware 5:2:1 oracle] launcher=%s tee_log=%s\n' "$LAUNCHER" "$tee_log"
printf '[mode1 shrink-aware 5:2:1 oracle] oracle=%s plan=%s baseline=%s\n' \
    "$ORACLE_TRACE" "$ORACLE_PLAN" "$BASELINE_DIR"
printf '[mode1 shrink-aware 5:2:1 oracle] model=%s distcp=%s train=%s test=%s\n' \
    "$MODEL_PATH" "$DISTCP_PATH" "$TRAIN_FILE" "$TEST_FILE"
printf '[mode1 shrink-aware 5:2:1 oracle] mode=1 floor=4 util=%s kv_cap_floor4=%s total_epochs=%s\n' \
    "$ROLLOUT_GPU_MEMORY_UTILIZATION" \
    "$VLLM_ASCEND_MODE1_PARITY_MAX_KV_TOKENS_FLOOR4" \
    "$TRAINER_TOTAL_EPOCHS"
printf '[mode1 shrink-aware 5:2:1 oracle] group_cache fixed_topology=%s cache_floor_groups=%s keep_mc2=%s keep_floor4=%s drop_old_floor_before_rebuild=%s release_live_old_floor=%s\n' \
    "$VLLM_ASCEND_MODE1_PARITY_FIXED_TOPOLOGY_REUSE" \
    "$VLLM_ASCEND_MODE1_PARITY_CACHE_FLOOR_GROUPS" \
    "$VLLM_ASCEND_MODE1_PARITY_KEEP_MC2_GROUP_CACHE" \
    "$VLLM_ASCEND_MODE1_PARITY_KEEP_FLOOR4_GROUP_CACHE" \
    "$VLLM_ASCEND_MODE1_PARITY_DROP_OLD_FLOOR_BEFORE_REBUILD" \
    "$VLLM_ASCEND_MODE1_PARITY_RELEASE_LIVE_OLD_FLOOR_ON_REBUILD"

bash "$LAUNCHER" \
    data.train_files="$TRAIN_FILE" \
    data.val_files="$TEST_FILE" \
    data.train_batch_size="$TRAIN_BATCH_SIZE" \
    data.max_prompt_length="$MAX_PROMPT_LENGTH" \
    data.max_response_length="$MAX_RESPONSE_LENGTH" \
    data.shuffle=False \
    actor_rollout_ref.model.path="$MODEL_PATH" \
    actor_rollout_ref.actor.megatron.dist_checkpointing_path="$DISTCP_PATH" \
    actor_rollout_ref.ref.megatron.dist_checkpointing_path="$DISTCP_PATH" \
    actor_rollout_ref.rollout.max_num_batched_tokens="$ROLLOUT_MAX_NUM_BATCHED_TOKENS" \
    actor_rollout_ref.rollout.max_num_seqs="$ROLLOUT_MAX_NUM_SEQS" \
    actor_rollout_ref.rollout.n="$ROLLOUT_N" \
    actor_rollout_ref.rollout.gpu_memory_utilization="$ROLLOUT_GPU_MEMORY_UTILIZATION" \
    actor_rollout_ref.rollout.shrink_aware.enable_shrink_aware_scheduling=true \
    actor_rollout_ref.rollout.shrink_aware.shrink_aware_mode=staged \
    actor_rollout_ref.rollout.shrink_aware.shrink_stages='[8,4]' \
    actor_rollout_ref.rollout.shrink_aware.survivor_selection_policy=manual \
    actor_rollout_ref.rollout.shrink_aware.intermediate_survivor_ranks='[8,9,10,11,12,13,14,15]' \
    actor_rollout_ref.rollout.shrink_aware.final_survivor_ranks='[8,9,10,11]' \
    actor_rollout_ref.rollout.shrink_aware.length_prediction_source=oracle_trace \
    actor_rollout_ref.rollout.shrink_aware.oracle_trace_path="$ORACLE_TRACE" \
    actor_rollout_ref.rollout.shrink_aware.assignment_policy=manual_5_2_1 \
    actor_rollout_ref.rollout.shrink_aware.enable_shrink_aware_logging="$SHRINK_AWARE_LOGGING" \
    trainer.total_epochs="$TRAINER_TOTAL_EPOCHS" \
    "$@" 2>&1 | tee "$tee_log"
