#!/usr/bin/env bash
set -euo pipefail

# Shrink-to-8 op-level sampled profiler. Captures one execute_model/dummy step
# every 500 decode steps in the tail by default.

run_id=$(date +%Y%m%d%H%M%S)
export WJ_RECORDS_DIR=${WJ_RECORDS_DIR:-/home/sharedata/wj_records}
export VLLM_ASCEND_NPU_UTIL_CSV=${VLLM_ASCEND_NPU_UTIL_CSV:-"${WJ_RECORDS_DIR}/npu_util/${run_id}_shrink8_op_profile.csv"}
export VLLM_ASCEND_BUCKET_OP_PROFILE=1
export VLLM_ASCEND_BUCKET_OP_PROFILE_DIR=${VLLM_ASCEND_BUCKET_OP_PROFILE_DIR:-"${WJ_RECORDS_DIR}/op_profiles/${run_id}_shrink8"}
export VLLM_ASCEND_BUCKET_OP_PROFILE_START_STEP=${VLLM_ASCEND_BUCKET_OP_PROFILE_START_STEP:-12500}
export VLLM_ASCEND_BUCKET_OP_PROFILE_END_STEP=${VLLM_ASCEND_BUCKET_OP_PROFILE_END_STEP:-16000}
export VLLM_ASCEND_BUCKET_OP_PROFILE_INTERVAL_STEPS=${VLLM_ASCEND_BUCKET_OP_PROFILE_INTERVAL_STEPS:-500}
export VLLM_ASCEND_BUCKET_OP_PROFILE_RANKS=${VLLM_ASCEND_BUCKET_OP_PROFILE_RANKS:-all}
export VLLM_ASCEND_BUCKET_OP_PROFILE_LEVEL=${VLLM_ASCEND_BUCKET_OP_PROFILE_LEVEL:-level0}
export VLLM_ASCEND_BUCKET_OP_PROFILE_SYNC=${VLLM_ASCEND_BUCKET_OP_PROFILE_SYNC:-1}
export VLLM_ASCEND_BUCKET_OP_PROFILE_ANALYSIS=${VLLM_ASCEND_BUCKET_OP_PROFILE_ANALYSIS:-1}
mkdir -p "${VLLM_ASCEND_BUCKET_OP_PROFILE_DIR}" "$(dirname "${VLLM_ASCEND_NPU_UTIL_CSV}")"

echo "[elastic op profile] mode=shrink8 dir=${VLLM_ASCEND_BUCKET_OP_PROFILE_DIR} csv=${VLLM_ASCEND_NPU_UTIL_CSV} start=${VLLM_ASCEND_BUCKET_OP_PROFILE_START_STEP} end=${VLLM_ASCEND_BUCKET_OP_PROFILE_END_STEP} interval=${VLLM_ASCEND_BUCKET_OP_PROFILE_INTERVAL_STEPS} ranks=${VLLM_ASCEND_BUCKET_OP_PROFILE_RANKS}"

bash "$(dirname "$0")/wj_train_grpo_qwen30b_a3b_16die_true_weight_eager_shrink8_util.sh" "$@"
